### ISSUE TITLE
Expose MeshIO ExportMesh and ImportMesh in Python binding like in C

### ISSUE THREAD

**Issue by bguan** [elalish/manifold#1013]
Trying to use Manifold3D in a python project but stuck on this issue and had to cobble together a homegrown export to STL function, would rather use whats native in Manifold.

**Comment by elalish** [comment]
Let's move this discussion over to #1010. In Python, I would recommend using `trimesh` for 3D file I/O, as in our [example](https://colab.sandbox.google.com/drive/1VxrFYHPSHZgUbl9TeWzCeovlpXrPQ5J5?usp=sharing). File I/O is a pretty big lift, so we have to be careful what we take on here, vs. use external libraries for.
