### ISSUE TITLE
add Triangulate() to C bindings?

### ISSUE THREAD

**Issue by james-bern** [elalish/manifold#1028]
Hey!

I'm using manifold to build a CAD program in C/C++.

I've been using the C bindings, and want to use the [Triangulate() function](https://manifoldcad.org/docs/html/group___triangulation.html#ga4bc8044ce1f24b682561f40d73363825) to do some graphics stuff (preview the cross section selected by the user).

I don't see this function in the C bindings.
**Does it make sense to add Triangulate() to the C bindings?** (And does this question even make sense?)
If it does, I can figure out how to do it, and submit a pull request. 🙂👍

Best,
Jim

**Comment by elalish** [comment]
Yes, absolutely! It was actually on our list, but we've been a bit too busy getting v3.0 finished up. If you're quick you can still make the release. 👍

**Comment by pca006132** [comment]
That said, if you are using c++ already, it makes more sense to directly use our c++ code :)

**Comment by james-bern** [comment]
> Yes, absolutely! It was actually on our list, but we've been a bit too busy getting v3.0 finished up. If you're quick you can still make the release. 👍

Rockin'! I'll give it my best shot :)
Also thank you so much for making this software!--It's been super inspiring for me and my students.

> That said, if you are using c++ already, it makes more sense to directly use our c++ code :)

Roger that! I'm more on the C side (not using the C++ STL) so I'll probably stick with the C bindings for this current project but will plan to directly use the C++ for future more fully C++ stuff.

**Comment by elalish** [comment]
Excellent, thanks! You speak of students - what do you teach? If any of them get the computational geometry bug, we try to run GSoC projects in the summers.

**Comment by james-bern** [comment]
> Excellent, thanks! You speak of students - what do you teach? If any of them get the computational geometry bug, we try to run GSoC projects in the summers.

I teach undergrad CS (intro, graphics, robotics). :) Will do!
