### ISSUE TITLE
OneDPL not in use?

### ISSUE THREAD

**Issue by kintel** [elalish/manifold#1039]
I found these OneDPL references still in there:
https://github.com/elalish/manifold/blob/74f340a8e79b5b6099fc43641fa27f6007bdcd93/manifoldConfig.cmake.in#L22-L24

Should these just be removed?

**Comment by elalish** [comment]
Hmm, yeah that seems outdated. Is that right @pca006132?

**Comment by pca006132** [comment]
yes, I thought I removed it before...
