### ISSUE TITLE
Merge MANIFOLD_EXCEPTIONS and MANIFOLD_DEBUG

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#1041]
Currently our readme says our `MANIFOLD_DEBUG` flag controls both assertions and exceptions, but in fact we have a second CMake flag: `MANIFOLD_EXCEPTIONS`, which defaults to ON. However, nearly all of our exceptions use `DEBUG_ASSERT`, for which *both* debug and exceptions must be enabled to fire. Only `Vec` uses `ASSERT` (and hull, but I think that's a mistake) which is enabled even when debug is off. I can't imagine a situation where an app is going to be able to do much if we throw a `Vec` assertion - it's basically just a seg-fault, and it certainly shouldn't happen if we've written our code properly. 

I propose we merge `MANIFOLD_EXCEPTIONS` into `MANIFOLD_DEBUG` and use only a single kind of `ASSERT`. This will have the effect of turning exceptions off by default, which seems right? Feedback welcome - and WDYT @pca006132?

**Comment by pca006132** [comment]
Sounds good to me.
