### ISSUE TITLE
Properties regression

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#1050]
Well, score one for our release checklist - I found a bug that got by our tests:
<img width="705" alt="image" src="https://github.com/user-attachments/assets/f23a9381-999a-4bc2-b436-da769da9dc4b">
It's not supposed to look noisy like that. Appears to be a problem in `GetMeshGL` - I'll get this fixed for v3.0.

**Comment by elalish** [comment]
@pca006132 This is weird - my local Vite version is showing this changed worked, but it deployed almost an hour ago and I'm still seeing the old behavior on ManifoldCAD.org.

**Comment by pca006132** [comment]
Maybe we should check the wasm hash to see if it got the latest version? Not sure if it is a cache issue or the CI getting the wrong binary...

**Comment by elalish** [comment]
Well, it's working now after another PR got merged. Should probably look into that someday...
