### ISSUE TITLE
project() does not seem to work

### ISSUE THREAD

**Issue by matas-bitbybit-dev** [elalish/manifold#1070]
Hey, great project, thanks for making it happen. Maybe I don't understand something, but I would expect the output of this operation to be a cylinder, but it says manifold is empty, here's the code that reproduces that on https://manifoldcad.org

```
const { sphere } = Manifold;
const s = sphere(1);
const cs = s.project();
const result = cs.extrude(1);
```

**Comment by elalish** [comment]
Thanks for the repro! Looks like the error is in the WASM bindings - working on it. `slice` still works at least.

**Comment by matas-bitbybit-dev** [comment]
:) Slice works perfect. Just one more question about revolve, sry if it should go to another issue. Maybe you could check if that's the output that is correct.

I have this script
```
const { square } = CrossSection;
const s = square(1, false);
const translatedSquare = s.translate([3,0]);
const ex = translatedSquare.extrude(2);
const rev = translatedSquare.revolve(32, 90);
const sum = ex.add(rev);
const result = sum;
```

And I get this output 
<img width="655" alt="image" src="https://github.com/user-attachments/assets/d5330662-3533-4437-b400-ae875d2474a8">

It seems that revolve takes the profile cross section and positions it vertically, while extrude keeps the cross section on the ground plane. Maybe there's some z and y mix happening on revolve? Is that intentional? Thanks!

**Comment by elalish** [comment]
Yes, that's working as intended - revolving about the z-axis feels slightly less arbitrary than other choices - I believe the docs describe this? If they're not clear, we should update them.

**Comment by matas-bitbybit-dev** [comment]
> Yes, that's working as intended - revolving about the z-axis feels slightly less arbitrary than other choices - I believe the docs describe this? If they're not clear, we should update them.

Sorry, docs explain this indeed. Thank you.
