### ISSUE TITLE
C binding function manifold_calculate_normals contains parameter type mistmatch

### ISSUE THREAD

**Issue by NickUfer** [elalish/manifold#1083]
The [manifold_calculate_normals](https://github.com/elalish/manifold/blob/11387fb871077953cedd3e08c0c70afe5969b3f0/bindings/c/include/manifold/manifoldc.h#L216-L218) function has a parameter called `min_sharp_angle` of type `int`. This function then calls [Manifold::CalculateNormals](https://github.com/elalish/manifold/blob/11387fb871077953cedd3e08c0c70afe5969b3f0/src/manifold.cpp#L710-L714) where the equivalent parameter, `minSharpAngle`, is of type `double` (formerly `float`).

This type mismatch limits the function's potential by restricting the precision with which sharp angles are handled.

**Comment by elalish** [comment]
Yup, looks like an error - want to send a PR?

**Comment by NickUfer** [comment]
Sure, can do that later today
