### ISSUE TITLE
Inconsistent use of int and size_t in C Bindings for std::vector Types

### ISSUE THREAD

**Issue by NickUfer** [elalish/manifold#1089]
The types `ManifoldCrossSectionVec`, `ManifoldPolygon`, `ManifoldPolygons` and `ManifoldManifoldVec` represent `std::vector` in the C bindings. However, their API functions mix the use of `size_t` and `int` for lengths and indices. For example:

ManifoldCrossSectionVec:
```c
size_t manifold_cross_section_vec_length(ManifoldCrossSectionVec *csv); // uses size_t
ManifoldCrossSection *manifold_cross_section_vec_get(void *mem, ManifoldCrossSectionVec *csv, int idx); // uses int
```

SimplePolygon:
```c
size_t manifold_simple_polygon_length(ManifoldSimplePolygon *p); // uses size_t
ManifoldVec2 manifold_simple_polygon_get_point(ManifoldSimplePolygon *p, int idx); // uses int
```

ManifoldPolygons:
```c
size_t manifold_polygons_length(ManifoldPolygons *ps); // uses size_t
ManifoldSimplePolygon *manifold_polygons_get_simple(void *mem, ManifoldPolygons *ps, int idx); // uses int
```

ManifoldManifoldVec:
```c
size_t manifold_manifold_vec_length(ManifoldManifoldVec *ms); // uses size_t
void manifold_manifold_vec_set(ManifoldManifoldVec *ms, int idx, ManifoldManifold *m); // uses int
ManifoldManifold *manifold_manifold_vec_get(void *mem, ManifoldManifoldVec *ms, int idx); // uses int
```

### Problem
The use of `int` for indices is problematic because `int` cannot represent the full range of values that `size_t` can. This mismatch can lead to:

- **Potential bugs**: Negative or out-of-range values for indices.
- **Type safety issues**: Implicit conversions and sign mismatches.
- **Platform-specific inconsistencies**: Differences in the size of `int` and `size_t` across platforms.

### Suggested Solution
All `int` parameters used for indices in the API should be updated to `size_t` to ensure consistency with the `std::vector` representation and avoid these issues.
Would be open to contribute a fix 😄

**Comment by pca006132** [comment]
Yeah, this is probably some old code we forgot to change to `size_t`. PR is welcomed.
