### ISSUE TITLE
suggestion: fuzzing

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#110]
Perhaps we can use https://llvm.org/docs/LibFuzzer.html to test the library? Generate a number of primitive objects, perform random translation/scaling/rotation and boolean operations for them. There are a few things we can test for:

1. Memory usage.
2. Should not crash.
3. Compare with other libraries like CGAL? Not sure about if this is possible.

**Comment by elalish** [comment]
A code coverage report at the very least would be very beneficial!

**Comment by pca006132** [comment]
The fuzzer will just give us an array of bytes, we will transform that into operations for geometric objects, so in principle we can favor generating colinear/coplanar/complex holes in addition to random transforms. Perhaps I can try to write a prototype for this later.

**Comment by pca006132** [comment]
feel that we really need this for the triangulator, will look into this later.
