### ISSUE TITLE
MANIFOLD_DEBUG with CI

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#1105]
Currently, `MANIFOLD_DEBUG` is disabled in many of the CI jobs. We should probably build most of them with `MANIFOLD_DEBUG` enabled, except for the wasm case where we want the uploaded build to be built without `MANIFOLD_DEBUG` for smaller binary size.

**Comment by elalish** [comment]
Did you fix this already?

**Comment by pca006132** [comment]
yes
