### ISSUE TITLE
Security Integrate manifold with OSS-Fuzz for Continuous Fuzz Testing

### ISSUE THREAD

**Issue by Shivam7-1** [elalish/manifold#1111]
Hii @elalish  

 I’d like to propose integrating manifold with Google's  continuous fuzz testing platform designed to improve the stability and security of open-source projects.

Why Integrate manifold with OSS-Fuzz?

Improved Stability: OSS-Fuzz can automatically detect edge-case bugs, crashes, and security vulnerabilities in manifold codebase.
Enhanced Reliability: Continuous fuzzing ensures that untrusted inputs, such as data from sensors, communication protocols, or user-defined configurations, are handled robustly.
Proactive Bug Fixes: By identifying potential issues early, OSS-Fuzz helps maintain a stable and secure codebase.

So Can I move Forward with this

**Comment by pca006132** [comment]
Hi, do you have any idea about the advantage of OSS-Fuzz over other fuzzers like [fuzztest](https://github.com/google/fuzztest)? We already have fuzz tests using that, though it is broken for now for unknown reason and documentation for fuzztest is a bit sparse.

Do you have a plan for integrating this? E.g. what to fuzz, and how to set up stuff with cmake.

**Comment by pca006132** [comment]
Looking at your issue comments as well as PRs to other projects, they make me feel that you are using AI tools to automatically generate patches and write generic comments about them. I think I will close this for now until we can trust that you are not a robot and have the skills/interest in doing what you have mentioned here.
