### ISSUE TITLE
How to set property per (triangle, vertex) tuple?

### ISSUE THREAD

**Issue by shikui08** [elalish/manifold#1114]
AFAIK, the function `Manifold::SetProperties` don't distinguish vertex shared by multiple triangles.

`
const int numTri = NumTri();
      triProperties.resize(numTri);
      for (int i = 0; i < numTri; ++i) {
        for (const int j : {0, 1, 2}) {
          triProperties[i][j] = pImpl->halfedge_[3 * i + j].startVert;
        }
      }
`
Say I want a cube with sharp edges, so normal don't blend.  How  can I possibly do that?

**Comment by pca006132** [comment]
I think you need to use `MeshGL` for this. Duplicate the vertices, and set the appropriate `mergeFromVert` and `mergeToVert`.

**Comment by pca006132** [comment]
Feel free to open a discussion if needed. Closing for now.
