### ISSUE TITLE
[Question] Create bindings or DLL file to use in Rust

### ISSUE THREAD

**Issue by AlbertoVPersonal** [elalish/manifold#1117]
Hi,

We want to do some tests with the library in Rust but we are not able to do it.

I'mg going to describe the process.

### Environment

- Windows 11 Pro x64

### Steps
- Download the latest release [1]
- Generate the library

```bash
.cmake.exe . -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DMANIFOLD_DEBUG=ON -DMANIFOLD_PAR=ON -A x64 -B build

# in the 'build' folder
cmake.exe --build . --target ALL_BUILD --config Release
```

- Create a basic program in Rust

I know how to load the `lib` file but I don't know what functions are available.

Is it possible to generate a DLL library? I tried `-DBUILD_SHARED_LIBS=ON` but the folder `build\bin\Release` does not contain any libraries. Only it has several EXE files.

Thanks for advance.

Regards,
Alberto

[1]: https://github.com/elalish/manifold/releases/tag/v3.0.0

**Comment by pca006132** [comment]
You can try to use https://github.com/NickUfer/manifold3d-rs for rust binding. For dll library, it should be generated in `build/lib/Release`.

**Comment by pca006132** [comment]
Can you show the list of files under build, as well as your cmake command and the specific version you are using?

**Comment by pca006132** [comment]
> > For DLL locations, try the latest master. I should have moved them to `build\lib\Release`.
> 
> I have been generated them from `master`. If you consider that I don't understand your comment, let me know what path I should search in the repo or my local folders.

Interesting, we should test it in our CI.

**Comment by WilstonOreo** [comment]
I have also written a manifold wrapper with cxx.rs: https://github.com/WilstonOreo/manifold-rs

**Comment by pca006132** [comment]
Closing as the DLL location issue was fixed.
