### ISSUE TITLE
Please support nanobind 2.4.0 

### ISSUE THREAD

**Issue by pbsds** [elalish/manifold#1119]
The nanobind dependency is limited to versions at or below 2.2.0:

https://github.com/elalish/manifold/blob/f48111c43c39ff515e2a84d5f35723b77ec57c2a/pyproject.toml#L29

It seems this limit was set out of caution in https://github.com/elalish/manifold/pull/987#issuecomment-2422510770

Discovered in https://github.com/NixOS/nixpkgs/pull/366800

**Comment by pca006132** [comment]
I'm thinking if there is a better way, maybe to check this version in cmake instead and issue a warning if the version is not yet supported? This way users should be able to debug the issue without blocking downstream users.

**Comment by pbsds** [comment]
Common is to stick with semantic versioning and limit nanobind to `<3.0.0`, where breaking changes are expected. I've yet to fully grok https://github.com/elalish/manifold/issues/947, but it seems like it caused a build error and not some obscure runtime error.

**Comment by pca006132** [comment]
Yeah, it was some build error. Will do this instead. Thanks!
