### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by rsaccon** [elalish/manifold#112]
@pca006132 has in his fork a branch with Python bindings. Just to see how far I get, I tried to apply those patches for python to the most recent upstream manifold which now builds perfectly with `CPP` compile option on my mac. The python bindings and the example `pythonTest` seemed to compile perfectly. In the manifold root folder  where the python test script `test.py` I created a symbolic link named `pythonTest` to  the compiled shared library and assumed I could run `python test`. Well, that is how far I got:
```
    from pythonTest import ManifoldSet, Polygons
ModuleNotFoundError: No module named 'pythonTest'
```
I am aware that this is all very early stage and unstable and the examples at [pybind](https://github.com/pybind) are a tiny bit different (using `pip` to compile and install the examples).  So what step am I missing to get that module imported ?

**Comment by pca006132** [comment]
Can you show the input for `ls -la` in the directory where you run the python script?

**Comment by pca006132** [comment]
btw, I thought I was the only one who uses my fork, so I do things like rebase and force push quite frequently, sorry if that annoys you. I planned to upstream the python changes, but there are still a few blockers:

1. difference is not yet optimized with manifold set, still thinking about what is the best way to do that.
2. the performance optimization in manifold set often triggers weird errors like #102 and #109 when I try to port some benchmarks from https://gist.github.com/ochafik/2db96400e3c1f73558fcede990b8a355 for testing.

For now maybe you can try to use [this branch](https://github.com/pca006132/manifold/tree/opt), I will try to keep it stable and avoid force pushing to it.

**Comment by elalish** [comment]
I would love to have python bindings; could we work on upstreaming that before dealing with the manifold set issues? Would be great to have Python building and testing in the CI.

**Comment by pca006132** [comment]
Yes that should be simple to do. Will submit a PR tmr.

**Comment by rsaccon** [comment]
@pca006132 here the `ls -la`
```
(base) robertosaccon@MacBook-Pro manifold % ls -al
total 368
drwxr-xr-x  32 robertosaccon  staff    1024 11 May 16:54 .
drwxr-xr-x  21 robertosaccon  staff     672 11 May 16:48 ..
-rw-r--r--@  1 robertosaccon  staff    6148 11 May 09:22 .DS_Store
drwxr-xr-x   3 robertosaccon  staff      96 10 May 22:51 .devcontainer
-rw-r--r--   1 robertosaccon  staff     308 10 May 22:51 .dockerignore
drwxr-xr-x  16 robertosaccon  staff     512 11 May 17:16 .git
drwxr-xr-x   3 robertosaccon  staff      96 10 May 22:51 .github
-rw-r--r--   1 robertosaccon  staff    1519 10 May 22:51 .gitignore
-rw-r--r--   1 robertosaccon  staff     409 10 May 22:51 .gitmodules
drwxr-xr-x   5 robertosaccon  staff     160 10 May 22:51 .vscode
-rw-r--r--   1 robertosaccon  staff    2648 11 May 09:26 CMakeLists.txt
-rw-r--r--   1 robertosaccon  staff     566 10 May 22:51 Dockerfile
-rw-r--r--   1 robertosaccon  staff  112798 10 May 22:51 Doxyfile
-rw-r--r--   1 robertosaccon  staff   11357 10 May 22:51 LICENSE
-rw-r--r--   1 robertosaccon  staff    4647 10 May 22:51 README.md
-rw-r--r--   1 robertosaccon  staff     601 10 May 22:51 assimp.diff
drwxr-xr-x  16 robertosaccon  staff     512 11 May 09:33 build
drwxr-xr-x   5 robertosaccon  staff     160 10 May 22:51 collider
-rwxr-xr-x   1 robertosaccon  staff    1555 10 May 22:51 deploy.sh
-rw-r--r--   1 robertosaccon  staff     115 10 May 22:51 docker-compose.debug.yml
-rw-r--r--   1 robertosaccon  staff      71 10 May 22:51 docker-compose.yml
drwxr-xr-x   5 robertosaccon  staff     160 10 May 22:51 docs
drwxr-xr-x   5 robertosaccon  staff     160 11 May 02:57 manifold
drwxr-xr-x   5 robertosaccon  staff     160 10 May 22:51 meshIO
drwxr-xr-x   5 robertosaccon  staff     160 10 May 22:51 polygon
lrwxr-xr-x   1 robertosaccon  staff      43 11 May 10:22 pythonTest -> build/tools/pythonTest.cpython-38-darwin.so
drwxr-xr-x   6 robertosaccon  staff     192 10 May 22:51 samples
drwxr-xr-x   9 robertosaccon  staff     288 10 May 22:51 test
-rw-r--r--   1 robertosaccon  staff    8072 11 May 10:47 test.py
drwxr-xr-x   9 robertosaccon  staff     288 11 May 09:22 third_party
drwxr-xr-x   8 robertosaccon  staff     256 11 May 02:57 tools
drwxr-xr-x   4 robertosaccon  staff     128 10 May 22:51 utilities
```

**Comment by rsaccon** [comment]
@pca006132 Oh yeah, that was it, thanks a lot. It doesn't fully work yet, but I will base my further experimenting on the `opt` branch your suggested.

**Comment by rsaccon** [comment]
Ok, checked out the `opt` branch and all just magically worked ! With very simple Python commands I can create and manipulate manifolds. This is totally awesome !
