### ISSUE TITLE
Add clang-format pre-commit hook

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#130]
I'm pretty sure there's a way to tell Github to run clang-format on any submitted PR, which would be nice both with viewing diffs and with keeping the code base consistent. I have VSCode set up to use the standard `google` style with clang-format, so that's what I'd like automatically applied for other contributors.

**Comment by pca006132** [comment]
Maybe we should add a `.clang-format` file with
```yaml
BasedOnStyle: Google
```

and add a github action to check for formatting on PRs? Error when the source files are not formatted properly.

iirc we cannot enforce pre-commit hook and using GitHub action for formatting commit seems an overkill and may make the history messy.

**Comment by elalish** [comment]
Sure, that sounds good.

**Comment by fire** [comment]
Block the merge until all the pre-commit hooks pass. Add a action to compile. Add an action to test if clang format has changes.
