### ISSUE TITLE
Simplify face triangulation

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#135]
Currently, vertices coming from different meshes are labelled with different `meshID`, preventing them from merging. However, when joining manifolds face-to-face, it may be desirable to assign vertices with the same original meshID the same meshID and redo/simplify the face triangulation to reduce the number of vertices.

For example, consider the result of the `Boolean.FaceUnion` test:
![image](https://user-images.githubusercontent.com/12198657/172041351-1d62139f-26fb-4e3f-9dfa-bb5bca66f562.png)

Can we make it so that it will not have vertices in the middle?

**Comment by elalish** [comment]
So this is intentional: imagine the two cubes have different textures applied; if these middle verts are removed, there is no way to apply the original textures. To get what you want, you simply need to call `AsOriginal` on the result. If that is not already calling `SimplifyTopology` internally, it probably should.

**Comment by pca006132** [comment]
Oh indeed, `SimplifyTopology` does work. I'm thinking about removing the `originalIDs` map and make `meshID` the same as original mesh ID, so adding two manifolds with the same original mesh ID will automatically give the simplified result.

It seems to me that some of the errors in samples test (mentioned in https://github.com/elalish/manifold/pull/125#issuecomment-1140256198) might be related to #102.

Should we keep this open until we fix this (removing the `originalIDs` map) or close this?

**Comment by elalish** [comment]
No, I don't think we want to do that, for exactly the reason I put above. Even if those two boxes are identical and have the same textures applied to their faces (same `originalID`), you will still be unable to re-apply those textures to the result if those internal verts are missing.

**Comment by pca006132** [comment]
Oh OK I see, sorry I wasn't thinking about texture previously. Just thought of a way of optimizing this with lazy evaluation though :).
