### ISSUE TITLE
Seg fault on CUDA

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#172]
Ugh, I really wish our CI had a GPU. I just realized I've been neglecting to test on CUDA locally, and honestly I'm not sure for how long. However, today I noticed that `Manifold.SmoothSphere` gives: `for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered" thrown in the test body.` and then `Manifold.ManualSmooth` seg faults, but just on CUDA.

I went back to #157 and found the same problem there. I'm having some trouble getting things to build before that, probably because I need different flags or something. @pca006132 Can you repro?

**Comment by fire** [comment]
We've been using swift shader at godot engine, but unclear if that's possible.

**Comment by pca006132** [comment]
My old laptop have some hardware issues, so I cannot run CUDA tests for now.

I plan to build a PC later this year (at the end of this year, probably) with nvidia graphics card, so perhaps I can setup a build bot or something to run the tests with CUDA. 

Compute shader is an entirely different thing comparing with CUDA, and we rely heavily on thrust for implementing GPU algorithms, so I don't think we can use shaders instead.

**Comment by pca006132** [comment]
But I can have a look at the build error you encountered. Can you show me the commit hash of the version that you are trying to build?

**Comment by elalish** [comment]
Thanks, but I think it's just my VSCode setup. I'll figure it out (it worked before).
