### ISSUE TITLE
Test input that causes the mesh to be invisible

### ISSUE THREAD

**Issue by fire** [elalish/manifold#174]
I wasn't able to recreate the steps, but here are the scene files and screenshots. Note that this file isn't an exact reproducable test case.

1. the meshes separated
2. bool meshes
3. By moving the meshes when they are chained, there are configurations that make the mesh disappear.

[node_3d.zip](https://github.com/elalish/manifold/files/9254328/node_3d.zip)

Before:

![image](https://user-images.githubusercontent.com/32321/182689552-a568d541-ac0b-4e42-bba5-b6251e76d9a8.png)

After:

![image](https://user-images.githubusercontent.com/32321/182689731-4909de60-8213-4623-8122-2ad843a30f3e.png)

**Comment by fire** [comment]
I forgot to do an is manifold check. The torus is not manifold.

**Comment by elalish** [comment]
And with my latest changes, non-manifold input will simply be empty, so you'll want to check `Status()` instead.
