### ISSUE TITLE
Read vertNormal for Smooth

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#185]
Currently the `vertNormal` supplied in a `Mesh` is ignored and recalculated instead. Ideally it should be read and used to form the `halfedgeTangent` vector. Need to ensure `vertNormal_` is making it through `SimplifyTopology()` without getting broken.

**Comment by elalish** [comment]
I think I'm not going to bother with this, as `Mesh` is not as useful as `MeshGL` and there's no guarantee that normals should be unique per-vert.

**Comment by hrgdavor** [comment]
I started playing with manifold a bit, and used getMesh() ... had to recalculate normals
A quick question: is meshgl better for display, and how to get it from JS ?

**Comment by pca006132** [comment]
yeah, `meshGL` represent vertex positions and triangles as flat buffers, and those can be feed into some graphics APIs directly (or with some minor changes) iirc, so the performance is better. And there are some additional information that you can get from `MeshGL`.

I think the `getMesh` API in JS is exporting the `MeshGL`, we do not expose `Mesh` in js. We should probably mention this in the documentation though.
