### ISSUE TITLE
Cache intermediate results automatically

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#199]
Regarding this [comment](https://github.com/elalish/manifold/pull/171#issuecomment-1214282589) @pca006132, I did a little test with `./manifold_test --gtest_filter=Samples.Frame -v` before and after removing the two cache-forcing [lines](https://github.com/elalish/manifold/blob/master/samples/src/rounded_frame.cpp#L35). I'm seeing at least double the number of Boolean operations when I remove those lines. Is there a way to make the `CsgNode` aware of when it's being used more than once so it can skip flattening and allow reuse instead? Maybe some kind of ref-counter?

**Comment by pca006132** [comment]
Yes, we are already using ref-counter so maybe we can do use [use_count](https://en.cppreference.com/w/cpp/memory/shared_ptr/use_count).

**Comment by elalish** [comment]
Sounds good; do you want to give it a try?

**Comment by pca006132** [comment]
```diff
diff --git a/src/manifold/src/csg_tree.cpp b/src/manifold/src/csg_tree.cpp
index 9e31137..d11fb5f 100644
--- a/src/manifold/src/csg_tree.cpp
+++ b/src/manifold/src/csg_tree.cpp
@@ -366,7 +366,7 @@ std::vector<std::shared_ptr<CsgNode>> &CsgOpNode::GetChildren(
 
   CsgNodeType op = op_;
   for (auto &child : children_) {
-    if (child->GetNodeType() == op) {
+    if (child->GetNodeType() == op && child.use_count() == 1) {
       auto grandchildren =
           std::dynamic_pointer_cast<CsgOpNode>(child)->GetChildren(finalize);
       int start = children_.size();
```

Indeed it works, but there is still 2 additional boolean operations, not sure what they are, will check later.

**Comment by elalish** [comment]
Excellent, I love a simple fix! Looking forward to the PR. :+1:

**Comment by elalish** [comment]
Any more progress on this, or would you like me to take a look?

**Comment by pca006132** [comment]
Sorry I am a bit busy recently, maybe you can take a look at it first.

**Comment by pca006132** [comment]
OK I understand what is going on for that 2 additional boolean operations now. The problem is that we are cloning all children when we do `CsgOpNode::Transform`, so we kind of lose track of how many copies of the nodes are there. A way to mitigate this is to share the child list, but I'm running into some problems while implementing this.
