### ISSUE TITLE
WASM produces wrong model for models with more than 32 parts

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#202]
```javascript
const n = 32;
let foo = Module.cube(1, 1, 1);
let bar = Module.cube(1, 1, 1);
for (let i = 1; i < n; i++)
  bar.add(Module.cube(1, 1, 1).translate(2*(Math.floor(i/10)), 2*(i%10), 0));
mesh.geometry = mesh2geometry(bar.getMesh());
```

Three.js (both the simple example and the model-viewer) will render something like this (32 and 100 respectively):
![image](https://user-images.githubusercontent.com/12198657/190674938-1829417f-0556-4f4a-9095-46870543fd11.png) ![image](https://user-images.githubusercontent.com/12198657/190674987-3f527333-e7ab-485a-8808-769c06688758.png)

`IsManifold()` returns true and the computed volume is correct. Not sure if this is an issue specific to our wasm build or do we produce corrupted models but were automatically fixed by other viewers.

**Comment by elalish** [comment]
Ah, this turned out to be kind of silly. Someone decided to use a `Uint8Array` for the triangle indices in `mesh2geometry` and I totally missed it in code review. It was just rolling over; `Uint32Array` fixes it.
