### ISSUE TITLE
Bounding CSG tree depth

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#215]
For the simplest implementation of compose, i.e.
```js
function compose(objs: Manifold[]): Manifold {
  let result = objs.pop();
  for (let obj of objs) {
    result = union(result, obj);
  }
  return result;
}
```

The CSG tree will be a linked list. This is problematic because evaluating this will involve a very deep recursion, excessive copying etc. Previously I thought this is not an issue due to tree flattening, but #199 restricted the cases that we can perform such flattening, and JavaScript binding will not decrement the reference count automatically, so the tree will not be flattened. Also, that flattening will not bound the height, it just makes it unlikely to have a very deep tree in the normal case.

I'm thinking about implementing this by storing weak references to the parent of the CSG tree node, so we can propagate the depth of the nodes when we update some of the element (by evaluating it).

**Comment by elalish** [comment]
Is there a way to make the JS binding decrement the reference count automatically? That feels like the most elegant solution here, and to other problems as well. Not sure about the feasibility though...

**Comment by pca006132** [comment]
I don't think it is possible to make JS binding decrement the reference count automatically, if we don't implement our own compiler/interpreter. Thinking about it, I think we probably don't need to store weak references, just store a depth would be fine.

**Comment by pca006132** [comment]
It seems that wasm is really bad at recursion, for some reason. For the following example:
```typescript
function combine1(objs: Manifold[]): Manifold {
    let a = [];
    let b = objs;
    while (b.length > 1) {
        for (let i = 0; i + 1 < b.length; i += 2)
            a.push(union(b[i], b[i+1]));
        if (b.length % 2 == 1)
            a.push(b[b.length - 1]);
        b = a;
        a = [];
    }
    return b[0];
}

function combine2(objs: Manifold[]): Manifold {
    let a = objs.pop();
    for (let x of objs)
        a = a.add(x);
    return a;
}

let spheres = [];
for (let i = 0; i < 10; i++) {
    for (let j = 0; j < 10; j++) {
        const s = sphere(1.1/2, 50).translate([i, j, 0]);
        spheres.push(s);
    }
}

const result = combine1(spheres);
```

For `combine1`, it runs for ~800ms, and `combine2` runs for ~4000ms. For comparison, combine2 in Python just runs in 0.2s (although it is parallel).

**Comment by pca006132** [comment]
Weird, it is still slow on wasm even after bounding the tree depth. No idea what is going on with wasm.

**Comment by pca006132** [comment]
I guess wasm is not slower due to recursion, but due to memory copy. We can probably close this after merging #220 as this is not related to performance.

**Comment by elalish** [comment]
I think your `combine1` and `combine2` timings make some sense. In the single-threaded case, the problem is dominated by the collider (O nlogn in triangles), where in parallel, that gets so fast that it's dominated by triangulation (O number of intersections). In `combine1`, most of your `n`s are smaller, while in `combine2` they quickly grow, even though the actual intersections haven't changed.

**Comment by pca006132** [comment]
Indeed, I was thinking that we can flatten the tree and do batch union automatically, which will avoid all the intermediate operations and copying, but it seems that due to reference counting issue in js we can't do that.
