### ISSUE TITLE
`addFunction` not exported

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#223]
For some reason `addFunction` is not being exported in our GitHub pages. Just try the `warp` example and it will report

```
ReferenceError: addFunction is not defined
```

Probably related: https://github.com/emscripten-core/emscripten/issues/17456

I guess this also says that we should probably add the js binding to wasm test cases.

**Comment by elalish** [comment]
Good find! Agreed.

**Comment by elalish** [comment]
I just verified this was indeed fixed by #224.
