### ISSUE TITLE
weird cuda problem

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#227]
I'm running the tests with my new work laptop with a RTX3050TI, with Driver Version: 515.48.07, CUDA Version: 11.7, nvcc version cuda_11.6.r11.6/compiler.31057947_0

The tests will fail with
```
C++ exception with description "Error in file: /home/pca006132/code/manifold/src/manifold/src/boolean_result.cpp (185): 'edgePos.size() % 2 == 0' is false: Non-manifold edge! Not an even number of points." thrown in the test body.
[  FAILED  ] Samples.GyroidModule (381 ms)
```

when MANIFOLD_DEBUG is enabled, and memory corruption when it is disabled. I am not sure if this is a problem due to driver version and compiler version mismatch, a problem in my driver installation (I'm using optimus prime offloading), a bug in thrust, or a bug in our code. I will have a look at this after this week to see what's wrong with this.

Also, for the compute capability, should we only compile for `sm_61` or should we include more common architecture? Not sure what is the usual way of doing this.

**Comment by elalish** [comment]
Good question; generally I think the CUDA versions need to be matched exactly, so it could be that. As for sm_61; I put that in a long time ago; ideally I'd like to not specify it at all. It'll probably work with no architecture specified? Just haven't tried lately.

**Comment by pca006132** [comment]
CUDA version issue: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#application-compatibility
> To execute code on devices of specific compute capability, an application must load binary or PTX code that is compatible with this compute capability as described in [Binary Compatibility](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#binary-compatibility) and [PTX Compatibility](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#ptx-compatibility). In particular, to be able to execute code on future architectures with higher compute capability (for which no binary code can be generated yet), an application must load PTX code that will be just-in-time compiled for these devices (see [Just-in-Time Compilation](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#just-in-time-compilation)).

And I have tested that it is fine to specify compute capability 61 and run on RTX3050TI (compute capability 86), so I guess not specifying it is fine.

After debugging, it seems that the problem is in the `BuildInternalBoxes` call in `Collider::UpdateBoxes`, changing that `for_each_n` to run on CPU fixes the issue. I currently have no idea why it is buggy, perhaps you will need to have a look at that.

**Comment by pca006132** [comment]
Also, it seems that we can still have out of memory in the GPU if the out of memory is caused by allocating a large temporary buffer by thrust code, which will use `cudaMalloc` instead of `cudaMallocManaged` which will not perform over-subscription. It seems that the standard way of changing this is to use custom memory allocator with execution policy but I have no idea how to do the pointer tagging stuff.

**Comment by elalish** [comment]
Oh, I was talking about the version mismatch between toolkit 11.7 and nvcc 11.6. I'll be happy to debug that issue if can get a repro, but maybe we should check all the compiler/driver versions first. 

I don't know about the pointer tagging either. What did you run to cause an OOM?

**Comment by pca006132** [comment]
The cuda documentation said that it is fine to run a binary compiled with an older compiler, so it should not be a problem I guess.

OOM: perfTest last case, the backtrace said that it is caused by temporary buffer allocation in thrust.

**Comment by pca006132** [comment]
OK I see, it seems that the `Collider::BuildInternalBoxes` have data race. With the following changes:
```diff
diff --git a/src/collider/src/collider.cpp b/src/collider/src/collider.cpp
index 9fd62f7..d50f7e7 100644
--- a/src/collider/src/collider.cpp
+++ b/src/collider/src/collider.cpp
@@ -219,12 +219,17 @@ struct BuildInternalBoxes {
 
   __host__ __device__ void operator()(int leaf) {
     int node = Leaf2Node(leaf);
+    std::cout << std::endl << "Current Leaf: " << leaf << std::endl;
     do {
       node = nodeParent_[node];
       int internal = Node2Internal(node);
       if (AtomicAdd(counter_[internal], 1) == 0) return;
+      std::cout << node << " = " << internalChildren_[internal].first << " + "
+        << internalChildren_[internal].second << std::endl;
+      std::cout << "Original: " << nodeBBox_[node] << std::endl;
       nodeBBox_[node] = nodeBBox_[internalChildren_[internal].first].Union(
           nodeBBox_[internalChildren_[internal].second]);
+      std::cout << "Updated: " << nodeBBox_[node] << std::endl;
     } while (node != kRoot);
   }
 };
@@ -313,9 +318,10 @@ void Collider::UpdateBoxes(const VecDH<Box>& leafBB) {
   VecDH<int> counter(NumInternal(), 0);
   // kernel over leaves to save internal Boxs
   for_each_n(
-      policy, countAt(0), NumLeaves(),
+      ExecutionPolicy::Seq, countAt(0), NumLeaves(),
       BuildInternalBoxes({nodeBBox_.ptrD(), counter.ptrD(), nodeParent_.ptrD(),
                           internalChildren_.ptrD()}));
+  std::cout << "--------------" << std::endl;
 }
```

`Boolean.EdgeUnion` will print:
```
Current Leaf: 0

Current Leaf: 1
3 = 0 + 2
Original: min: inf, inf, inf, max: -inf, -inf, -inf
Updated: min: 0, 0, 0, max: 1, 1, 1

Current Leaf: 2

Current Leaf: 3
7 = 4 + 6
Original: min: inf, inf, inf, max: -inf, -inf, -inf
Updated: min: 0, 0, 0, max: 1, 1, 1

Current Leaf: 4

Current Leaf: 5
9 = 8 + 10
Original: min: inf, inf, inf, max: -inf, -inf, -inf
Updated: min: 0, 0, 0, max: 1, 1, 1
5 = 7 + 9
Original: min: inf, inf, inf, max: -inf, -inf, -inf
Updated: min: 0, 0, 0, max: 1, 1, 1
11 = 3 + 5
Original: min: inf, inf, inf, max: -inf, -inf, -inf
Updated: min: 0, 0, 0, max: 1, 1, 1
```

So the `internalChildren_[3]` is being written and read for different `n`s (leaf = 1 and leaf = 5), which can be executed in parallel. I guess that can potentially cause problem. Even if the algorithm itself is robust against arbitrary reordering of these operations (not sure about this), the updates are not atomic so there is no guarantee what value will we read.

[CUDA C Programming Guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memory-fence-functions)
>  The CUDA programming model assumes a device with a weakly-ordered memory model, that is the order in which a CUDA thread writes data to shared memory, global memory, page-locked host memory, or the memory of a peer device is not necessarily the order in which the data is observed being written by another CUDA or host thread. It is undefined behavior for two threads to read from or write to the same memory location without synchronization.
> ...
>  The two threads read and write from the same memory locations X and Y simultaneously. Any data-race is undefined behavior, and has no defined semantics. The resulting values for A and B can be anything.

Also, for [C++](https://en.cppreference.com/w/cpp/language/memory_model), non-atomic concurrent read write without synchronization is also undefined.

**Comment by pca006132** [comment]
I tried adding `__threadfence();` before and after the update, and it indeed fixes the problem, but I am still a bit concerned because this is still undefined behavior.

**Comment by elalish** [comment]
Good find! That's pretty old code, so it wouldn't surprise me if I had something wrong. I was implementing https://github.com/elalish/manifold/blob/master/docs/ParallelBVH.pdf - second-to-last page, end of first column. Do you want to take a stab at a proper fix? I'm sure I was taking advantage of writes being always atomic in CUDA. But it sounds like I still missed something.
