### ISSUE TITLE
NPM package is broken

### ISSUE THREAD

**Issue by rafern** [elalish/manifold#265]
The NPM package includes a broken build of the bindings; when trying to call the `Module` function to initialize the library, an error is thrown: `TypeError: Module is not a function`. If I compile my own build, or if I use the build found in the examples website, then the problem is gone.

**Comment by elalish** [comment]
Ah, yes indeed, sorry. So really, this was a recent breaking change to the npm library (turning it into a CommonJS module), so our served version and usage have been updated, but we haven't done a new npm release of it yet. Hence your solution(s) are correct. I guess what we really need are versioned docs; I don't suppose anyone knows of an easy way to set that up with github pages?

**Comment by rafern** [comment]
Ah, I didn't realise that the NPM package was still in an old version, should have looked at it better. As for the Github pages, as far as I know you can only have one deployment at a time. Previous deployments are overridden by newer ones, so you would have to make some system that keeps old versions, with a UI for picking the correct version.

**Comment by elalish** [comment]
Yeah, I was just hoping someone had made a nice open-source Action or something that would take care of it for me, because I don't really want to do it myself. Oh well, we'll get a release out and then it'll make sense again.

**Comment by pca006132** [comment]
It seems that we can create a new subdirectory for every release and automate using Action: https://glebbahmutov.com/blog/versioned-doc-pages/

**Comment by elalish** [comment]
That looks pretty excellent - I suppose we could also have a `pre-release` folder for the very latest. Not sure when I'll get around to it, but if anyone wants to take a stab at it, you're more than welcome!

**Comment by elalish** [comment]
Fixed by #350.
