### ISSUE TITLE
Incomplete mesh relations API

### ISSUE THREAD

**Issue by rafern** [elalish/manifold#282]
There is no transformation matrix in a MeshRelation object, which is needed for correctly restoring vertex normals. The only alternative at the moment is to separately track each transformation, and apply them to the vertex normals at the end.

There is also no flag for knowing whether a triangle needs to be flipped or not (for example, subtracted triangles are flipped, but not if there is a double-subtraction/quadruple-subtraction/etc...). The only alternatives are:
- compare the face normal of a triangle to the original face normal (with transformations applied), and use a dot product to check whether the triangle was flipped
- manually track which triangles need to be flipped by walking through each subtraction separately

**Comment by elalish** [comment]
That's a great point - I hadn't considered normals requiring a transform matrix. Perhaps we should have a private static vector of transforms for each meshID? Then we could have a function like `static glm::mat4x3 Transform(int meshID)`? What do you think, @pca006132? I recall you fixed some of my earlier static usage for thread safety. 

I was thinking you'd tell if it was flipped by the order of the verts, but I see now that'll only work for retained triangles, but not for intersected triangles. The face normal dot product method should actually be safe because I retain the original face normals rather than recalculating them (once you have the transforms from above). Does that seem reasonable, or is additional data necessary?

**Comment by pca006132** [comment]
Do we need a vector of transforms or is 1 transformation matrix for each mesh id sufficient? Not sure if storing them globally would be a good idea, as it would cause "leak" when users keep creating new meshes. I think a better way would be to store them in impl.

One problem is that this will not handle warp appropriately, users using this should be aware of this limitation.

**Comment by rafern** [comment]
I was under the assumption that the library already stored which faces were flipped and that it would be better to reuse those flags, but I can't find any flags like these in the code, so it's definitely more reasonable to use the face normal method.

For the transform matrices, I agree with @pca006132 if the only use is to correct vertex normals/other attributes, but if you want to let users inverse/decompose the matrix for some reason, then it's probably better to store all transformation matrices in a vector because of non-uniform scaling.

**Comment by pca006132** [comment]
I'm thinking if it would make sense to store the transformations in https://github.com/elalish/manifold/blob/master/src/manifold/src/csg_tree.h#L88

Because we are already tracking them in the csg tree.

**Comment by elalish** [comment]
That seems reasonable, but the trouble is that currently `CsgNode` is the only thing with knowledge of the transforms, while `Manifold::Impl` is the only thing with knowledge of the unique meshIDs for each leaf instance. Somehow we need to put those together to make a map of meshID -> transform and make it available somewhere. Would it be better for `CsgOpNode` to increment the meshIDs and pass that mapping to `Manifold::Impl` to update its `MeshRelation` values? Do you have any better ideas?

**Comment by pca006132** [comment]
No better idea for now, I guess we can try this approach.

**Comment by elalish** [comment]
Also, I'd like to take back my suggestion on the geometric approach to inverting normals. Considering that every meshid must be entirely either inverted or not, I think having an `inverted` property as part of this meshid mapping will be a better solution. At least it won't have to be per-triangle.
