### ISSUE TITLE
Two solids with common face does not subtract as expected

### ISSUE THREAD

**Issue by jirihon** [elalish/manifold#285]
I have two manifolds with a common face. By *common* I mean that the vertices of the faces have **exactly** the same positions. I would expect these manifolds will subtract without any artifacts, but there are two extra triangles in the result. See the image below. The contour of the original solid is shown by red lines. One of the extra triangles is dark grey.
![boolean](https://user-images.githubusercontent.com/16903172/201933911-aa8e693d-2fd1-4a0e-b2bf-57cbc192381b.png)

Here is a test to reproduce the issue. The four common vertices are indicated by comments (a, b, c, d).
```cpp
TEST(Boolean, SubtractTouching) {
  Mesh firstMesh;
  firstMesh.vertPos = {
      {-1000, -600, -1000},
      {-1000, -600, 1000},
      {-1000, 600, -1000},
      {-1000, 600, 1000},
      {1000, -600, -1000},
      {1000, -600, 1000},
      {1000, 600, -1000},
      {466.3377380371094, 600, 492.56036376953125},               // a
      {493.0780029296875, 600, 1000},                             // b
      {524.4122314453125, 37.57208251953125, 472.8426208496094},  // c
      {1000, 87.55838012695312, 447.78082275390625},
      {553.8148803710938, 22.12688446044922, 1000},  // d
      {1000, 68.19853210449219, 1000},
      {1000, 600, 462.7948913574219}};
  firstMesh.triVerts = {{0, 1, 2},   {1, 0, 5},   {0, 2, 6},   {6, 2, 3},
                        {2, 1, 3},   {1, 8, 3},   {8, 7, 3},   {5, 0, 4},
                        {4, 0, 6},   {11, 1, 5},  {5, 4, 12},  {12, 4, 10},
                        {12, 11, 5}, {10, 4, 6},  {6, 13, 10}, {6, 7, 13},
                        {8, 1, 11},  {6, 3, 7},   {13, 9, 10}, {9, 11, 12},
                        {11, 9, 7},  {9, 12, 10}, {7, 9, 13},  {8, 11, 7}};

  Mesh secondMesh;
  secondMesh.vertPos = {
      {425.0963439941406, 27.133560180664062, 478.07623291015625},
      {454.20709228515625, 11.84170150756836, 1000},
      {365.9440002441406, 600, 498.159912109375},
      {392.3891906738281, 600, 1000},
      {524.4122314453125, 37.57208251953125, 472.8426208496094},  // c
      {553.8148803710938, 22.12688446044922, 1000},               // d
      {466.3377380371094, 600, 492.56036376953125},               // a
      {493.0780029296875, 600, 1000}};                            // b
  secondMesh.triVerts = {{1, 2, 0}, {2, 6, 0}, {2, 7, 6}, {3, 2, 1},
                         {3, 7, 2}, {0, 4, 1}, {0, 6, 4}, {5, 4, 6},
                         {1, 5, 3}, {1, 4, 5}, {7, 5, 6}, {3, 5, 7}};

  Manifold first(firstMesh);
  Manifold second(secondMesh);

  Manifold result = first - second;

  EXPECT_EQ(result.NumTri(), 30);
}
````

Is it expected behaviour or is it a bug?

**Comment by jirihon** [comment]
The test was wrong initially. It should be fixed now.

**Comment by elalish** [comment]
So, in general coplanar input can give different shard-type surfaces due to rounding error, and we consider them all to be valid results. In the particular case of axis-aligned surfaces, our symbolic perturbation is designed to give better results, but even this can be fooled with tricky geometry. I believe the problem is your surface is not axis-aligned. As with other tools, the easiest way to overcome this is to make your subtracted object a bit longer than what you're subtracting from.

**Comment by elalish** [comment]
Ideally in a case like this I'd like our decimator to identify this edge for collapse and remove the shard that way. Again, it won't work for everything, but probably for quite a few.

**Comment by jirihon** [comment]
Thank you very much for your answer! Indeed, in a lot of cases, even for non-axis-aligned surfaces, the shards are not present. Good job! I'll go for the solution you proposed and will make the subtracted object a bit longer.

However, would you be, please, willing to explain a little bit where the rounding errors occurs during the boolean operations? I'm just curious why it happens even when the touching faces are strictly identical (bit by bit the same vertex positions).

**Comment by jirihon** [comment]
Thank you very much for explanation.
