### ISSUE TITLE
Mesh to manifold may run indefinitely

### ISSUE THREAD

**Issue by chpark1111** [elalish/manifold#302]
Hi! It' me again with an another issue..

When I convert the Mesh to Manifold, it takes too much time. I found that this is coming from the stable_sort_by_key function in  CreateHalfedges function.

It handles meshes with number of vertices lower than 1000 well, but if it gets about 1500, it takes too long time (it does not end).

Is there any way to reduce the time of Mesh to Manifold conversion without lowering the number of vertices? Also, in my experience this time complexity is definitely not O(N). Because vertices of 1500 mesh didn't end until a whole day. Can you explain about this too?

Or where do you think the time bottleneck is happening?

And I tried to enlarge the precision_, but it didn't work..

**Comment by pca006132** [comment]
Are you using this on wasm or native? And if you are using it on native, did you enable multithreading?

I tried generating a sphere with 4096 circular segments, resulting in a mesh with 4194306 vertices, and the conversion of that mesh into manifold object takes about 8945962us (~9s) for native without parallelization and 4978475us (~5s) with TBB backend, so I can't reproduce your issue. Can you provide your mesh?

**Comment by chpark1111** [comment]
Oh my, I'm sorry. I think I used a degenerated mesh.. (Maybe not watertight mesh) I'll close the issue!

**Comment by hrgdavor** [comment]
@chpark1111 silly question, maybe it is mentioned elsewhere.
 
I am wondering if JS side can give manifold mesh to WASM with proper info or it has to go through mesh->manifold converter ?

I am looking to play a bit with manifold in near future, so I am curious about such details.

**Comment by elalish** [comment]
@chpark1111 I'd still like to see you mesh! It sounds like you hit an infinite loop, probably in the edge collapse step. This would be a great test case to look at.

@hrgdavor I'm not quite sure what your question is. What is "proper info"? I would consider `Manifold(mesh)` to be both giving a manifold mesh and a mesh->manifold converter - not sure what distinction you're trying to draw.

**Comment by chpark1111** [comment]
@elalish I think that's the exact answer I wanted to get!! Thanks! :)
I'll provide you one here. If this contains too much vertices to look at, I can give you small number of meshes that gets an infinite loop.

And just for a suggestion, can't we detect does infinite loop cases and make the program output an error?
[mesh.txt](https://github.com/elalish/manifold/files/10320445/mesh.txt)

**Comment by pca006132** [comment]
Yeah we should detect that.

**Comment by hrgdavor** [comment]
@elalish Iam seing this
>I tried generating a sphere with 4096 circular segments, resulting in a mesh with 4194306 vertices, and the conversion of that mesh into manifold object takes about 8945962us (~9s) for native without parallelization and 4978475us (~5s) with TBB backend,

So it sounds to me that when I provide a mesh to manifold library, it will for a large mesh then take time to create a manifold object. I am wondering if I can produce a manifold object in JS and skip the mentioned  mesh->manifold conversion step.

**Comment by pca006132** [comment]
@hrgdavor If you only do csg with basic primitives (spheres, cylinders, cubes, etc.) or sdf, you don't have to do the conversion. The conversion is only needed when you want to import an existing mesh.

**Comment by hrgdavor** [comment]
I like producing procedural meshes, so knowing the format and being able to produce and pass a manifold to WASM is interesting to me.

**Comment by elalish** [comment]
@hrgdavor We're using "manifold" to mean two different things here. A manifold is a water-tight mesh, while a `Manifold` is this library's internal data structures for operating on such. The conversion takes time because it's populating those data structures and doing various checks and calculations, like collapsing degenerate triangles if there are any. It's very fast compared to any Boolean operations you might do on the result (with the exception of this bug).

For procedural meshes, I'd recommend you look at our `Warp` function. I find it's often much quicker and easier to start with a primitive, possibly `Refine` it, then `Warp` to whatever shape I need. That also saves you from needing a bunch of I/O.

**Comment by hrgdavor** [comment]
Ok, will there be an option to pass a water tight mesh that can skip some checks for speed ?

Anyway, when the time comes, we will see if some thigs I can produce with Warp, Refine, LevelSet, and if custom meshes will be fast enough to import with checks so this "skip checks" shortcut is not even needed.

**Comment by pca006132** [comment]
Wondering if this may be related to #331

**Comment by chpark1111** [comment]
@pca006132 Thanks for the fixes!! I check and report the issue when I have.

**Comment by chpark1111** [comment]
@pca006132 I think the issue is fixed! I'll close them. Thanks!
