### ISSUE TITLE
Near-overlapping planes can produce non-watertight results

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#304]
Example:

```python
import trimesh
from pymanifold import Manifold

def export(model, filename, extension='obj'):
    mesh = model.to_mesh()
    meshOut = trimesh.Trimesh(
        vertices=mesh.vert_pos, faces=mesh.tri_verts)
    trimesh.exchange.export.export_mesh(meshOut, f'{filename}.{extension}', extension)

def warpFun(v):
    v = list(v)
    if all(abs(x - 1) < 0.01 for x in v):
        v[0] -= 0.5
    return v

cube1 = Manifold.cube()
cube2 = cube1.translate(1, 0, 0)
cube1 = cube1.warp(warpFun).rotate(10, 0, 0)
cube2 = cube2.warp(warpFun).rotate(10, 0, 0)

export(cube1 + cube2, 'test')
```

The rotation is used to introduce slight error and keep the overlapping faces. meshlab reports non-manifold edges:
![image](https://user-images.githubusercontent.com/12198657/210125192-794261c2-7f22-4f44-89bd-cd2bb3bb18cc.png)

cura mesh-tools also report the mesh being not watertight.

I'm wondering whether we can remove the faces when the distance between them is less than tolerance, although real-world situation might be a lot more complicated (partially overlap, etc.)

**Comment by elalish** [comment]
Okay, so the first question is have we checked that the exporter hasn't changed the mesh? Some of them try to "helpfully" deduplicate vertices, which breaks everything. Can we verify that the output is actually non-manifold within our own library? I'll be surprised if it is, but that would definitely be a serious bug. If not, then we can look at what the exporter does to the mesh and see if there's a way to convince it to stop.

**Comment by pca006132** [comment]
Oh I forgot to check this because I thought obj files can preserve manifoldness (and for another model it does, while stl doesn't). I've checked the documentation and it doesn't seem like this behavior is configurable, which is quite annoying... Meshlab doesn't support 3MF format so I am not sure if it works as intended.

**Comment by pca006132** [comment]
Maybe we should close this as there is not much that we can do here? I wonder if assimp can preserve manifoldness etc. And we should probably compile assimp with wasm so we can add 3MF output to our web editor.

**Comment by elalish** [comment]
I don't think OBJ is the problem, but rather particular exporters/importers which often do extra processing. Honestly, we should probably start keeping a list of libraries that are and are not problematic for preserving our meshes topologically in a round-trip.

**Comment by danielyan86129** [comment]
@pca006132 it might be this
```
process (bool) – if True, Nan and Inf values will be removed immediately and vertices will be merged
```
try setting it to `False` in `Trimesh()`. Curious to learn what comes out.

Also, IIUC are you simply building 2 manifold cubes and save them into a file, the file contains two mesh manifold components? Then it should have nothing to do with "Near-overlapping planes" right?

**Comment by pca006132** [comment]
Thanks! Setting process to false will prevent obj files from merging vertices, but stl files will still merge them.

> Also, IIUC are you simply building 2 manifold cubes and save them into a file, the file contains two mesh manifold components? Then it should have nothing to do with "Near-overlapping planes" right?

No, what I am doing is building two manifold cubes, modify one of their vertices and then merge them together. The merged faces are still present in the result. The "near-overlapping planes" is not a good terminology but I don't know much about graphics/geometry so I am not sure what should be the term.

And in general there can be some annoying small gaps in the result, although @elalish said it is expected behavior:

> Okay, so there's no triangulation error and there's no manifoldness error, just a marginal situation where two adjacent cubes don't get joined sometimes? I don't particularly consider that a bug. We do some best effort to make common situations work better, but in general we look at vertex positions as having fundamental uncertainty from rounding error and so any ε-perturbation is a valid result. I'm tempted to call this expected behavior.

**Comment by pca006132** [comment]
After thinking more about it, it seems that my example here is wrong and the bug is just the same as the one in #297, so I'm closing this for now.
