### ISSUE TITLE
Failure of boolean subtraction

### ISSUE THREAD

**Issue by chpark1111** [elalish/manifold#305]
Ultimately, I want to boolean subtraction (part - mesh) and calculate the volume with given below 2 meshes. But it gives me a segmentation fault when I calculate the volume or turn the subtracted manifold into a mesh. 

Can you guys check whats the error?

 I'll providethe part and mesh as txt file under
[part.txt](https://github.com/elalish/manifold/files/10329039/part.txt)
[mesh.txt](https://github.com/elalish/manifold/files/10329040/mesh.txt)

**Comment by chpark1111** [comment]
Also with the above mesh, when I turn the mesh into manifold and turn it back to mesh, I get a open mesh! I think that has something to do with the failure above. 
![스크린샷 2023-01-02 오후 1 00 04](https://user-images.githubusercontent.com/50504528/210194235-b7d41b72-6622-4256-90ba-39803d630ed3.png)

It means that manifold to mesh creates a open mesh!

**Comment by elalish** [comment]
So first, can you be very specific about what your workflow is and what apps/libraries are being used to test the results? Keep in mind that most 3D file importers and exporters change the mesh, often in an attempt to make something manifold that isn't, but just as often doing the opposite. 

The seg fault sounds like a definite bug. Any chance you can turn it into a simple-ish test akin to these? https://github.com/elalish/manifold/blob/master/test/mesh_test.cpp#L639

**Comment by chpark1111** [comment]
I checked that it makes a non-watertight mesh with the below codes!
I just do nothing but loading it to pymanifold mesh and manifold and just turn them back to mesh. But it gives us a non-watertight mesh.

![image](https://user-images.githubusercontent.com/50504528/210203448-effbe8c5-039a-4bd2-b95d-a2e81157cf71.png)

Above prints out True, False.

And about the seg-fault, I'll try to make the tests in c++ but it will be definitely hard to reproduce the results without loading the above meshes. Do you mean "simple-ish " as reproducing the seg-fault without using those meshes?

**Comment by elalish** [comment]
Thanks, so you're using `Trimesh` to import our mesh and to check watertightness. That's not trivial, as we don't know what the `Trimesh` importer does with the mesh (does it try to merge duplicate verts?) and we don't know how it checks watertightness (ours is one of many definitions of manifoldness). See a similar discussion in https://github.com/elalish/manifold/issues/304#issuecomment-1368506302

Anyway, it would be great to understand the details of other libraries like `Trimesh` so we can document what is expected, how to properly interface with them, and even file bugs/feature requests. It'll help a lot if we can manage to reduce the test mesh down to a small number of triangles so we can find differences in the round-trip by reading the vectors in std out.

**Comment by chpark1111** [comment]
Oh sorry about the missing details.. I didn't know that it's not a trivial thing. I'll try to explore little deeper about the current problem and tell you what I've found.
The water-tightness is just one thing I'm suspecting but like you said seg-fault is a problem. I'll first track where the segfault is happenning!

**Comment by pca006132** [comment]
Just build with debug information enabled and give the gdb backtrace should give us a rough idea about what is causing the problem.

```
cmake -DCMAKE_BUILD_TYPE=Release -DMANIFOLD_PAR="NONE" -DMANIFOLD_DEBUG=1 -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -g"-DMANIFOLD_PYBIND=on ..
```

**Comment by danielyan86129** [comment]
Curious @elalish there must be routines that check if a mesh is manifold and watertight right? 

@pca006132 can you comment out `fix_normals()` (as it might be doing something), and try to use those routines and print the status after you call `.from_mesh()` and `.to_mesh()`? Also, when you call `trimesh.Trimesh()` set this to `False`:
```
process : bool
          if True, Nan and Inf values will be removed
          immediately and vertices will be merged
```

**Comment by chpark1111** [comment]
Oh sorry about the late response. I made the tetrahedral meshes with Tetwild libary which seems to generate degenerated tetrahedral meshes. I tried it with using process=False in tetmesh and given just used the manifold's meshIO. I think this is just the problem of the mesh not the library. I'll close the issue.. Sorry for bothering you guys.

**Comment by elalish** [comment]
@chpark1111 Not a bother! Thanks, and we learned something useful from @danielyan86129 about `process: false` in `pymanifold`, which we should probably document somewhere.
