### ISSUE TITLE
Error collision manifold::Manifold::Error::NO_ERROR using MinGW-Windows

### ISSUE THREAD

**Issue by jespa007** [elalish/manifold#318]
Hi there,

I'm trying to use manifold in my environment using mingw gcc in windows. I had some issues,

Because in the tool I include `<windows.h>` then `manifold::Manifold::Error::NO_ERROR` defined in `manifold.h` collides with `NO_ERROR` defined in `winerror.h`. The compiler throws an error that `NO_ERROR` is already defined,

![image](https://user-images.githubusercontent.com/7852409/218091247-38133fdd-418c-4953-84ec-646d66b6e22d.png)

The solution could be change the contents of `Error` enumeration by the following,

```
  enum class ManifoldError {
    MANIFOLD_ERROR_NO_ERROR,
    MANIFOLD_ERROR_NON_FINITE_VERTEX,
    MANIFOLD_ERROR_NOT_MANIFOLD,
    MANIFOLD_ERROR_VERTEX_INDEX_OUT_OF_BOUNDS,
    MANIFOLD_ERROR_PROPERTIES_WRONG_LENGTH,
    MANIFOLD_ERROR_MISSING_POSITION_PROPERTIES,
    MANIFOLD_ERROR_MERGE_VECTORS_DIFFERENT_LENGTHS,
    MANIFOLD_ERROR_MERGE_INDEX_OUT_OF_BOUNDS,
  };
```

Note: I'm using x86_64-12.2.0-release-posix-seh-rt_v10-rev0 toolchain, and `winerror.h` it can be found in the `x86_64-w64-mingw32\include`

Thanks

**Comment by elalish** [comment]
That's bizarre - what's the point of namespacing if the names still collide? I must be missing something; is there a C++ best practices doc that talks about this somewhere?

**Comment by pca006132** [comment]
Well the macro is just find and replace, so namespace is useless against it. Sadly there is nothing we can do other than avoiding this name.

**Comment by elalish** [comment]
Oh, I see now - wow, excellent macro, M$! :roll_eyes:  How about `NO_ERROR` => `NO_ERRORS`?

**Comment by pca006132** [comment]
That header file probably existed long ago, and changing the macro may break other code so I see why they keep this :).

`NO_ERRORS` sounds good to me, but we should probably also make sure that people compiling on MinGW will get an error if they accidentally typed `NO_ERROR`.

**Comment by elalish** [comment]
Any thoughts on how to do that? Or would it be better to just choose a more different name?

**Comment by pca006132** [comment]
It should cause an error, but we need to check it. Can @jespa007 help us check this?

**Comment by jespa007** [comment]
@elalish , not only M$, many projects can include headers from C projects so it could collide with other cases with short name macros.


> It should cause an error, but we need to check it. Can @jespa007 help us check this?

Yes of course I can help you! :-) As I suggested I could change enum `Error` to other one more explicit like this,

```
  enum class ManifoldError {
    MANIFOLD_ERROR_NO_ERROR,
    MANIFOLD_ERROR_NON_FINITE_VERTEX,
    MANIFOLD_ERROR_NOT_MANIFOLD,
    MANIFOLD_ERROR_VERTEX_INDEX_OUT_OF_BOUNDS,
    MANIFOLD_ERROR_PROPERTIES_WRONG_LENGTH,
    MANIFOLD_ERROR_MISSING_POSITION_PROPERTIES,
    MANIFOLD_ERROR_MERGE_VECTORS_DIFFERENT_LENGTHS,
    MANIFOLD_ERROR_MERGE_INDEX_OUT_OF_BOUNDS,
  };
```

Of course this change can broke code changes for the users that currently uses Manifold, but we can explain the migration needed. I the other hand it will be more compatible in the future. @pca006132 , @elalish decide what is the best and I could help to try make the changes for this issue, do the corresponent tests and finally make a PR.

**Comment by geoffder** [comment]
Or, as it is an C++ enum, it could be switched to PascalCase instead of screaming snake. The `MANIFOLD_` prefix would be more appropriate for the manifoldc binding enums.

**Comment by geoffder** [comment]
Not at all, I specifically mentioned PascalCase. I'm suggesting `NoError` (... `NotManifold`), which would be used normally as `Error::NoError`. To repeat myself, the naming you suggest is more appropriate for a C enum (*not* a C++ enum class), which may be worth doing in the C bindings, but is extremely cumbersome and unergonomic in the C++ which with name spacing should never have to bear that kind of burden.

**Comment by jespa007** [comment]
> Not at all, I specifically mentioned PascalCase. I'm suggesting `NoError` (... `NotManifold`), which would be used normally as `Error::NoError`. To repeat myself, the naming you suggest is more appropriate for a C enum (_not_ a C++ enum class), which may be worth doing in the C bindings, but is extremely cumbersome and unergonomic in the C++ which with name spacing should never have to bear that kind of burden.

Sorry I misunderstood. So you are suggesting this,

```
 enum class Error {
    NoError,
    NonFiniteVertex,
    NotManifold,
    VertexIndexOutOfBounds,
    PropertiesWrongLength,
    MissingPositionProperties,
    MergeVectorsDifferentLengths,
    MergeIndexOutOfBounds,
  };
```

**Comment by elalish** [comment]
Good call @geoffder, I somehow missed this in the [Google style guide](https://google.github.io/styleguide/cppguide.html#Enumerator_Names).
