### ISSUE TITLE
Integrate glMatrix into manifold.js

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#324]
It's pretty clear if you're using `Manifold`, you're also doing matrix operations on 2, 3, and 4 -element vectors. Currently we have our own types for these without any useful functions, just fixed-size arrays. I'm thinking it would be better to integrate a mature package like [`glMatrix`](https://www.npmjs.com/package/gl-matrix) and use their types in our API instead, to avoid a bunch of manual conversion. It's an extra 15kb (minified and gzipped) compared to >200kb for our library currently, so the size difference seems a worthwhile trade.

What does everyone think of this? (particularly @pca006132).

**Comment by elalish** [comment]
Of course our C++ library already includes GLM, which is equivalent, but I feel like making WASM bindings for their myriad functions doesn't sound like a lot of fun.

**Comment by elalish** [comment]
So, looking at the glMatrix API more, I think this is even simpler, because their whole API is free functions, rather than classes. This means I *think* it will work right now with manifold and we don't even have to bundle them together, which simplifies distribution considerably. I think this will be a better approach to #238.

**Comment by pca006132** [comment]
Interesting, I somehow missed this yesterday. This looks pretty nice.

There is a [babel plugin](https://github.com/akira-cn/babel-plugin-transform-gl-matrix) which looks pretty nice, wondering if we can somehow run this in the browser...

**Comment by pca006132** [comment]
https://babeljs.io/docs/en/babel-standalone

Seems possible. We can probably use this to add operator overloading for manifold boolean operations as well.

**Comment by elalish** [comment]
Oh yes, that's a nice API cleanup they did! I'd still like to maintain separation between our libraries if possible. I think a great way to test this would be to include it in our editor's worker and see if we can get it to integrate nicely there alongside our WASM (and get the torus knot example to use it). Then we'll have easy instructions for others to use, but there won't be any duplication in their code base if they already depend on it.

**Comment by pca006132** [comment]
Although to be honest I have no idea how the babel plugin works without a type system... I have a quick look at the code, it seems that it is trying to get the type information by checking the definition of the variable, but this will not work if the code is slightly more complicated, e.g. with lambdas or arrays.

One workaround would be to replace every binary operator with a call to a global binary operator handler and perform dynamic dispatch, but it will have some performance problem if they do a lot of calculation, plus I have no idea if typescript can handle operator overloading...

**Comment by pca006132** [comment]
Yeah I think we don't need much changes to the wasm API, we just have to expose more helpers to the editor. We can keep our wasm API as simple as possible.

**Comment by elalish** [comment]
Sounds good. Let's try to just get vanilla glMatrix working first and worry about syntactic sugar later.

**Comment by pca006132** [comment]
I can try to do this in the weekend.
