### ISSUE TITLE
CI hang

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#326]
Just to keep track of the weird problem. It seems that the OMP backend with Ubuntu will somehow cause the CI to timeout. Interestingly the nix builds never timeout (and they seems to run faster as well, perhaps different compiler and runner). 

And I don't quite understand why it is taking so much time. For example, for [this run](https://github.com/elalish/manifold/actions/runs/4180714794/jobs/7241962894) the test task run for 21m 16s according to GitHub Action, but the log said it run for 29162 ms in total, which is no where near 21m, and it was cancelled after the task is finished...?

It would be nice if someone can find a way to reproduce or explain this issue, or maybe we should just disable that job for now. We already have OMP covered in nix tests anyway.

**Comment by elalish** [comment]
Agreed, this has been bothering me too. I've seen it with the TBB runs as well, but less often. I'd be fine with removing the jobs. I'd also guess that OMP/TBB are somewhat lower priority for bug fixes from Thrust...

**Comment by elalish** [comment]
Not yet, but I also haven't been compiling to OMP. I should give it a shot.

**Comment by elalish** [comment]
Fixed by #330 and #331
