### ISSUE TITLE
Making the library faster

### ISSUE THREAD

**Issue by chpark1111** [elalish/manifold#337]
Is there a way to accelerate this library? It doesn't matter if the precision of volume or other meshes get slightly lower. Is there something I can control like the precision and get speed up? I can modify in a code level for only my use.

I already tried the parallelization but didn't help. (It more likely made it slower) Because what I need is rapid small calculations not speeding up one large calculation.

**Comment by pca006132** [comment]
Ah, we already tried to accelerate this as much as we can, so there is probably no low hanging fruits. Precision doesn't really affect the performance except for SDF. We can probably try to use the SIMD sort to replace some of the sorting calls, but even if that can help, it will only affect large meshes.

If you want to, you can tell us your use cases, ideally with a demo code, so we can see where is the bottleneck.

**Comment by chpark1111** [comment]
Oh what I exactly need is to making the triangularization faster. (The part converting manifold to mesh) I think the triangularization will be accelerated if we can control the ideal length of the triangle meshes. How can I control this? I think the SDF part is what I need I guess?

**Comment by pca006132** [comment]
Oh triangulation... It is known that the triangulation algorithm is not fast and does not benefit much from parallelization. I don't have much idea about this. What I know is that the algorithm is different from other commonly used triangulation algorithms, will produce skinny triangles, but is more robust when encountering self intersection or something. @elalish What do you think?

**Comment by pca006132** [comment]
Thinking about it, if your models don't have much overlap, maybe you can try to do intersection instead of union/subtraction for volume calculation, as the mesh may be smaller with intersection.

**Comment by chpark1111** [comment]
Thanks for the thoughts! But what I need to calculate is volume of boolean union of many meshes... But maybe those kind of optimizations might work in such setup!
