### ISSUE TITLE
Publish python library to pypi

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#362]
This is blocked by #361

**Comment by pca006132** [comment]
I am trying to build python wheels in https://github.com/pca006132/manifold/tree/python-wheel, but now is stuck with windows build... There are two problems:

1. Somehow cmake cannot find the tbb library installed via pip (tbb-devel) or nuget. I am now disabling tbb for windows, but hopefully we can get this sorted out later.
2. CMake does not build the `ALL_TARGET` automatically, I am now trying to copy args from our normal CI commands.

**Comment by elalish** [comment]
Thanks for looking into this! I just found what might be a good [template](https://github.com/scikit-build/scikit-build-sample-projects/blob/master/projects/hello-cmake-package/README.md) to follow. I also found an interesting wheels CI [example](https://github.com/pybind/cmake_example/blob/master/.github/workflows/wheels.yml). TBB can wait, no problem. I'll defer to your superior Python and build setup skills.

**Comment by pca006132** [comment]
Oh and there are other issues as well:

1. manylinux2014 uses gcc 10, which ships with pstl 10, and will cause issues when using newer tbb versions (>= 2021), the one provided by the system is too old (2014), and cmake/pkg-config cannot find the tbb installed from the intel provided script.
2. somehow our extrude example will cause python 3.7 importer error (syntax error), I have no idea why, so I am limiting it to Python >= 3.8.
3. auditwheel which is used for statically linking the libraries (libtbb.so for example) somehow is unable to find tbb installed from pip, and can only install from the system.

I am familiar with building for linux, but not so much for MacOS and Windows... I wonder if there are others that are familiar with Python packaging that can help.

**Comment by elalish** [comment]
Do you want to open a PR with your WIP? I think this is pretty much the last thing to take care of for our release (aside from triangulator bugs I'm still working on).

**Comment by pca006132** [comment]
OK now the remaining thing is to push the wheels to PyPI.

**Comment by pca006132** [comment]
I think we should push to TestPyPi first. I think automated release should not be hard, we already have the wheels anyway.

**Comment by Eric-Vin** [comment]
Super excited to try this out! Is there a rough timeline of when the wheels will be pushed to PyPi?

**Comment by pca006132** [comment]
I think we will do that after the triangulator PR is merged.

**Comment by pca006132** [comment]
@elalish maybe you can setup a python package first?

**Comment by pca006132** [comment]
alternatively I can do it when I get back from a conference (~4 days). the conference is fun but I am pretty tired at the end of the day to do any useful work :P

**Comment by elalish** [comment]
Yeah, I totally understand. I'm a bit exhausted from that triangulator overhaul too. I want to take a look at #579 first, but probably not tonight.
