### ISSUE TITLE
.transform not available in wasm

### ISSUE THREAD

**Issue by frading** [elalish/manifold#373]
Using the npm module, I get `.transform is not a function`.

And double checking in your online editor https://manifoldcad.org/, while I can see that `.translate`, `.rotate` and `.scale` work perfectly fine,  I also get an error when trying to use `.transform`. Even though it is mentioned in the [types](https://github.com/elalish/manifold/blob/master/bindings/wasm/manifold-encapsulated-types.d.ts#L206) 

edit:
to clarify what I tried in the editor, the following works:

```
const box = cube([100, 100, 100], true);
const ball = sphere(60, 100).translate([50,0,0]);
const result = box.subtract(ball);
```

But this generates an error:

```
const box = cube([100, 100, 100], true);
const ball = sphere(60, 100).transform([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]);
const result = box.subtract(ball);
```

**Comment by pca006132** [comment]
Oh we accidentally deleted it in https://github.com/elalish/manifold/pull/332/files#diff-734a58f3eafd25b8d9cee3f50f47ec8032b8146333036054da86c44df8620ba1

**Comment by frading** [comment]
ah good, thanks a lot for checking quickly, and glad I wasn't going crazy.
