### ISSUE TITLE
More sanity check

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#379]
We don't do much validation for function inputs, and some inputs can cause a crash, such as cylinder with zero/negative radius. We should probably add this so downstream users will not get a segfault.

**Comment by geoffder** [comment]
Should there be new cases added to `Status` to cover these kinds of invalid input? Perhaps one like `InvalidConstruction` on an empty `Manifold` would be appropriate for a handful of them.

**Comment by pca006132** [comment]
Yeah we should probably do that. And ideally we should get this done before the upcoming release.

**Comment by elalish** [comment]
Yes, that sounds like a good solution. Want to give it a shot, @geoffder?

**Comment by geoffder** [comment]
@elalish Sure, I can try to put some work into that soon.
