### ISSUE TITLE
Illegal memory access for SparseIndices.Sort with TBB backend

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#391]
The sort function will perform illegal memory access when dealing with large meshes and with TBB backend enabled. This can be checked by enabling the address sanitizer.

Build instruction:
```
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DMANIFOLD_PAR="TBB" -DCMAKE_CXX_FLAGS="-g -fsanitize=address" -DMANIFOLD_USE_CUDA=off -DMANIFOLD_EXPORT=on ..
```

Run the following test:
```c++
TEST(Boolean, LargeSpheres) {
  auto a = Manifold::Sphere(100, 2000);
  auto b = a + a.Translate({30, 0, 0});
  a.GetMesh();
}
```

**Comment by pca006132** [comment]
Thinking about this, maybe we should use single threaded sort for now until the root cause of this is fixed.

**Comment by elalish** [comment]
Perhaps so; any luck with the Thrust-only repro? That sounds like a bug Nvidia should take pretty seriously.

**Comment by pca006132** [comment]
Ah, it seems that the issue disappeared after updating thrust. Forgot to rerun the test after thrust update. Closing for now.
