### ISSUE TITLE
Manifold - PerfTest (Debug) : List Iterators Incompatible error (Windows)

### ISSUE THREAD

**Issue by yetigit** [elalish/manifold#395]
## This will happen running PerfTest in debug on windows.

![perfTest_mblGMevvG0](https://user-images.githubusercontent.com/7016200/229350712-32ec2a9e-3911-4e7a-8a71-d3220f91f230.png)

![devenv_EccVui8L7U](https://user-images.githubusercontent.com/7016200/229350725-c5e421dd-445c-4b27-924b-a1726d5af168.png)

![devenv_Nu7DlJ6hWs](https://user-images.githubusercontent.com/7016200/229350749-20cd8ac2-769e-4994-930e-66e30ca07667.png)

![devenv_OZdHjgqVtd](https://user-images.githubusercontent.com/7016200/229350751-827c9d15-129b-42be-a1b2-8fbba6741699.png)

see polygon.cpp line 186
see polygon.cpp line 950

--------------------------------------

Apparently the west/east iterator from `vert`  is not coming from the same list it tries to compare to. 

https://stackoverflow.com/questions/31217529/c-list-iterators-incompatible

on Release the STL assert won't happen.

**Comment by elalish** [comment]
Okay, so it sounds like it was about to throw "No active pairs", but MSVC caught the issue slightly earlier? This means the triangulation failed, though that's not entirely a problem - hence why it works in Release mode, where the code gracefully falls back to a simpler triangulation. If you enable `verbose` mode it should spit out the problem polygon to the command line so you can easily write a new polygon TEST case. But maybe plot it first - if it actually has some small self-intersections then this is expected behavior.

**Comment by pca006132** [comment]
I think this can be considered undefined behavior? Although it will only happen when triangulation failed, we should still try to avoid this. And this should not be hard to fix I guess.

**Comment by elalish** [comment]
I'm not quite sure what you mean, but if you know a quick fix, I'd love to see it.

**Comment by pca006132** [comment]
Not sure if this is sufficient:
```diff
diff --git a/src/polygon/src/polygon.cpp b/src/polygon/src/polygon.cpp
index acd4006..2980926 100644
--- a/src/polygon/src/polygon.cpp
+++ b/src/polygon/src/polygon.cpp
@@ -364,6 +364,7 @@ class Monotones {
     VertItr vWest, vEast, vMerge;
     PairItr nextPair;
     bool westCertain, eastCertain, startCertain;
+    bool isRemoved = false;
 
     int WestOf(VertItr vert, float precision) const {
       int westOf = CCW(vEast->right->pos, vEast->pos, vert->pos, precision);
@@ -566,6 +567,7 @@ class Monotones {
    */
   void RemovePair(PairItr pair) {
     pair->nextPair = std::next(pair);
+    pair->isRemoved = true;
     inactivePairs_.splice(inactivePairs_.end(), activePairs_, pair);
   }
 
@@ -947,7 +949,7 @@ class Monotones {
       OVERLAP_ASSERT(type != Skip, "Skip should not happen on reverse sweep!");
 
       PairItr westPair = GetPair(vert, type);
-      OVERLAP_ASSERT(westPair != activePairs_.end(), "No active pair!");
+      OVERLAP_ASSERT(westPair->isRemoved || westPair != activePairs_.end(), "No active pair!");
 
       switch (type) {
         case Merge: {
@@ -972,6 +974,7 @@ class Monotones {
           // begin and end are swapped.
           PairItr eastPair = westPair;
           westPair = eastPair->nextPair;
+          eastPair->isRemoved = false;
           activePairs_.splice(westPair == activePairs_.end()
                                   ? activePairs_.begin()
                                   : std::next(westPair),
```

I think the problem is that the `westPair` can be in `inactivePairs`, causing the assertion error on Windows. This only addresses that issue.

**Comment by yetigit** [comment]
> Okay, so it sounds like it was about to throw "No active pairs", but MSVC caught the issue slightly earlier? This means the triangulation failed, though that's not entirely a problem - hence why it works in Release mode, where the code gracefully falls back to a simpler triangulation. If you enable `verbose` mode it should spit out the problem polygon to the command line so you can easily write a new polygon TEST case. But maybe plot it first - if it actually has some small self-intersections then this is expected behavior.

@elalish  this is where the verbose print stops (took the liberty to print the sweepfunc and polygonid): 

```
mesh_idx = 77
sweepfwd
polygonid = 0
Start
active edges:
certain edge West: S = 77, N = 258
certain edge East: S = 77, N = 260
mesh_idx = 260
sweepfwd
polygonid = 1
EastSide
active edges:
certain edge West: S = 77, N = 258
certain edge East: S = 260, N = 313
mesh_idx = 313
sweepfwd
polygonid = 2
EastSide
active edges:
certain edge West: S = 77, N = 258
certain edge East: S = 313, N = 312
mesh_idx = 312
sweepfwd
polygonid = 3
EastSide
active edges:
certain edge West: S = 77, N = 258
certain edge East: S = 312, N = 258
mesh_idx = 258
sweepfwd
polygonid = 4
End
active edges:
mesh_idx = 258
sweepback
Start

```

I will admit I'm not familiar with this data so I don't know what I am seeing 😅 

now here is the polygon (5 vertices) in question : 

![maya_mnJilt70Ep](https://user-images.githubusercontent.com/7016200/229470664-b642d8d1-6be1-41d2-9d14-ef26acc9d45b.png)

no self intersection

**Comment by yetigit** [comment]
@pca006132  your changes seem to work !

**Comment by pca006132** [comment]
@elalish what do you think about the fix? I wonder if this indicates some invariant being broken in the triangulator. If no, maybe I can open a PR?

**Comment by elalish** [comment]
Yes, thank you, I just want to make sure I understand what's happening inside the triangulator first. I'll try to get to that today.

**Comment by elalish** [comment]
Okay, I can't repro this since I'm not on Windows. @pca006132 Yes, please make a PR. However, can you verify that without your fix this polygon is being processed as "overlapped"? If so, you should be able to turn on verbose mode and have it spit out the polygon on the command line so you can copy it into a Polygon test. That should allow me to repro what's going on. I just want to double-check there isn't some side-effect we're missing.

**Comment by pca006132** [comment]
It seems that polygon is not being processed as overlapped. I made the following changes:
```diff
diff --git a/extras/perf_test.cpp b/extras/perf_test.cpp
index 082f3b4..7c3ae45 100644
--- a/extras/perf_test.cpp
+++ b/extras/perf_test.cpp
@@ -20,6 +20,8 @@
 using namespace manifold;
 
 int main(int argc, char **argv) {
+  ManifoldParams().processOverlaps = false;
+  ManifoldParams().verbose = true;
   for (int i = 0; i < 8; ++i) {
     Manifold sphere = Manifold::Sphere(1, (8 << i) * 4);
     Manifold sphere2 = sphere.Translate(glm::vec3(0.5));
```

and there is no polygon output.

For reproducing the problem, you don't have to be on Windows. Just apply the following patch:
```diff
diff --git a/src/polygon/src/polygon.cpp b/src/polygon/src/polygon.cpp
index acd4006..425d5da 100644
--- a/src/polygon/src/polygon.cpp
+++ b/src/polygon/src/polygon.cpp
@@ -364,6 +364,7 @@ class Monotones {
     VertItr vWest, vEast, vMerge;
     PairItr nextPair;
     bool westCertain, eastCertain, startCertain;
+    bool isRemoved = false;
 
     int WestOf(VertItr vert, float precision) const {
       int westOf = CCW(vEast->right->pos, vEast->pos, vert->pos, precision);
@@ -566,6 +567,7 @@ class Monotones {
    */
   void RemovePair(PairItr pair) {
     pair->nextPair = std::next(pair);
+    pair->isRemoved = true;
     inactivePairs_.splice(inactivePairs_.end(), activePairs_, pair);
   }
 
@@ -947,7 +949,7 @@ class Monotones {
       OVERLAP_ASSERT(type != Skip, "Skip should not happen on reverse sweep!");
 
       PairItr westPair = GetPair(vert, type);
-      OVERLAP_ASSERT(westPair != activePairs_.end(), "No active pair!");
+      OVERLAP_ASSERT(!westPair->isRemoved && westPair != activePairs_.end(), "No active pair!");
 
       switch (type) {
         case Merge: {
@@ -972,6 +974,7 @@ class Monotones {
           // begin and end are swapped.
           PairItr eastPair = westPair;
           westPair = eastPair->nextPair;
+          eastPair->isRemoved = false;
           activePairs_.splice(westPair == activePairs_.end()
                                   ? activePairs_.begin()
                                   : std::next(westPair),
```

This patch just assert that the `westPair` should not be in `inactivePairs`. And in fact there are many tests that failed after this patch, for example:
```
[ RUN      ] Polygon.SimpleHole
-----------------------------------
Triangulation failed! Precision = -1
Error in file: /home/pca006132/code/manifold/src/polygon/src/polygon.cpp (39): 'condition' is false: No active pair!
polys.push_back({
    {glm::vec2(0, -2), 0},  //
    {glm::vec2(2, 2), 1},  //
    {glm::vec2(0, 4), 2},  //
    {glm::vec2(-3, 3), 3},  //
});
polys.push_back({
    {glm::vec2(0, -1), 4},  //
    {glm::vec2(-1, 1), 5},  //
    {glm::vec2(1, 1), 6},  //
});
array([
  [0, -2],
  [2, 2],
  [0, 4],
  [-3, 3],
])
array([
  [0, -1],
  [-1, 1],
  [1, 1],
])
```

**Comment by elalish** [comment]
Perfect, thanks!
