### ISSUE TITLE
GetMesh failing with processor intel i9 but not with i7

### ISSUE THREAD

**Issue by edumarzolla** [elalish/manifold#411]
I am testing manifold with subtracting around 10.000 cylinders from a bigger cylinder.
I have compiled it with nvidia toolkit + Intel TBB. 
When I run the code in a computer with processor i9 10900K + RTX3080ti, the code stops at the funcition GetMesh
When I run the code in a computer with processor i9 12900K + RTX3090ti, the code stops at the funcition GetMesh
When I run the code in a computer with processor i7 4558 without nvidia, the code works correctly (slow, but correcty)

Any idea about what is happening?

**Comment by pca006132** [comment]
This sounds like more related to CUDA instead of CPU model. What if you compile without CUDA and run on the i9 GPU?

Also, CUDA can in fact be slower when there are many little operations but the result mesh is not large. We plan to address this issue later.
