### ISSUE TITLE
Build a manifold extension to glTF

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#422]
Considering that Manifold handles arbitrary mesh properties like normals and UVs, it would be nice to be able to round-trip this type of material data through a file format losslessly. This is not generally possible, as even indexed files like OBJ or glTF must be exported as non-manifold when they contain multiple materials (or even sharp corners) as GPUs require the vertex positions to be duplicated for any vertex properties that don't match. Relying on geometric checks (verts having identical positions) to reassemble the manifold will often work, but is unreliable in general. 

It appears that a glTF extension is possible to make that will encode this manifoldness data, and at very little size cost, by using their concept of sparse accessors. I'll write up this extension and propose it to Khronos (since I work with them for my day job anyway), but as far as Manifold is concerned, the work will be to make a reader and writer of this extension, proving that it works. 

I think it'll also be a good opportunity to show off #394 by making a small web tool to upload a GLB and download the manifold version of it (or show that we can't fix it automatically), which will hopefully help with problems like https://github.com/elalish/manifold/issues/91#issuecomment-1429030070

**Comment by elalish** [comment]
Here's the glTF extension draft: https://github.com/KhronosGroup/glTF/pull/2286

**Comment by fire** [comment]
@elalish If I wanted to support this in Godot Engine should I implement this extension? How does it degrade?

**Comment by elalish** [comment]
If you can explain your use case I'll be able to give you a better answer. How do you plan to use manifold meshes? 

Are you still interested in integrating manifold into Godot, or has that been blocked? Anything I can do to make it easier?

**Comment by fire** [comment]
One of the problems with using the manifold library is requiring input manifold meshes. 

If I can keep a chain of manifold gltfs, I can keep the chain all the way to the output. Starting from the cad / 3d modeler, imported into godot engine (triangulated), and then csg merge, subtract and intersect operations, to the resulting mesh which also be used for the input of this chain.

**Comment by fire** [comment]
I think from a point of view of a user, I can have a scene that enforces manifold input. As long as the chain is unbroken, I get a manifold output.
