### ISSUE TITLE
Nix flake update

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#424]
We should clean up the flake, build the project appropriately, and perhaps upstream to nixpkgs.
Should also update emscripten once https://github.com/NixOS/nixpkgs/pull/229718 is landed.

**Comment by elalish** [comment]
Looks like that landed - anything blocking this?

**Comment by pca006132** [comment]
Yeah I checked this previously, they reverted the change and is now waiting for https://github.com/NixOS/nixpkgs/pull/235624

**Comment by pca006132** [comment]
Looking at the nixpkgs commit process, it seems that they PR has to go through staging-next, staging and then to master. So it seems that the issue cannot be closed soon. Manually porting the changes can work but will significantly increase CI time due to lack of binary cache.

**Comment by elalish** [comment]
Meh, no rush.
