### ISSUE TITLE
Get CrossSection from Manifold and plane

### ISSUE THREAD

**Issue by harmanpa** [elalish/manifold#426]
There doesn't appear to be a way of creating a CrossSection from a Manifold. This would be a useful feature for creating a 2D slice from a 3D mesh.

**Comment by pca006132** [comment]
Yes we did think about this in #127, but it seems that we forgot it and no one remember to implement it.

**Comment by elalish** [comment]
Agreed, I've been wanting this, but haven't gotten around to implementing it. Shouldn't be too hard; we can use a similar API to `trimByPlane`.

**Comment by elalish** [comment]
Any interest in contributing @harmanpa?

**Comment by johnnybigert** [comment]
Plus one on this one, would be very useful to have :)

**Comment by harmanpa** [comment]
Awesome, thank you @elalish
