### ISSUE TITLE
Bizarre malloc error in `CalculateCurvature`

### ISSUE THREAD

**Issue by geoffder** [elalish/manifold#450]
I've finally gotten to pulling down the latest master and started updating the C bindings and have hit a bit of a snag. Everything compiles and tests fine for me with CUDA enabled, leading to [`mallocManaged`](https://github.com/elalish/manifold/blob/cce35aa5a04ec606f00dad6d82d66453148128d9/src/utilities/include/vec_dh.h#L254) using `cudaMallocManaged` instead of `malloc`. So malloc is being tripped up by size parameters that are doing fine in the CUDA branch. Any idea what could be going wrong? Won't have more time to try and figure it out for a bit, so dumping here to see if it makes sense to you guys.

**Build Error:**
```
In file included from /home/geoff/git/manifold/src/utilities/include/sparse.h:22,
                 from /home/geoff/git/manifold/src/collider/include/collider.h:17,
                 from /home/geoff/git/manifold/src/manifold/src/impl.h:18,
                 from /home/geoff/git/manifold/src/manifold/src/properties.cpp:21:
In static member function ‘static void manifold::ManagedVec<T>::mallocManaged(T**, size_t) [with T = glm::vec<3, int, glm::packed_highp>]’,
    inlined from ‘void manifold::ManagedVec<T>::shrink_to_fit() [with T = glm::vec<3, int, glm::packed_highp>]’ at /home/geoff/git/manifold/src/utilities/include/vec_dh.h:169:20,
    inlined from ‘void manifold::VecDH<T>::resize(int, T) [with T = glm::vec<3, int, glm::packed_highp>]’ at /home/geoff/git/manifold/src/utilities/include/vec_dh.h:349:36,
    inlined from ‘void manifold::Manifold::Impl::CalculateCurvature(int, int)’ at /home/geoff/git/manifold/src/manifold/src/properties.cpp:355:39:
/home/geoff/git/manifold/src/utilities/include/vec_dh.h:260:42: error: argument 1 range [18446744065119617032, 18446744073709551604] exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
  260 |       *ptr = reinterpret_cast<T *>(malloc(bytes));
      |                                    ~~~~~~^~~~~~~
In file included from /usr/include/c++/13.1.1/cstdlib:79,
                 from /usr/include/c++/13.1.1/ext/string_conversions.h:43,
                 from /usr/include/c++/13.1.1/bits/basic_string.h:4110,
                 from /usr/include/c++/13.1.1/string:54,
                 from /usr/include/c++/13.1.1/bits/locale_classes.h:40,
                 from /usr/include/c++/13.1.1/bits/ios_base.h:41,
                 from /usr/include/c++/13.1.1/streambuf:43,
                 from /usr/include/c++/13.1.1/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/13.1.1/iterator:66,
                 from /home/geoff/git/manifold/src/third_party/thrust/thrust/iterator/iterator_traits.h:36,
                 from /home/geoff/git/manifold/src/third_party/thrust/thrust/count.h:26,
                 from /home/geoff/git/manifold/src/manifold/src/properties.cpp:15:
/usr/include/stdlib.h: In member function ‘void manifold::Manifold::Impl::CalculateCurvature(int, int)’:
/usr/include/stdlib.h:553:14: note: in a call to allocation function ‘void* malloc(size_t)’ declared here
  553 | extern void *malloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~
```

**Machine:**
```
OS: EndeavourOS Linux (Arch based)
Kernel: 6.3.7-zen1-1-ze
```

**Comment by elalish** [comment]
I've never seen an error like that; how can it know an allocation is too big at compile time? @pca006132 any thoughts, since you did the `ManagedVec` work?

**Comment by geoffder** [comment]
For a bit more context now that I;m poking it again, it is [this line](https://github.com/elalish/manifold/blob/cce35aa5a04ec606f00dad6d82d66453148128d9/src/manifold/src/properties.cpp#L355) as mentioned by the error message. Specifically, it doesn't like that `NumTri()` is informing the number of bytes that should be allocated. Giving an int literal compiles fine.

```cpp
  if (meshRelation_.triProperties.size() == 0) {
    // int n = NumTri(); // error
    int n = 1000000000;  // compiles
    meshRelation_.triProperties.resize(n);
  }

```

**Comment by geoffder** [comment]
Bizarrely, this compiles. Looking at `resize` and `reserve` in `VecDH`, I'm not sure exactly what this avoids, since `resize` is supposed to be doing a `reserve` anyway...
```cpp
  if (meshRelation_.triProperties.size() == 0) {
    int n = NumTri();
    meshRelation_.triProperties.reserve(n);
    meshRelation_.triProperties.resize(n);
  }
```

**Comment by elalish** [comment]
That's bizarre - what compiler is this? I feel like I have lines all over the code base that do that; it seems strange it would only complain about that one.

**Comment by geoffder** [comment]
> what compiler is this?

This was built with the default system compiler (gcc).

```
❯ /usr/bin/c++ --version
c++ (GCC) 13.1.1 20230429
```

It definitely is weird, `resize` is used indirectly with functions of `NumVerts()` etc all over the place, as the constructors of `VecDH` call it. I don't know why this particular line is tripping it up, and why adding a `reserve` before avoids it.

**Comment by geoffder** [comment]
Given that adding a line that should be redundant avoids the error, I got suspicious that it is an optimization issue, and I think that I'm right.
```cmake
set(MANIFOLD_FLAGS -O0)
```
Turning off optimizations in Manifold by setting `-O0` in `CMakeLists.txt` compiles for me. Setting `-O1` hits the same error.

**Comment by geoffder** [comment]
Modifying [`ManagedVec::shrink_to_fit`](https://github.com/elalish/manifold/blob/cce35aa5a04ec606f00dad6d82d66453148128d9/src/utilities/include/vec_dh.h#L166) like so:
```cpp
  void shrink_to_fit() {
    T *newBuffer = nullptr;
    if (size_ > 0) {
      // mallocManaged(&newBuffer, size_ * sizeof(T));      
      int sz = size_ * sizeof(T);
      mallocManaged(&newBuffer, sz);
      prefetch(newBuffer, size_ * sizeof(T), onHost);
      uninitialized_copy(autoPolicy(size_), ptr_, ptr_ + size_, newBuffer);
    }
    freeManaged(ptr_);
    ptr_ = newBuffer;
    capacity_ = size_;
  }
```
avoids the error for me (without the pre-emptive `reserve` line mentioned above).

**Comment by geoffder** [comment]
This [issue](https://gcc.gnu.org/bugzilla//show_bug.cgi?id=85783) I found in my travels may be related. Maybe breaking out the size calculation to another line defeats the inlining somehow?

**Comment by elalish** [comment]
That looks like a perfectly reasonable change, even if it is a GCC bug workaround. The wisdom I always heard was if you think it's a compiler bug, it's really your own bug, but here I'm tempted to disagree.

**Comment by geoffder** [comment]
Ok, I'll make a PR with this fix then.

**Comment by pca006132** [comment]
I agree this is very weird... Perhaps gcc somehow thinks that NumTri can return something negative?

**Comment by geoffder** [comment]
> I agree this is very weird... Perhaps gcc somehow thinks that NumTri can return something negative?

I did experiment with that, but casting to unsigned didn't change anything in this case (though I saw examples online where that fixed peoples malloc problems).

**Comment by pentacular** [comment]
Just from curiosity, what is the point of reserve(n) followed by resize(n)?
