### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jw3126** [elalish/manifold#467]
I followed the build instructions in the README, but got his error:
```
manifold/src/third_party/thrust/thrust/system/detail/sequential/trivial_copy.h:47:17: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 18446744022169944064 and 18446744073709551592 bytes into a region of size between 0 and 2147483647 [-Werror=stringop-overflow=]
   47 |     std::memmove(result, first, n * sizeof(T));
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by pca006132** [comment]
which compiler are you using?

**Comment by jw3126** [comment]
I am using gcc:
```
c++ (GCC) 13.1.1 20230429
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by pca006132** [comment]
@geoffder can you reproduce this? iirc you are also using gcc 13.1.1

**Comment by geoffder** [comment]
Haven't had an an error in `memmove` so far no.

**Comment by pca006132** [comment]
Can you show the cmake command you used?

**Comment by jw3126** [comment]
Sure I did `cd build && cmake .. && make`

**Comment by elalish** [comment]
Does it repro with `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON .. && make` like in the README? Just curious why no one else has seen this.

**Comment by jw3126** [comment]
> Does it repro with `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON .. && make` like in the README? Just curious why no one else has seen this.

yes gives me the same error

**Comment by pca006132** [comment]
It seems that gcc for some reason will complain about our code... Maybe try to set cmake_cxx_compiler to clang++ and see if it works?

**Comment by jw3126** [comment]
@pca006132 thanks, the following build successfully for me:
`cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER=/usr/bin/clang++ .. && make -j16`

**Comment by elalish** [comment]
Glad we have a work-around. Is this all versions of GCC? Seems like we should fix this... The old adage comes to mind: if you think you found a compiler bug, it's probably your own bug. I suppose we could also check and see if Thrust knows about this or has fixed in meanwhile.
