### ISSUE TITLE
Request - New field for MeshRelation : Clipped triangles 

### ISSUE THREAD

**Issue by yetigit** [elalish/manifold#490]
New field for MeshRelation : clippedTriangles

it would basically be a `Vec<char>` of size `numTri()` telling us whether the i'th triangle of the result is from the clipping step of the boolean operation or not (clipping that occurred because mesh A was cutting into mesh B).

It's I think (not sure) equivalent to asking which tris are at the intersection / contact points  created by the boolean operation.

it does not have to be a new field for mesh relation persay, maybe it could be just a `Manifold::` method retrieving this piece of information.

### Why ?

because it would allow to track which faces (in a polyhedron) were impacted by the boolean operation
and based on that make targeted processing of either non-clipped polygons or clipped/tesselated polygons.

most of the time in a boolop a very small subset of the polygons are getting clipped or tesselated into, it makes sense to know or have some indirect way to know what geometry was spared in the process.

**Comment by elalish** [comment]
Can you give some details of what kinds of processing you envision doing on these triangles? The triangle runs of MeshGL exactly show the sets of triangles from each input mesh, so you can find the intersections as the open edges of these submeshes. Is that adequate?

**Comment by elalish** [comment]
I've updated the wiki with some description of this too: https://github.com/elalish/manifold/wiki/Manifold-Library#vertex-properties

**Comment by yetigit** [comment]
sorry for getting back to you after this long @elalish 

> This is what faceID & originalID are for in GetMeshGL. For every output triangle, it says which input mesh it came from via originalID and which input triangle it came from in faceID

I was also able to create mappings using `Mesh` and `triRef` from `MeshRelations`, way before this issue, this is not a problem for me.

When it comes to using `faceID` and `MeshGL` I must say that the result of the boolean coming as a `MeshGL`  from `getMeshGL()` will refer back not to the polygon ID's but to the triangles of the mesh submitted; for example on a cube the maximum index would be 5 (6 faces) , but here `faceID` will refer to tris, so will refer to ID's all the way to 11 (12 faces since the triangulation), which isn't what I was expecting but in this sense it's exactly like `triRef`.

![ApplicationFrameHost_Kjyus40pvn](https://github.com/elalish/manifold/assets/7016200/ac0ca1dc-9697-449f-a6e2-c231c8c0268c)


>  For every output triangle, it says which input mesh it came from via originalID

constructing a `Manifold` from a `MeshGL`, will always currently result in `OriginalID` returning / being `-1`. So if I wanted to do an external property map per mesh, I cannot rely on the `original ID`. 

After all this is the very end of  `Manifold::Impl::Impl(const MeshGL& meshGL, std::vector<float> propertyTolerance)` 

: 

```
  *this = Impl(mesh, relation, propertyTolerance, !meshGL.faceID.empty());

  // A Manifold created from an input mesh is never an original - the input is
  // the original.
  meshRelation_.originalID = -1;

```

Also (nothing to do with this issue) when it comes to `Mesh` and `MeshGL` I must say that I noticed they have different tesselations. `Mesh` will tend to create way fewer triangle on the clipped parts for example.

> If polygon face 10 was triangulated into tris 3, 5, and 8, then it will pick one (the largest area) as the faceID. If it is untouched, those three triangles will appear in the output, all with e.g. faceID == 5. If they were intersected and turned into more or fewer triangles, the same will be true.

Ok, but I take that the original polygon must be planar. `Manifold` will group every triangle of that polygon only if they are coplanar for one; and, I also take that in this example `faceID == 5` because 5 happened to be the largest triangle ? So therefor If I want to know which faces were untouched this way , I would have to probe the area of my triangles and also make sure my polygons (n >= 4) are planar.

> If a neighboring triangle has a different originalID, then that edge has been created by the Boolean op.

it sounds like a much more interesting idea, however I am not familiar or even aware of the existence of adjacency queries API's  in the library. And I can't help but think it would be easier to just mark these faces in some ways during the collision process.

**Comment by elalish** [comment]
Oh man, there's a lot here and maybe several of these should be individual discussions. 

1) If you create a `Manifold` from an input `MeshGL` you can assign an `originalID` yourself. If you don't, one will be assigned for you, which you can read by doing an immediate `GetMeshGL`. My comment is merely saying the triangle indices always reference the triangle indices of the input mesh, not the output mesh (which is sorted). 
2) If you have your own mapping of triangles to whatever your concept of faces is, then with my `faceID` (which is indeed a triangle index), you should be able to get back to your faces, no?
3) We don't currently expose our halfedge data structure, since I had figured users would want to use their own. It's pretty trivial to create one. We could expose it if there's demand.

**Comment by yetigit** [comment]
> 1. If you create a Manifold from an input MeshGL you can assign an originalID yourself

oh ok sorry I hadn't check these examples.

```
  outGL.runOriginalID = {Manifold::ReserveIDs(1)};
  return outGL;

```

> 2. If you have your own mapping of triangles to whatever your concept of faces is, then with my faceID (which is indeed a triangle index), you should be able to get back to your faces, no?

yes yes yes, that's what I did before but I thought it was different with faceID
