### ISSUE TITLE
Python Interface Vertex and Face Types

### ISSUE THREAD

**Issue by Eric-Vin** [elalish/manifold#543]
It seems that the vertices and faces of Mesh objects in the Python interface are PyCapsule objects, not numpy arrays. Is there a way to easily convert these?

As an example, running the following script:
```
in_mesh = trimesh.creation.box(extents=[2,0.5,0.2])
manifold = Manifold.from_mesh(Mesh(vert_properties=np.asarray(a.vertices), tri_verts=np.asarray(a.faces)))
out_mesh = manifold.to_mesh()

print(type(out_mesh.vert_properties))
print(type(out_mesh.tri_verts))
```

Outputs the following:
```
<class 'PyCapsule'>
<class 'PyCapsule'>
```

**Comment by pca006132** [comment]
It seems that the PyCapsule can be converted to numpy array using `numpy.array(out_mesh.vert_properties)`, but I will convert it in our binding directly to avoid confusion. (and just found that I forgot to test mesh export in our CI)

Thanks!

**Comment by Eric-Vin** [comment]
Ah, that makes sense. Thanks for the quick response!

**Comment by Eric-Vin** [comment]
Just tried the new fix, and it's working well! One small issue:  `tri_verts` is currently being exported as an array of floats, when I think it should be an array of integer values?

**Comment by pca006132** [comment]
Nice catch! This should be a very simple fix. I don't have my laptop with me for now, maybe you can open a PR and we can merge it?

**Comment by Eric-Vin** [comment]
Sure thing! Here's a PR: https://github.com/elalish/manifold/pull/546
