### ISSUE TITLE
Subtraction creates overlapping triangles

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#562]
I discovered this while testing my offset algorithm.

```c++
Manifold cubesphere = Manifold::Cube({8, 8, 8}, true) - Manifold::Sphere(5);
std::cout << cubesphere.NumDegenerateTris() << std::endl;
cubesphere = cubesphere.SplitByPlane({-0.770, -0.632, -0.085}, 4.958).second;
std::cout << cubesphere.NumDegenerateTris() << std::endl;
ExportMesh("cubesphere.ply", cubesphere.GetMesh(), {});
```

There are no degenerate triangles and it seems that the output is a 2-manifold, but the output contains overlapping triangles:

![image](https://github.com/elalish/manifold/assets/12198657/f4533e58-b9fe-485c-bac9-41dbc1439f49)

**Comment by pca006132** [comment]
I tried disabling tbb, change `Split` to use the public boolean API (instead of reusing Boolean3), and enabled address sanitizer. The result is the same.

**Comment by pca006132** [comment]
I did not optimize the decomposition algorithm, so it tends to generate cuts that precisely touch some triangles. I will try to optimize the algorithm, but it also reveals some issues in our boolean.

**Comment by elalish** [comment]
Can you be a touch more specific regarding what the overlapping triangles are? Is your only evidence that render? Technically what this library intends to generate is &epsilon;-valid geometry, which means there exists a perturbation of the vertices each by less than precision that means all points in R3 have winding number either 1 or 0. Do you believe this condition has been violated? It would also be nice to avoid folds, where triangles become coplanar, but this cannot in general be avoided. Is that the situation?

**Comment by pca006132** [comment]
Oh, I think it is probably coplanar triangles:

![image](https://github.com/elalish/manifold/assets/12198657/f3a661ba-b164-4aa7-8e43-19888066a239)

The reason I noticed this is because the offset result becomes a giant cthulhu... I just debugged it and found that the bug is caused by zero thickness cases causing the algorithm to blow up. Maybe I should close this?

**Comment by pca006132** [comment]
The overlapping stuff are just the back faces, verified by meshlab.

**Comment by pca006132** [comment]
Thinking about it, this should be closed as the result is geometrically valid.
