### ISSUE TITLE
extrude twist can cause invalid geometry

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#563]
I was thinking about the twist parameter when I was looking at offset extrude. It seems that the twist parameter can cause invalid geometry when the `nDivisions` is small. This problem also exists in OpenSCAD (which does not use our extrude algorithm) so this is pretty general.

Extruding a square with `twist=180` and `nDivisions=0` (*not necessarily invalid*, I am just showing here because it is a simpler case):
![image](https://github.com/elalish/manifold/assets/12198657/b6cd3696-a03d-4877-bc00-2626e4e041dc)

Extruding a concave polygon (`square(glm::vec2(2), false) - square(glm::vec2(1), false)` with `twist=180` and `nDivisions=0`:
![image](https://github.com/elalish/manifold/assets/12198657/f4d999ac-3899-4473-9094-8184f36c510c)

**Comment by pca006132** [comment]
> I would call this user issue, not library issue. :)

I think it depends on how you view the APIs. For example, the documentation of the warp function explicitly says that it is very easy to create self-intersections and we do not check them now.

The way I see this is that, except certain APIs that we have warned the users, geometrically valid inputs should result in geometrically valid output. Anything violating this is a bug. (which we can also 'fix' by saying that the user should pay attention to blablabla...)
For this case, it is not easy to see what is the minimal number of segments to create a valid result.

**Comment by elalish** [comment]
I look at this exactly like the Warp function, and you're right that it should probably have a similar warning. I am planning to try and implement an overlap removal algorithm, in which case that can be run automatically after operations like these.

**Comment by pca006132** [comment]
@platypii suggested we can rotate the points to avoid getting self-intersections, though it will only work if the points are evenly spaced.

Wonder if this can work in general if we interpolate the points into segments with roughly the same lengths? One problem is that the geometry will be different even for cases that there are no self-intersections.

**Comment by elalish** [comment]
I think that's a little too clever - could easily surprise users. Let's wait for a proper solution that will handle Warp as well.
