### ISSUE TITLE
XCode 15 Link problem with <memory_resource>

### ISSUE THREAD

**Issue by ramcdona** [elalish/manifold#565]
XCode 15's standard library moved <memory_resource> from <experimental/memory_resource> to production use.  This turned it 'on' in my build (polygon.cpp), but then my application crashes on start with a dyld error looking for something I surmised was related to memory_resource.

It looks like XCode 15 has a brand new linker that is causing all kinds of problems.  The best advice appears to be avoiding it.

MacOS Ventura 13.6

**Comment by elalish** [comment]
Thanks for the head's up. No doubt I'll have to deal with this at some point - hopefully Apple figures it out first.

**Comment by elalish** [comment]
Hmm, I just updated my Mac and tried out Clang 15 - it seems to be working fine? Maybe this is different than the XCode 15 change, though I thought they kept all those versions in lock step...

**Comment by pca006132** [comment]
Maybe try a clean build? There may be old makefiles referencing the old toolchain and causes some issue.

**Comment by ramcdona** [comment]
Since I got it fixed, I have had trouble recreating this problem.  When I was chasing it down, I did multiple clean builds.

I work with CMake if that makes any difference.

If nobody can recreate, go ahead and close it.

**Comment by elalish** [comment]
Glad to hear it - I use CMake as well and it's working fine for me, so let's close this for now and resurrect it if the problem shows up again.
