### ISSUE TITLE
How could I create a manifold object for a simple rectangle? 

### ISSUE THREAD

**Issue by jedecsam** [elalish/manifold#566]
I used such following code to create a manifold object, the status is  NotManifold. 
Mesh testMesh;
  testMesh.vertPos = {{0.0f, 0.0f, 0.0f},
                  {1.0f, 0.0f, 0.0f},
                  {1.0f, 1.0f, 0.0f},
                  {0.0f, 1.0f, 0.0f}};
  testMesh.triVerts = {{0, 1, 2}, {0, 2, 3}};
  Manifold corner(testMesh);
  auto status = corner.Status();
  The status is "NotManifold".
  
I simply want to perform mesh boolean operations on a basic rectangle. How can I achieve this?

**Comment by pca006132** [comment]
You can't. If you want boolean operations on 2D objects, you can use Clipper2 (directly or indirectly via our CrossSection API).

**Comment by jedecsam** [comment]
Thank you for your response. I will try your suggestion.

**Comment by elalish** [comment]
I'd also recommend you look at our [definition of manifoldness](https://github.com/elalish/manifold/wiki/Manifold-Library#manifoldness) so you can see why a plane is not a manifold mesh.

**Comment by pca006132** [comment]
I think we should close this. @jedecsam if you have more questions feel free to open a discussion.
