### ISSUE TITLE
Python binding to Manifold.Split() does not work

### ISSUE THREAD

**Issue by rsaccon** [elalish/manifold#592]
I am using latest release and tried out the Python bindings. All works great so far except the binding to `Manifold.Split`

the signature of the original function (looked up in documentation) is:
```
std::pair< Manifold, Manifold > Split ( const Manifold &  cutter ) const
```

the Python binding definition however looks incomplete to me:
```
.def("split", &Manifold::Split,
           "Split cuts this manifold in two using the cutter manifold. The "
           "first result is the intersection, second is the difference. This "
           "is more efficient than doing them separately.")
```

**Comment by zalo** [comment]
Ah yeah, nanobind doesn't like that it returns an std::pair...

It would have to be replaced with something like:
```c++
      .def("split", [](Manifold &self, Manifold& cutter) {
            auto p = self.Split(cutter);
            return nb::make_tuple(p.first, p.second);
           },
           nb::arg("cutter"),
           "Split cuts this manifold in two using the cutter manifold. The "
           "first result is the intersection, second is the difference. This "
           "is more efficient than doing them separately."
           "\n\n"
           ":param cutter: This is the manifold to cut by.")
```

**Comment by rsaccon** [comment]
I also tried to build locally on my old intel mac, finally was able to build, but my attempt to use the local built bindings (the not yet modified ones) failed, so many things can go wrong, well, I guess I have to wait for the next pipy release for this Split() binding to work ...

**Comment by zalo** [comment]
If a version of this PR https://github.com/elalish/manifold/pull/593 works, you might be able to extract a working version of the Python wheel from the Github Actions build action.

**Comment by rsaccon** [comment]
I just managed to get my local build working, tested the modified binding, @zalo `Split` works now as expected, thanks.
