### ISSUE TITLE
iterator invalidation in triangulator

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#599]
https://github.com/elalish/manifold/blob/b439603eb912014b7813403ffdf7ff9d891c3c18/src/polygon/src/polygon.cpp#L546-L556

https://github.com/elalish/manifold/blob/b439603eb912014b7813403ffdf7ff9d891c3c18/src/polygon/src/polygon.cpp#L711-L714

`VertItr` is invalidated after the vector is modified, so it may cause segfault. We can either leave the linked list setup after the `polygons_` vector is filled, or just use indices instead of iterator references (recommended).

Should be the cause of https://github.com/openscad/openscad/issues/4814

**Comment by elalish** [comment]
Hmm, I thought line 188: `polygon_.reserve(numVert + 2 * polys.size());` would take care of that - they're not invalidated if there's enough reserved, right? Is my math wrong?
