### ISSUE TITLE
Python binding to Manifold.Smooth() does not work

### ISSUE THREAD

**Issue by rsaccon** [elalish/manifold#602]
When I try a simple example like
```
model = Manifold.cube(1, 2, 3)  
mesh = model.to_mesh()
model = Manifold.smooth(mesh)
```

I get the error:
```
    model = Manifold.smooth(mesh)
            ^^^^^^^^^^^^^^^^^^^^^
TypeError: smooth(): incompatible function arguments. The following argument types are supported:
    1. smooth(arg: manifold::Mesh, /) -> manifold3d.Manifold

Invoked with types: manifold3d.Mesh
```

also the binding is incomplete, `sharpenedEdges` parameter is not supported. And if I look at the JS scallop example, there is also a `CalculateCurvature` method which is not yet present at the Python bindings.

**Comment by elalish** [comment]
Good catch. We really need to port our examples to Python so we have better test coverage of these bindings.

**Comment by zalo** [comment]
The LevelSet function could also benefit from the exposure of the non-gl Mesh class (to prevent unnecessary manifoldization)… that might be one of the things I tackle in my PR.

**Comment by elalish** [comment]
So, we're in the process of deprecating `Mesh` in favor of `MeshGL` (both are independent of `Manifold`), because `MeshGL` is a lot more flexible, as well as being faster to move to a GPU or across C-style bindings. `LevelSet` returns a `Mesh` because that was easy, but for bindings I only want to expose `MeshGL` (the JS & Python bindings just call it `mesh` since the other isn't exposed).

**Comment by pca006132** [comment]
Actually I'm wondering if we can just change the signature of SDF and `Smooth` to not take/output a mesh, and use `Manifold` uniformly across the APIs. For SDF it can also skip some operations such as `SplitPinchedVerts`.

**Comment by elalish** [comment]
Yeah, that is a possibility. The original reason for using `Mesh` with SDF is so that it didn't have to depend on `Manifold`, but maybe this isn't so important in practice. It would also allow us to do degenerate removal automatically, which SDF could certainly use.
