### ISSUE TITLE
Infinite loop in ear clipping 

### ISSUE THREAD

**Issue by starseeker** [elalish/manifold#606]
Hi!  I work on BRL-CAD (https://github.com/BRL-CAD/brlcad) which is an open source CSG modeling system.  We've recently wired Manifold into our facetize command (for converting implicit CSG boolean trees into evaluated meshes) and gotten excellent results.  However, on rare occasions I'm seeing what appears to be non-manifold output from a boolean operation, which is then fed back into the next operation and causing some sort of infinite loop (when I break gdb reports the code is in EarClip::Triangulate(), specifically EarClip::ProcessEar):

left: (((7863.1.t0.rcc.16_18 u 7863.1.t0.rcc.17_18) u (7863.1.t0.rcc.19_20 u 7863.1.t0.rcc.19_21)) u ((7863.1.t0.rcc.19_22 u 7863.1.t0.rcc.19_23) u (7863.1.t0.rcc.19_24 u 7863.1.t0.rcc.19_25)))
right: (((7863.1.t0.rcc.16_18 u 7863.1.t0.rcc.17_18) u (7863.1.t0.rcc.19_20 u 7863.1.t0.rcc.19_21)) u ((7863.1.t0.rcc.19_22 u 7863.1.t0.rcc.19_23) u (7863.1.t0.rcc.19_24 u 7863.1.t0.rcc.19_25)))
Manifold op: Union

The boolean strings aren't important here except to indicate that both the left and right inputs to the union operation are themselves output from other Manifold operations.  I've tried to capture the meshes themselves at:

http://brlcad.org/~starseeker/7863.1.t0_left.stl
http://brlcad.org/~starseeker/7863.1.t0_right.stl

I know this isn't the glb export from the Manifold routines used for tests, and if it should prove necessary or desirable I'm willing to try and wire up the exact Manifold methods for capturing glb files.  My own tooling suggests that the 7863.1.t0_right.stl input may be the problematic one, but I'm not completely sure of that.  If the necessary inputs for debugging need to come from the earlier mesh inputs that generated 7863.1.t0_right.stl I can try to capture those as well.

Thank you for making an excellent library available - overall, we saw a significant improvement in the success rate of our conversions when we wired Manifold into our pipeline, so it's quite an exciting development.

**Comment by pca006132** [comment]
I don't think stl can preserve manifoldness, so it may not be possible to debug from the stl files. Did you enable `MANIFOLD_DEBUG`? This CMake option will enable some tests that can ensure the intermediate results are correct, e.g. are manifold. Also, are you using Windows? There is recently a weird crash (https://github.com/openscad/openscad/issues/4814) on Windows which may or may not be related, so maybe you can also try to run it on Linux if you are using Windows to see if it is related.

**Comment by starseeker** [comment]
I'm using Ubuntu Linux.  Rebuilding with MANIFOLD_DEBUG defined doesn't seem to change anything.  So Manifold's capture of the data with glb will be sufficient?  If so I can try to get that working.

**Comment by pca006132** [comment]
Yes glb should be sufficient. I think just dumping the Mesh struct output with some serialization format should also work, if that is easier.

**Comment by starseeker** [comment]
Here are glb files dumped with ExportMesh:
http://brlcad.org/~starseeker/7863.1.t0_left.glb
http://brlcad.org/~starseeker/7863.1.t0_right.glb

**Comment by elalish** [comment]
Thanks for generating GLBs! Would you mind sending a PR with an added `TEST` like [this one](https://github.com/elalish/manifold/blob/master/test/samples_test.cpp#L258-L269)? This will ensure we have a repro of your problem if we can see it fail on our CI.

**Comment by elalish** [comment]
Also, I'm excited that Manifold is mostly working for BRL-CAD! If you wouldn't mind, please tell us about it in https://github.com/elalish/manifold/discussions/340 - it's great to know about our users.

**Comment by starseeker** [comment]
Done.  Summary added, and PR #608 is currently being tested.

**Comment by pca006132** [comment]
I think this and #607 should probably be merged as one issue about triangulator robustness. Apparently there are still some really weird inputs that can cause the triangulator to crash/loop indefinitely. We should do some fuzzing to make sure that it will never have such behavior.

**Comment by starseeker** [comment]
Did you want me to rework it into one pull request?

**Comment by pca006132** [comment]
maybe we can let @elalish have a look at it first, I can only identify this to be some triangulator issue, but not sure what exactly is the problem
