### ISSUE TITLE
Perf regression with properties

### ISSUE THREAD

**Issue by stephomi** [elalish/manifold#619]
This commit https://github.com/elalish/manifold/commit/a842de97c656c8890ae09d9008791857f8ba0d76
Caused by removal of this line https://github.com/elalish/manifold/blob/5e103931f1191eba8eb25d89b1039aa58a03e0db/src/manifold/src/boolean_result.cpp#L559

It creates tons of unique properties and the bins size gets very big (linear search...).
I don't have the full picture but it's a huge perf regression (unusable if polycount > ~70k).

Maybe using a map for the "miss prop" option? (don't really have time to make a PR or do some test atm)

```diff
diff --git a/src/manifold/src/boolean_result.cpp b/src/manifold/src/boolean_result.cpp
index 08ca4af..73f0665 100644
--- a/src/manifold/src/boolean_result.cpp
+++ b/src/manifold/src/boolean_result.cpp
@@ -532,7 +532,8 @@ void CreateProperties(Manifold::Impl &outR, const Manifold::Impl &inP,
 
   using Entry = std::pair<glm::ivec3, int>;
   int idMissProp = outR.NumVert();
-  std::vector<std::vector<Entry>> propIdx(outR.NumVert() + 1);
+  std::vector<std::vector<Entry>> propIdx(outR.NumVert());
+  std::unordered_map<glm::ivec3, int> propIdxMiss;
   outR.meshRelation_.properties.reserve(outR.NumVert() * numProp);
   int idx = 0;
 
@@ -577,17 +578,28 @@ void CreateProperties(Manifold::Impl &outR, const Manifold::Impl &inP,
         }
       }
 
-      auto &bin = propIdx[key.y];
       bool bFound = false;
-      for (int k = 0; k < bin.size(); ++k) {
-        if (bin[k].first == glm::ivec3(key.x, key.z, key.w)) {
-          bFound = true;
-          outR.meshRelation_.triProperties[tri][i] = bin[k].second;
-          break;
+      if (key.y == idMissProp) {
+        auto res =
+            propIdxMiss.try_emplace(glm::ivec3(key.x, key.z, key.w), idx);
+        if (!res.second) {
+          outR.meshRelation_.triProperties[tri][i] = res.first->second;
+          continue;
         }
+
+      } else {
+        auto &bin = propIdx[key.y];
+        for (int k = 0; k < bin.size(); ++k) {
+          if (bin[k].first == glm::ivec3(key.x, key.z, key.w)) {
+            bFound = true;
+            outR.meshRelation_.triProperties[tri][i] = bin[k].second;
+            break;
+          }
+        }
+        if (bFound) continue;
+        bin.push_back(std::make_pair(glm::ivec3(key.x, key.z, key.w), idx));
       }
-      if (bFound) continue;
-      bin.push_back(std::make_pair(glm::ivec3(key.x, key.z, key.w), idx));
+
       outR.meshRelation_.triProperties[tri][i] = idx++;
 
       for (int p = 0; p < numProp; ++p) {
```

**Comment by elalish** [comment]
Interesting; it sounds like you and I have found exactly opposite results from this change: https://github.com/elalish/manifold/pull/587#discussion_r1380609494

Considering I already have a test for this (that passes) is there a chance you can give me any kind of basic test that showcases a situation where duplicate propVerts are created? I'd like to get this fixed before pushing v2.2.2 if possible.

**Comment by elalish** [comment]
Oh, maybe you don't mean we actually end up with duplicate propVerts in the output, but rather that our internals are just slow now? @pca006132 would you mind taking a look at this? I can't get his diff to compile because it needs a hash function, and you know much more about optimizing unordered_map than I do.

**Comment by pca006132** [comment]
I am working on fuzzer stuff, I managed to get the thing to hang but I am struggling to terminate the thread.
Will have a look at this later when I finish dealing with the fuzzer.

**Comment by elalish** [comment]
I love the idea of adding a fuzzer, but I'm not sure how much time it'll take to fix the bugs it discovers - we may want to deal with that after this point release.

**Comment by pca006132** [comment]
sure, I just want to make it work first (considering it is near working now)

**Comment by pca006132** [comment]
OK now the fuzzer stuff is working, will look at this tmr.

**Comment by stephomi** [comment]
> Oh, maybe you don't mean we actually end up with duplicate propVerts in the output, but rather that our internals are just slow now? @pca006132 would you mind taking a look at this? I can't get his diff to compile because it needs a hash function, and you know much more about optimizing unordered_map than I do.

#include <glm/gtx/hash.hpp>
