### ISSUE TITLE
precision calculation causes collider error

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#634]
For the following code:
```c++
TEST(Boolean, Spiral) {
  ManifoldParams().deterministic = true;
  const int d = 2;
  std::function<Manifold(const int, const float, const float)> spiral = [&](const int rec, const float r, const float add) {
    const float rot = 360.0f / (glm::pi<float>() * r * 2) * d;
    const float rNext = r + add / 360 * rot;
    const Manifold cube = Manifold::Cube(glm::vec3(1), true).Translate({0, r, 0});
    if (rec > 0)
      return spiral(rec-1, rNext, add).Rotate(0, 0, rot) + cube;
    return cube;
  };
  const Manifold result = spiral(117, 25, 2);
}
```

It causes error for rec > 117. It seems that it triggered collider error:
```
'leafBB.size() == NumLeaves()' is false: must have the same number of updated boxes as original
```
and causes Vec out of range when MANIFOLD_DEBUG is not enabled.

**Comment by pca006132** [comment]
It seems that collapseEdge replaced everything with NAN at some point, which causes everything to be removed (0 triangles), and the collider update will fail. Why everything is replaced with NAN is unknown...

**Comment by pca006132** [comment]
Maybe we should track the precision as a 3D vector, so things like rotation can work?

**Comment by elalish** [comment]
Yes, I would bet it is too conservative. Can you drop an image of what this shape looks like when it's still working? And how quickly does the precision increase compared to the bounding box? Generally a pure rotation should have a determinant of 1, and therefore not affect the precision much (it is still layering on rounding errors, so some growth is probably correct, but it should be quite slow).

**Comment by pca006132** [comment]
![image](https://github.com/elalish/manifold/assets/12198657/ce398cb2-2497-439e-b2ed-259fab899205)

The precision increases something like this:
```
found 0 short edges to collapse
precision: 0.281999
found 0 short edges to collapse
precision: 0.303284
found 0 short edges to collapse
precision: 0.326196
found 0 short edges to collapse
precision: 0.350863
found 0 short edges to collapse
precision: 0.377420
found 0 short edges to collapse
precision: 0.406014
found 0 short edges to collapse
precision: 0.436805
found 0 short edges to collapse
precision: 0.469961
found 0 short edges to collapse
precision: 0.505669
found 0 short edges to collapse
precision: 0.544126
found 0 short edges to collapse
precision: 0.585548
found 0 short edges to collapse
precision: 0.630166
found 0 short edges to collapse
precision: 0.678230
found 0 short edges to collapse
precision: 0.730009
found 0 short edges to collapse
precision: 0.785796
found 0 short edges to collapse
precision: 0.845904
found 0 short edges to collapse
precision: 0.910673
found 0 short edges to collapse
precision: 0.980468
found 0 short edges to collapse
precision: 1.055686
found 2856 short edges to collapse
```

It increases by about 7% every transform.

**Comment by elalish** [comment]
Yeah, 7% seems like a lot. Also, how is the precision starting at 0.28? I would have expected more like `r * tol`, which should be `2.5e-4`.

**Comment by elalish** [comment]
So, this is the problem line: https://github.com/elalish/manifold/blob/master/src/manifold/src/impl.cpp#L782

I'm taking some kind of a matrix norm here, but agreed that it's too conservative. What do you think would be better? Max singular value might be nice, but a little complicated to compute...

**Comment by pca006132** [comment]
I'm thinking about something like a (not axis-aligned) bounding box which is called a precision box. This can track the precision along arbitrary direction. The box will be transformed according to the matrix. We will also compute a box with dx = dy = dz= kTolerance * max(coord), and update the precision box by taking the union of the two and return a bounding box that covers both boxes (not axis-aligned in general). The actual precision will be the max coordinate of the points in this box. Not sure if this makes sense though, as rotation can improve precision in some cases when this is used.
