### ISSUE TITLE
Smoothing with smoothness 0 on all edges does not return the original geometry

### ISSUE THREAD

**Issue by Niels-IO** [elalish/manifold#641]
As continuation from discussion #639 I created a simpler showcase for the behavior of smoothing a shape where the smoothness of all half-edges is set to 0. It doesn't result in reproducing the un-smoothened geometry, but also distorts vertices.

This is the result of a smoothness of 0 on all halfedges of a cube:
<img width="429" alt="image" src="https://github.com/elalish/manifold/assets/47059882/869ae7c4-fdb3-4ffd-82c9-7262e7f2949c">

And the (seemingly correct) smoothing result for smoothness of 1:
<img width="546" alt="image" src="https://github.com/elalish/manifold/assets/47059882/52393296-4f69-4075-a1fa-db8e2fb88911">

This is the JS code that re-produces the behavior:
```javascript

const cube = Manifold.cube(1)

const numTriangles = cube.numTri();

const sharpEdges = []

for (let i = 0; i<= numTriangles; i++){
  for(let halfEdgeIndex = 0; halfEdgeIndex <=2; halfEdgeIndex++){

  sharpEdges.push({halfedge: i+halfEdgeIndex, smoothness:0.0})
  }
}
const result = Manifold.smooth(cube.getMesh(),sharpEdges).refine(2)
```

Thank you very much for looking into it!

**Comment by elalish** [comment]
I found a couple of bugs in your code; fixing those produces a somewhat better result, though still not what you're expecting:
```js
const cube = Manifold.cube(10)

const numTriangles = cube.numTri();

const sharpEdges = []

for (let i = 0; i< numTriangles; i++){
  for(let halfEdgeIndex = 0; halfEdgeIndex <=2; halfEdgeIndex++){

  sharpEdges.push({halfedge: 3*i+halfEdgeIndex, smoothness:0.0})
  }
}
const result = Manifold.smooth(cube.getMesh(),sharpEdges).refine(100);
```
<img width="597" alt="image" src="https://github.com/elalish/manifold/assets/1649964/07bf38ab-a581-4c15-a046-a141a6806f00">
I'm not sure this is exactly a bug, as my `smooth` function is pretty heuristic. If you want to be precise, you should specify your own `halfedgeTangent` vectors. I'm actually quite interested in other ways to auto-generate these, since there are many ways one could go about it. One thing that might be confusing it is that you're specifying zero smoothness even between triangles on the same face. Anyway, please continue to experiment and report your results. I'd like to build out more functionality around smoothing.

**Comment by Niels-IO** [comment]
Hi @elalish,

Thanks for the fix! This looks indeed better. I am still struggling to fully grasp the concept of how your smoothing is actually working.

My motivation for this experiment was to see if your smoothing function can be used to mimic the subd workflow I am using heavily in other CAD software like in Fusion (based on T-Splines) and CATIA based on _Imagine and Shape_ subd surfaces.

To give an example: you can get very nice and smooth looking surfaces with a very coarse contol polygon using this subd approach:
Control polygon:
<img width="877" alt="image" src="https://github.com/elalish/manifold/assets/47059882/b7cc8382-90d2-4628-b05f-5082f9cf6b37">
And smoothened result:
<img width="845" alt="image" src="https://github.com/elalish/manifold/assets/47059882/384b0555-f61f-46c9-9279-38adc5d97659">

Do you think your approach could be used for such modelling? 

Can you point me to the code section to understand how to define `halfedgeTangent` vectors?

**Comment by elalish** [comment]
Perhaps not traditional documentation, but I have this blog [post](https://elalish.blogspot.com/2022/03/smoothing-triangle-meshes.html). My approach is quite a bit different than subD, so it'll have different pros and cons. And I need to add quad support, which it doesn't have yet. But yes, the goal is to enable this kind of modeling.

**Comment by Niels-IO** [comment]
Thanks for the link. I have read it already, but I will go through the code again.

It would be awesome if Manifold could support such an approach! Thanks for taking the time to answer and creating this library!
