### ISSUE TITLE
`__xor__` and `operator^` are not a XOR op, rather an AND op

### ISSUE THREAD

**Issue by wrongbad** [elalish/manifold#645]
I understand it may be too late to change this, but I find it very counter-intuitive that you need to type XOR (^) when you mean AND (&).

I guess the use case for a real XOR op is pretty slim, but it would be even more confusing how to add it to the API.

**Comment by pca006132** [comment]
I think the intention is to treat `^` as $\wedge$, which does mean AND. But I agree this can be confusing to users.
If you are building programs on top of this, you can create a simple wrapper type that expose the operators you want.

**Comment by elalish** [comment]
Yeah, I'm thinking of `+` as union (OR), `-` as difference (AND NOT) and `^` as intersection (AND), so following more set notation than binary notation.
