### ISSUE TITLE
Number of SDF evaluations

### ISSUE THREAD

**Issue by Niels-IO** [elalish/manifold#652]
Hi, 

I just wanted to double-check that the behavior of the SDF generation is expected.
I noticed that the SDF is evaluated quite often. In this example of a simple sphere in a 2x2x2 box with resolution 0.1, the SDF is evaluated 170368 times.
```javascript
const { vec3, } = glMatrix;


function sdfSphere(p, r) {
  return vec3.length(p) - r;
}

const period = 1;
const box = {
  min: vec3.fromValues(-period, -period, -period),
  max: vec3.fromValues(period, period, period),
};

let numberOfEvaluations = 0
const sdf = Manifold.levelSet(
  (p) => {
    
    numberOfEvaluations++
   
    return -1 * sdfSphere(p, 1); 
  },
  box,
  .1
);
console.log({numberOfEvaluations})
const result = sdf
```

I tried to understand where this might come from, and maybe it is due to the evaluation of the neighboring grid cells here:
https://github.com/elalish/manifold/blob/eba866d266f1954f81211c71d9f5329477606e5e/src/sdf/src/sdf.cpp#L175

Is there a chance to optimize this by caching the distance value and try to retrieve it before evaluating again?

**Comment by pca006132** [comment]
We should switch to the implementation in https://github.com/elalish/manifold/pull/598, and it should fix this problem.

**Comment by pca006132** [comment]
closing as we now track the SDF update in #655.

**Comment by elalish** [comment]
And regardless of batching, SDF is O(n) where n is the number of grid vertices. So it scales up fast with increasing resolution. You can think of it (very roughly) as O(n^1.5) if n is the number of output triangles.
