### ISSUE TITLE
python cleanup

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#657]
- [x] Add and cleanup documentation for every function and type.
- [x] Name every parameter.
- [x] Generate python stub file.
- [x] Use numpy when possible. (#656)
- [x] Improve auto casting.

**Comment by wrongbad** [comment]
Another thing to note: improve auto casting removes the need for many lambda wrappers, and we could just pass the c++ apis directly to nanobind, to reduce the amount of code to maintain.

**Comment by wrongbad** [comment]
The maintenance burden for doc-strings is quite frustrating right now, with quantity and formatting being challenges.

I'm considering generating doc-strings [like this](https://stackoverflow.com/questions/34896122/how-to-avoid-redundancy-between-c-and-boostpython-docs). Though I would avoid the in-place substitution, and instead have placeholder reference string variables in an auto-generated header-file so the manual source doesn't mix with auto source. We could of course keep a few manual doc-strings where the python API diverges, but ~90% would be cleaned up I'd guess.

**Comment by pca006132** [comment]
We can also ditch the docstring in nanobind, and put the docstring in the generated stub file instead. One inconvenience will be users being unable to get the docstring from help, but not sure if this is commonly used...

**Comment by elalish** [comment]
Yes, generating doc-strings would be amazing! Bonus points if the system can be somehow extended to do the TS declarations too.

**Comment by wrongbad** [comment]
I briefly looked at the bindings/wasm folder. I think I may not be the right person to extend the auto-gen to JS/TS. But I'm sure there's a way.

**Comment by zalo** [comment]
I wrote a similar script to auto-generate bindings and typescript annotations for [mujoco_wasm](https://github.com/zalo/mujoco_wasm):
https://github.com/zalo/mujoco_wasm/blob/main/dist/mujoco_wasm.d.ts
https://github.com/zalo/mujoco_wasm/blob/main/src/main.genned.cc
https://github.com/zalo/mujoco_wasm/blob/main/src/parse_mjxmacro.py

The input/output types to manifold might be a bit too fancy for easy auto-generation of all the bindings (?), but I might be able to take a look for the typescript…

**Comment by elalish** [comment]
Thanks @zalo! Yeah, just keeping the TS docstrings automatically up-to-date would be huge, and conveniently, they're in the same format as the C++ ones, so that at least is simpler than for the Python.

**Comment by pca006132** [comment]
Thanks @wrongbad!
