### ISSUE TITLE
Mesh Simplification is incomplete after one pass

### ISSUE THREAD

**Issue by zalo** [elalish/manifold#675]
@elalish It seems like there's room for additional simplification after one pass; perhaps topology should be simplified until no changes are made?

```py
    general_offset = nonConvex.minkowski_sum(nonConvex.scale([0.5, 0.5, 0.5]))
    for i in range(5):
        save_mesh(general_offset, "general_offset_"+str(i), "stl")
        general_offset = general_offset.as_original()
```

Pass 0:
![image](https://github.com/elalish/manifold/assets/174475/a376aa1d-bbe5-4d5c-a076-524061ccc758)

Pass 1:
![image](https://github.com/elalish/manifold/assets/174475/5231829e-d43a-4fda-8eb3-2538a825eb8d)

Pass 2:
![image](https://github.com/elalish/manifold/assets/174475/af8e8ffc-4adb-4c8e-ba7d-92089de86e6b)

**Comment by elalish** [comment]
Yeah, that's probably a good idea for a stand-alone `Simplify` method - the internal one is aimed more at being fast dealing with what a single Boolean op creates.

**Comment by pca006132** [comment]
This is due to the order in which we perform edge collapses. We currently only do one pass over the list of halfedges in the order in the vector, but collapsing a halfedge with index `i` can cause halfedge `j < i` to be eligible for further simplification. Ideally we should have some kind of a worklist/set, when an edge is collapsed we check its neighbors to discover edges that can be further simplified. A worklist will be more efficient when the number of edges require collapsing is low (comparing with the total number of edges). I think this can combine with the optimization we mention in #679, i.e. only look for edge collapses among the newly-created verts in a Boolean, and will *probably* be faster than the current one we have.

**Comment by elalish** [comment]
Yeah, agreed. Currently `EdgeCollapse` is recursively checking neighboring edges for potential collapse, but I may be missing some cases.

**Comment by zalo** [comment]
Another interesting wrinkle... the slivers left over from some of the Minkowski operations appear to be cleaned up by the simplifications in `asOriginal()`, which also changes the Genus:

Before (Genus 4):
![image](https://github.com/elalish/manifold/assets/174475/8e8929b2-e524-470b-a48c-921efd12527c)

After calling `as_original()` 10 times (settled on Genus 5 after the first call):
![image](https://github.com/elalish/manifold/assets/174475/15585a9d-68e5-47b3-a253-5a615c5982f1)


Also worth noting the nearby triangle that is _not_ getting simplified...

**Comment by pca006132** [comment]
Wonder what the black thing in your first photo is. Is this a bug in our boolean impl? And yeah, the lump of triangles not being simplified at the end is also interesting.

**Comment by elalish** [comment]
I would guess the black thing is a thin, disconnected mesh that's likely responsible for the genus being 1 low (an extra separate mesh will do that). On a second pass, I'm guessing it got simplified down to nothing.

**Comment by zalo** [comment]
Yep; that’s right!  This is the same bug that was seen with Offset with the sliver meshes.

Simplify can often eliminate them (but not always).

**Comment by yxdragon** [comment]
is there any method to simplify mesh to polyhedron? (list of polygons, not only tri_verts, and tri_faces)

**Comment by yxdragon** [comment]
I got the face_id, I want a structure just like mesh. vert is n x 3, but faces is 2d list. not tri_face. I had got the faces id, so Is there a simple method to produce the face list? or need I do some geometry analysis? (I just deal with face without holes)

**Comment by pca006132** [comment]
Just [`triVerts`](https://manifoldcad.org/docs/html/structmanifold_1_1_mesh_g_l.html#afe0601a32ce917d3324b430a34f5d118). It is a flattened list of vertex IDs, `[3*i, 3*i + 1, 3*i+2]` defines a face.

**Comment by yxdragon** [comment]
```python
import manifold3d as mfd
cube = mfd.Manifold.cube((1,1,1))
mesh = cube.to_mesh()


out:
mesh.vert_properties
array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 1.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]], dtype=float32)
mesh.tri_verts
array([[1, 0, 4],
       [2, 4, 0],
       [1, 3, 0],
       [3, 1, 5],
       [3, 2, 0],
       [3, 7, 2],
       [5, 4, 6],
       [5, 1, 4],
       [6, 4, 2],
       [7, 6, 2],
       [7, 3, 5],
       [7, 5, 6]], dtype=int32)
mesh.face_id
[0, 1, 2, 3, 2, 5, 6, 0, 1, 5, 3, 6]
```
I want to trans the tri-mesh to polyhedron. (for a cube, I need 4 index to describe a face)
the face_id is the tri_verts's group id, but I need to merge the same group to polygon.

**Comment by elalish** [comment]
That's right, you'll need to merge them back into a polygon(s) by removing interior edges. Best you do that yourself, since naively they may produce concave polygons or polygons with holes, which you may want to avoid.

**Comment by yxdragon** [comment]
ok, I will process it myself. but is there an simple method to get the face polygon, when assuming the mesh is convex.

**Comment by elalish** [comment]
Lots of ways - e.g. find the half edges without pairs and assemble them into a loop.

**Comment by pca006132** [comment]
@elalish if you can verify if this is fixed or not, we can close this issue.

**Comment by elalish** [comment]
Fixed by #894 - `SimplifyTopology` now runs in a loop until it can't find anything to collapse.

**Comment by zalo** [comment]
This might be an interesting time to consider the Offset and Minkowski operations again… I think a great number of the failure cases of the Minkowski algorithm will be fixed/helped by the improved precision and improved simplification heuristic…

https://github.com/elalish/manifold/pull/666
https://github.com/elalish/manifold/pull/669

**Comment by elalish** [comment]
Yeah, certainly worth a look. We've got a bunch of breaking changes to close out for v3.0, but if you'd like to take another look, that would be great.

**Comment by zalo** [comment]
As an aside from https://github.com/elalish/manifold/pull/666#issuecomment-2797778354 , It seems like there is still some benefit to running `as_original()` several times in sequence.... 
Perhaps steps other than `SimplifyTopology` are contributing to the simplification?

Here are some example .stl's with the simplification run 0, 1, and 2 times...
[nasty_gear_simplified_0.stl.txt](https://github.com/user-attachments/files/19712915/nasty_gear_simplified_0.stl.txt)
[nasty_gear_simplified_1.stl.txt](https://github.com/user-attachments/files/19712913/nasty_gear_simplified_1.stl.txt)
[nasty_gear_simplified_2.stl.txt](https://github.com/user-attachments/files/19712914/nasty_gear_simplified_2.stl.txt)

**Comment by elalish** [comment]
I'm hoping #1217 will help with this.
