### ISSUE TITLE
2D batch union is slow

### ISSUE THREAD

**Issue by briansturgill** [elalish/manifold#695]
The python API (and really the C++ API) does not allow the creation of 2D objects without going
through a Union. It says this is a protective measure in the source code.
This is particularly odd because the Warp method allows the creation of invalid 2D objects but doesn't check.
This forces end users to have slow creation of 2D objects that they make.
In my case, it will mean I'll need to ship a forked version of Manifold to get proper speed.
I really think a constructor without the Union check is a good idea.

Regardless, I need to make two heavily used 2D objects at the C++ level: Ellipse and RoundedRectangle
As these are commonly used, would you like me to make a PR adding these to CrossSection and the Python API?

**Comment by pca006132** [comment]
The reason for warp having no check is because we have no way of implementing it right now, we want to perform checks on it.

Do you have specific examples in which the 2D union is too slow? I think we can do multithreaded union, we just don't have examples that show that it is so slow and requires multithreading.

**Comment by geoffder** [comment]
I'd also add, are these usually actually aribitrary shapes, or mostly simple shapes (e.g. triangles, rounded rectangles, and ellipses) of different dimensions? You could make a base one for each and simply use `Scale` to create new ones, avoiding another union. Also for ellipses, you can scale circles, no need to use the polygonal path constructor.

**Comment by briansturgill** [comment]
@geoffder Yes, I think you've solved it... fortunately users usually use the default number of segments, or maybe one
more. I don't need to make C++ Ellipse or RoundedRectangle.
I can keep a cache by segment number of a "unit" shape. Then things will be fast enough.

**Comment by briansturgill** [comment]
Ok, I'm going to close this... @geoffder 's solution seems to have all the bases covered. The overhead only comes into
play if you're making like 50 or more. And really, @geoffder 's solution is probably more efficient that what I originally planned. Certainly it is more efficient in the case of an ellipse... 50 sets of trig calls vs only 1... yeah, I'll take that.

**Comment by briansturgill** [comment]
Ok, I'm going to close this... @geoffder 's solution seems to have all the bases covered. The overhead only comes into
play if you're making like 50 or more. And really, @geoffder 's solution is probably more efficient that what I originally planned. Certainly it is more efficient in the case of an ellipse... 50 sets of trig calls vs only 1... yeah, I'll take that.
