### ISSUE TITLE
Serious bug in Python API

### ISSUE THREAD

**Issue by briansturgill** [elalish/manifold#698]
I discovered this while trying to add CS::compose to the API.
It appears that the API sometimes deallocates memory it shouldn't.
I suspect it has something to do with the shared paths in CrossSection (though it happens in Manifold too).
Someone that understands shared_paths() and nanobind needs to look at this.
(I don't understand shared_paths and barely understand nanobind.)
I spent yesterday reading nanobind and tried using nb::rv_policy::copy, but that did not fix the problem.

For CrossSection
```python
from manifold3d import *

c = CrossSection.circle(1)
#c = CrossSection.square(1)
print(c.num_vert())
c1 = c.translate((1, 0))
print(c1.num_vert())
h = CrossSection.batch_hull([c, c1])
print(h.num_vert())
# This next segmentation faults for c1 and c.
# 'compose' (which I was adding to manifold3d.cpp) fails in the exact same way.
print(c1.num_vert())

# I tried adding nb::rv_policy::copy, to all members that return
# a CrossSection in manifold3d.cpp... didn't fix the problem.
```

For Manifold:
```python
from manifold3d import *

c = Manifold.cylinder(1, 1)
print(c.num_vert())
c1 = c.translate((1, 0, 0))
print(c1.num_vert())
m = Manifold.compose([c, c1])
print(m.num_vert())
# This next segmentation faults for c1 and c.
# 'compose' (which I was adding) fails in the exact same way.
print(c.num_vert())
```

**Comment by pca006132** [comment]
I just checked, updating nanobind to v1.8.0 seems to fix the issue. I guess this is a nanobind issue.
