### ISSUE TITLE
header file naming/directory structure

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#701]
We want to avoid conflicting with header files from other packages.

**Comment by pca006132** [comment]
https://github.com/elalish/manifold/pull/901#issuecomment-2295314295

@hzeller what do you think if we put all headers inside the `manifold` subdirectory, and access them as `#include "manifold/xxx.h"`?

**Comment by hzeller** [comment]
yes, I think that would be good. That way, it is easy to immediately see where headers are coming from and there are no conflicts.
