### ISSUE TITLE
mesh id handling

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#702]
See #678 for discussion. Basically:

1. Use zero as a special mesh ID. `IncrementMeshIDs` will only remap non-zero IDs. Constructors automatically assign mesh ID zero. This allows coplanar triangles to be collapsed by default unless explicitly opt-out.
2. Allow `AsOriginal(id)` to take an optional parameter to specify the ID to apply to. This allows preserving the ID zero.

**Comment by onlynadeem** [comment]
a system or framework related to mesh generation or manipulation, likely in the context of computer graphics or computational geometry and Handling Co-planar Triangles by Default-
The design allows co-planar triangles to be collapsed by default unless explicitly opted out. This can be a useful feature for simplifying geometry or optimizing mesh data. 
`class Mesh:
    def __init__(self):
        self.vertices = []  # List of vertices
        self.triangles = []  # List of triangles (each triangle represented by indices of vertices)
        self.mesh_id_map = {}  # Dictionary to map old IDs to new IDs during IncrementMeshIDs

    def IncrementMeshIDs(self):
        self.mesh_id_map.clear()  # Clear the ID map
        new_id = 1  # Start with 1 to avoid zero as a regular ID
        for vertex_id in range(len(self.vertices)):
            self.mesh_id_map[vertex_id] = new_id
            new_id += 1

        # Increment non-zero mesh IDs in triangles
        for i in range(len(self.triangles)):
            for j in range(3):
                vertex_id = self.triangles[i][j]
                if vertex_id != 0:
                    self.triangles[i][j] = self.mesh_id_map[vertex_id]

    def AsOriginal(self, original_id=0):
        # Apply the original ID (default to 0 if not specified) to vertices or triangles as needed
        # This allows preserving ID zero or applying a specific ID during certain operations
        pass  # Implementation depends on how you want to handle this

    def CollapseCoplanarTriangles(self, opt_out=False):
        # Detect and collapse coplanar triangles by default, unless explicitly opted out
        if not opt_out:
            # Implement coplanar triangle collapsing logic
            pass
        else:
            # Preserve coplanar triangles based on user opt-out preference
            pass
`

**Comment by pca006132** [comment]
@onlynadeem what is this? our project is not a python project, and even if it is a python project you are leaving so much implementation details. Maybe you can have a look at the code and submit a PR for your changes if you are interested in working on it.

**Comment by elalish** [comment]
Is this GSOC-related?

**Comment by onlynadeem** [comment]
This is completely related and I am a beginner in this field and I want to learn to contribute in open source.

**Comment by elalish** [comment]
Sorry @onlynadeem, we're new to GSoC this year too. I'm glad to hear you're interested in our project! Perhaps you can share a bit of what makes this project interesting to you? Any idea how you might like to contribute?

**Comment by elalish** [comment]
I'm going to close this for now as it looks longer-term. Let's continue in the discussion, #678.
