### ISSUE TITLE
manifold3d: 2.3.1 sdist fails to build

### ISSUE THREAD

**Issue by cjmayo** [elalish/manifold#706]
When building https://files.pythonhosted.org/packages/ad/c0/217cfeef531b94727408b16d0085342559b0143a5942235a8db36dd1fbf2/manifold3d-2.3.1.tar.gz:

```
CMake Error at bindings/python/third_party/nanobind/CMakeLists.txt:34 (message):
  The nanobind dependencies are missing! You probably did not clone the
  project with --recursive.  It is possible to recover by invoking

  $ git submodule update --init --recursive
```

output by nanobind:

```
if (NOT IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/ext/robin_map/include")
  message(FATAL_ERROR "The nanobind dependencies are missing! "
    "You probably did not clone the project with --recursive. It is possible to recover "
    "by invoking\n$ git submodule update --init --recursive")
endif()
```

robin-map is not included in the sdist.

I am installing from a Gentoo Linux ebuild, but only using normal Python package installation code with scikit-build-core. It is building in a sandbox without network access.

**Comment by pca006132** [comment]
perhaps for some reason nanobind is not added in the sdist, will look into it later

**Comment by pca006132** [comment]
btw FYI you can build the sdist locally by
```
python -m build --sdist
```
if you have https://build.pypa.io/en/stable/# installed.
