### ISSUE TITLE
API Documentation link in README does not exist

### ISSUE THREAD

**Issue by jalexvig** [elalish/manifold#737]
As title says, the link to the api docs doesn't work. Are they available somewhere?

**Comment by pca006132** [comment]
for some reason modules.html disappeared, for now you can use https://manifoldcad.org/docs/html/

@elalish should we change the url or somehow modify doxygen configuration?

**Comment by elalish** [comment]
Yeah, super weird - I'm guessing there's a new version of doxygen that changed things? Looks like Modules was replaced by Topics? Also, the top page is using the Python bindings README instead of the main README, which is odd.
