### ISSUE TITLE
Better documentation for FillRule

### ISSUE THREAD

**Issue by briansturgill** [elalish/manifold#750]
Straightening this out will require breaking changes.

Two `CrossSection` constructors have a `FillRule` parameter and this is used in the single object union.
In all other instances, the `FillRule` is hard-coded to `FillRule.Positive`.
Thus, even though all FillRules are listed, only FillRule.Positive can actually be used.

In Clipper2 the 'FillRule' is used only in booleans and other clipping functions.
There is no way to provide this information in Manifold's 2d API.
Additionally, the odd use of +, -, and ^ for large, expensive operations makes solving this even harder.

One idea would be to require the use of FillRule.Positive. The FillRule parameter would eventually go
away and would throw an error in the meantime if some other FillRule was used.
This probably breaks the least existing code, but is also the least flexible.

I want to raise the caveat that  FillRule.EvenOdd requires no knowledge of winding on the part of end users
(it all gets sorted out automatically). That was my original plan for use in Piecad, though
I have ways around this if needed.

A second idea is to have a globally set a FillRule variable that is then used by all functions.
Similar to how OpenSCAD uses $fn.
This maintains flexibility, while breaking very little existing code.
I'm not sure what Manifold policy is for global static vars.
Enums (ie. FillRule) are allowed to have static variables. Perhaps it could go there?

A third idea is to go through each 2D call and add the ability to set FillRule.
For +, - and ^ one could default to FillRule.Positive and corresponding union/subtract/intersect functions if you
want to use something other than FillRule.Positive.
This option best matches Clipper's idea of how things should work.

I guess I favor the second option. I'd like to use FillRule.EvenOdd if I can.

I'll gladly do a PR for this, but a direction needs to be set first.

**Comment by geoffder** [comment]
The fill rule parameter is only exposed in the constructors intentionally, as once the initial "cleanup" union is performed on user provided paths, all winding thereafter is positive.

**Comment by elalish** [comment]
Lots of confidence in this title... would you mind providing an example of what is broken, i.e. a returned vs expected result?

EvenOdd loses winding direction information and results lots of "kissing" polygons, which is not terribly helpful for solid geometry.

**Comment by pca006132** [comment]
In my understanding, everything in manifold is done in `Positive` fill rule. The constructor is just for users to convert their polygons using alternate fill rules into `Positive`. I think as long as the representation is consistent, the fill rule used for boolean operation should not matter?

Maybe we should document this better though, e.g. the result of `ToPolygons` is `Positive`.

**Comment by pca006132** [comment]
You can have a look at the winding number definition, winding number <= 0 is a hole when you use positive fill rule.

>  Can interior contours contain interior contours (without an intervening hole)?

Yes, though I think in the output we just collapse winding numbers to either 1 and 0? Not sure about that.

**Comment by pca006132** [comment]
btw changing the title as this seems to be only affecting documentation

**Comment by geoffder** [comment]
> > Can interior contours contain interior contours (without an intervening hole)?
> 
> Yes, though I think in the output we just collapse winding numbers to either 1 and 0? Not sure about that.

Contours (positive winding) in contours and holes (negative winding) in holes (without the other between) are just unioned away. Like adding a smaller circle to a bigger one.

**Comment by elalish** [comment]
@briansturgill it sounds like some more documentation of what a winding number is might help here. Check out https://en.wikipedia.org/wiki/Point_in_polygon for examples. This is why pasting images into issues like this is so critical. The purpose of winding number is exactly to convert overlapping polygons into non-overlapping polygons. Information is always lost in this process, but EvenOdd loses different information than Positive.

**Comment by briansturgill** [comment]
From Clipper2 docs:
Even-Odd: Only odd numbered sub-regions are filled
Non-Zero: Only non-zero sub-regions are filled
Positive: Only sub-regions with winding counts > 0 are filled
Negative: Only sub-regions with winding counts < 0 are filled
and then there is (https://en.wikipedia.org/wiki/Nonzero-rule):
"If the total winding number is zero, P is outside C; otherwise, it is inside."

What, specifically is the difference between non-zero and positive?
They look to be exactly the same to me.

**Comment by briansturgill** [comment]
Yet there is definitely some difference, from Clipper2 source:

```C++
//nb: SVG only supports fill rules NonZero and EvenOdd
  //    so while we can clip using Positive and Negative
  //    we can't displaying these paths accurately in SVG
  //    without (safely) changing the fill rule

  inline void SvgAddSubject(SvgWriter& svg, const PathsD& path, FillRule fillrule)
  {
    if (svg.Fill_Rule() == FillRule::Positive ||
      svg.Fill_Rule() == FillRule::Negative)
    {
      svg.AddPaths(path, false, fillrule, 0x0, subj_stroke_clr, 0.8, false);
      PathsD tmp = Union(path, svg.Fill_Rule());
      svg.AddPaths(tmp, false, fillrule, subj_brush_clr, subj_stroke_clr, 0.8, false);
    } 
    else
      svg.AddPaths(path, false, fillrule, subj_brush_clr, subj_stroke_clr, 0.8, false);
  }
```

**Comment by briansturgill** [comment]
OK, I apparently have no understanding of non-zero whatsoever.
But I think I really do understand Positive now.
Here's a picture I found:
![image](https://github.com/elalish/manifold/assets/7350143/8208eda1-7383-4565-b4ca-04e172671fea)

**Comment by elalish** [comment]
That's an excellent picture of how winding numbers work; do you understand now? I'd be happy to put a link to it in our docs if you have one.

**Comment by briansturgill** [comment]
@elalish https://image.slidesharecdn.com/cg-surfacedetectionilluminationmodelssurface-renderingmodels-course9-111015013406-phpapp01/75/cg-opengl-surface-detectionilluminationrendering-modelscourse-9-9-2048.jpg?cb=1668135447
Don't know how permanent that like will be though (it was part of a slide deck).
Here's another source: https://www.flipcode.com/archives/article_tesselating_windingrules.gif

**Comment by elalish** [comment]
First off, if you draw a valid polygon, it doesn't matter because all fill rules have the same result. The only time fill rule matters is when your polygon has winding numbers that are not just zero and one. Since CCW is positive, a CW poly inside of a CCW poly is always a hole. And yes, they can be nested in an alternating way, again with no difference from fill rule. That's why we apply fill rule on construction: it turns invalid polygons into valid ones that have only winding numbers zero and one.

**Comment by elalish** [comment]
Oh, except negative. That's a weird one, since that makes CW positive.

**Comment by briansturgill** [comment]
@elalish OK, I'm having good success with very nested polygons and some 2d booleans thrown in using EvenOdd.
It works fine with my SVG export. But I'm still a bit apprehensive that it's because I tend to think in terms of EvenOdd.
Clipper2 needs to know the FillRule for booleans and other clipping. Why?
Surely that means that the ops must sometimes produce different results for different FillRules?

**Comment by briansturgill** [comment]
@elalish The only time I know that paths (ignore winding) are different between EvenOdd and Positive is that you can have holes in holes and shapes in shapes in Positive. However, Clipper (wisely) collapses them. In other words, winding aside, paths in Clipper are Positive and EvenOdd. Thus, in some sense we get lucky here?

**Comment by briansturgill** [comment]
@elalish OK, I'm a bit slow. But I get it now.   Because of the need to keep things extrudable, Clipper2 maintains
a set of paths that only have winding 0 and 1.  NonZero, EvenOdd and Positive all handle winding 0 and 1 in the exact
same way... this in my SVG output I could even use NonZero and get the same result.
Thanks for your patience!
