### ISSUE TITLE
wasm build problem 'Failed to resolve import "./built/manifold"'

### ISSUE THREAD

**Issue by Utopiah** [elalish/manifold#763]
Hi there, I built without problem but when I load the page after `npm i; npm run dev` I get 

```
[plugin:vite:import-analysis] Failed to resolve import "./built/manifold" from "worker.ts?type=module&worker_file". Does the file exist?
```

similar problem with `npm run build` getting

```
gltf-io.ts:18:49 - error TS2307: Cannot find module './public/manifold-encapsulated-types' or its corresponding type declarations.

18 import {Mesh as ManifoldMesh, MeshOptions} from './public/manifold-encapsulated-types';
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

worker.ts:21:20 - error TS2307: Cannot find module './built/manifold' or its corresponding type declarations.

21 import Module from './built/manifold';
                      ~~~~~~~~~~~~~~~~~~

worker.ts:24:73 - error TS2307: Cannot find module './public/manifold' or its corresponding type declarations.

24 import type {CrossSection, Manifold, ManifoldToplevel, Mesh, Vec3} from './public/manifold';
                                                                           ~~~~~~~~~~~~~~~~~~~

worker.ts:47:8 - error TS2339: Property 'setup' does not exist on type 'WorkerStatic'.

47 module.setup();
          ~~~~~
```

For a bit of context I run that from `manifold/bindings/wasm/examples` and I built in `manifold/build` before, same for `manifold/build/emsdk` which I then enabled via `emsdk_env.sh`.

The error happens in Firefox and Chromium and via the CLI.

**Comment by pca006132** [comment]
Can you show the commands you use to do the wasm build? cmake should copy them to the correct location after building.

**Comment by pca006132** [comment]
closing as it is impossible to follow up for now.

**Comment by Utopiah** [comment]
Looks like I need to follow https://github.com/elalish/manifold?tab=readme-ov-file#wasm first, right?

**Comment by pca006132** [comment]
yes

**Comment by Utopiah** [comment]
OK thanks will try that, apologies for the delayed answer other things came up and I honestly couldn't understand what "more" than `npm run build` I could share. Now I understand I missed a step, namely manifold build, then wasm build, then npm, trying now!

**Comment by pca006132** [comment]
if you are not familiar with c++, you can try the version published on npm, it is up-to-date and don't require you to build the wasm yourself.

**Comment by Utopiah** [comment]
Ah that's where my misunderstanding came from, I thought https://github.com/elalish/manifold/tree/master/bindings/wasm/examples specifically the `npm i` step would allow me to try without building it myself and pull from npm. But apparently not. Anyway now my local build works so that's fine, thanks again for the work and the help now!

<img width="1913" alt="image" src="https://github.com/elalish/manifold/assets/1076655/849a8f76-0650-4303-bfe9-cce04da02332">

Going to see how I can tinker with your engine and WebXR, ideally integrate more directly than an older prototype I've done https://twitter.com/utopiah/status/1311999553537802240 so that I "just" rely on threejs to display then code https://twitter.com/utopiah/status/1623571212017213440 e.g

```
const {cube, sphere} = Manifold;
const box = cube([100, 100, 100], true);
const ball = sphere(60, 100);
const result = box.subtract(ball);
```

then gestures for values e.g `60` in sphere as moving pinched fingers along a line.

**Comment by tetron432** [comment]
I've actually been having this problem too...I did 

```
git clone --recurse-submodules https://github.com/elalish/manifold.git
cd manifold
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON .. && make test/manifold_test
```

and then made a buildWASM directory and typed:

```
cd manifold
mkdir buildWASM
cd buildWASM
emcmake cmake -DCMAKE_BUILD_TYPE=MinSizeRel .. && emmake make node test/manifold_test.js
```
but then I get:

```
make: make
make: *** No targets specified and no makefile found.  Stop.
emmake: error: 'make' failed (returned 2)
```
Can anybody help me out with getting the WASM stuff set up?

**Comment by elalish** [comment]
I'm not sure you can combine these commands: `emmake make node test/manifold_test.js` - did you try
```
emmake make
node test/manifold_test.js
```

**Comment by elalish** [comment]
I'm not sure you can combine these commands: `emmake make node test/manifold_test.js` - did you try
```
emmake make
node test/manifold_test.js
```
