### ISSUE TITLE
Wrong pkg-config package name for Clipper2 dependency

### ISSUE THREAD

**Issue by t-paul** [elalish/manifold#766]
Looking at https://sources.debian.org/src/clipper/2.1.20201109-2/clipper.pc.in/ it seems that the package names should be just `clipper` even for version 2.1.

The [dependency definition](https://github.com/elalish/manifold/blob/master/manifoldDeps.cmake#L8) uses `Clipper2` which results in downloading the source on Debian with `libclipper-dev` installed. 

I have not yet check if other distributions may use different naming.

**Comment by t-paul** [comment]
Wait, is that the wrong Clipper2 code? https://github.com/AngusJohnson/Clipper2/blob/main/CPP/Clipper2.pc.cmakein does have the name `Clipper2`. So the Debian package is just some totally different code with the same name and version 2.

**Comment by pca006132** [comment]
interesting, is this an issue with debian?
