### ISSUE TITLE
README: clarify arity of mesh faces  

### ISSUE THREAD

**Issue by virtualritz** [elalish/manifold#78]
The 'Manifoldness' section of the Wiki talks about "triangle meshes".

Can this library work with meshes that contain faces of arity higher than three? 

If not this constraint should probably be mentioned in the first sentence of the README as it may save people looking for something that does (and not checking the Wiki) a lot of time. :)

Specifically: If I input a mesh made out of e.g. quads and perform a boolean operation, will the result mesh only contain triangles? Even in areas not affected by the boolean operation at all?

**Comment by elalish** [comment]
Indeed, it's not even possible to input data other than triangle [meshes](https://elalish.github.io/manifold/group___connections.html#structmanifold_1_1_mesh). Sorry to have dedicated years to a hard problem and given it away for free only to waste a few minutes of your time.

**Comment by virtualritz** [comment]
I'm not sure why you need to be passive aggressive. This was an earnest question/suggestion.

And it wouldn't have taken me minutes to find out. I would need to read source code or clone the repo build, try etc.

The fact that you seem to value your time more than that of others shouldn't give anyone pause but yourself. And I mean that in a very caring way.

**Comment by elalish** [comment]
I just linked you to the documentation that that says it. And for the record, your request was rudely stated. Happy to add docs though.

**Comment by virtualritz** [comment]
Kindly point me to what was rude about my request. I am not a native speaker.

It was an earnest question. Even though I found the wiki and that sentence I mentioned I opened this issue because this was not conclusive to me.

I would have just added the word 'triangle' to the 1st sentence of the README and opened a PR otherwise. But I wasn't sure.

**Comment by elalish** [comment]
> If not this constraint should probably be mentioned in the first sentence of the README as it may save people looking for something that does (and not checking the Wiki) a lot of time. :)

No problem, thanks for asking! If you just removed this line, it would have been much better. It implies the library is missing a fundamental feature that makes is useless for most people. Opening the PR is great. And trust me, there are far more glaring holes in my documentation at the moment; I'm still working on it.

**Comment by elalish** [comment]
@virtualritz After thinking about this some more, I think this library should work for quad meshes, depending on exactly how you want to use them. You'll need to write your own Import/Export functions, but that's going to be required for most specific use cases anyway. Since I save a [MeshRelation](https://elalish.github.io/manifold/classmanifold_1_1_manifold.html#a45ea90568e3c9072089e9854cd51a02f) that relates every triangle back to the original mesh & triangle it came from, it should be totally doable to triangulate your quad mesh, and then return the unmodified triangles back to quads as a post-process.
