### ISSUE TITLE
Manifold 2.4.5 release tar.gz is incomplete

### ISSUE THREAD

**Issue by LazyDodo** [elalish/manifold#783]
For blender we use the released tgz's of projects rather than cloning from git (for compliance reasons no code can be downloaded during a build, so git, git sub-modules and cmake's `FetchContent` just aren't an options for us), while building manifold's 2.4.5 release from https://github.com/elalish/manifold/releases/tag/v2.4.5 the `src/third_party/quickhull` folder isn't populated in the release tarball, causing the build to fail, we worked around this by copying in the required code during a pre-build step, but it be nice if this is fixed for future releases. 

this is a common problem in the automatically generated tar.gz's on github, other projects that have this issue generally manually upload a tar.gz for a release that has the all the sub modules populated

**Comment by elalish** [comment]
Hmm, so there's no way to make github populate the tarball submodules automatically? I'm not a huge fan of adding a manual step to our release process. Do you have any recommendations?

**Comment by elalish** [comment]
Should we use this? https://github.com/fabacab/git-archive-all.sh/blob/master/git-archive-all.sh

What's the best way to build this into our release automation?
