### ISSUE TITLE
Manifold Decompose doesn't preserve vertex properties

### ISSUE THREAD

**Issue by harmanpa** [elalish/manifold#786]
Calling Decompose on a Manifold made up of multiple disconnected meshes divides it into the separate Manifolds, but only containing vertex positions and not including other vertex properties if defined (unless I'm mistaken?).

**Comment by pca006132** [comment]
Probably a bug because decompose was there before vertex properties.

**Comment by harmanpa** [comment]
I'd be happy to try to implement and test a solution, do you know of anywhere in the code that also filters the vertex properties by index that might be similar @pca006132 ?

**Comment by elalish** [comment]
That would be excellent, thanks! It might help to look at [CompactProps](https://github.com/elalish/manifold/blob/master/src/manifold/src/sort.cpp#L353). 

If you get excited about cleaning up `Decompose`, there's another issue open about it: https://github.com/elalish/manifold/issues/745#issuecomment-1975078086. Ideally it shouldn't take too much to make `Manifold::Decompose` act more like [`CrossSection::Decompose`](https://github.com/elalish/manifold/blob/master/src/cross_section/src/cross_section.cpp#L457-L462)

**Comment by harmanpa** [comment]
It turned out that the only cause of this was that ```meshRelation_.numProp``` was not set in ```Manifold::Impl::GatherFaces``` while the vertProperties and properties were. However I've added a test and associated test utility (PR incoming) to check the properties in a resulting mesh match those set via SetProperties.
