### ISSUE TITLE
Modularize Manifold

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#803]
We've been getting more requests to have just core Manifold functionality (usually Booleans) with minimal dependencies (like Clipper, convex hulls, SDFs, etc). Our code is largely already partitioned this way, but I think we need to make some build flags to allow it to build modularly. Context: https://github.com/godotengine/godot/pull/91748#discussion_r1595679227

I'm curious if anyone knows any best practices for how to set this up? ASSIMP does a lot of this. @kintel perhaps this would also help for OpenSCAD? Curious if you have any thoughts.

**Comment by pca006132** [comment]
I feel that getting rid of Clipper can be quite painful. If we want to do something about clipper dependency, it will be a large breaking change and should be in the 3.0 plan.

**Comment by elalish** [comment]
Isn't clipper pretty much walled-off within `CrossSection`? I think we should be able to build Manifold without CrossSection if we want.

**Comment by elalish** [comment]
Also relevant to Blender integration: https://projects.blender.org/blender/blender/issues/120182#issuecomment-1170472

**Comment by pca006132** [comment]
ah, I was conflating it with glm, not something optional.

probably indicating I should sleep now :P

**Comment by kintel** [comment]
Some thou^H^H^H^Hramblings:
* Splitting up into feature sets is a bit of a slippery slope, as the number of possible permutations may explode, making testing very annoying. Can be mitigated by creating some automated test "matrixes". If there is a way of splitting into distinct sub-libraries, that might be preferable. Not sure how feasible that is.
* Some larger libraries do this pretty well (e.g. Qt, boost). They pretty much split into completely distinct libraries, possibly with some interdependencies.
* I kind of assume that people asking for this are mostly thinking in terms of dependencies, not features, but it would be nice if this is surfaced as feature selectors where the dependencies follow.
* In general, be prepared to spend some quality time with CMake :)
* Once you get sufficiently fed up with CMake, don't fall for the temptation to create a build system generator-generator script, as you'll eventually reinvent one of the 86 different build systems already created to solve this problem.
* Don't skimp on automated testing

A general comment, which would make sense to keep in mind. There seems to be a beginning movement to start packaging Manifold into Linux distros. This currently comes implicitly through the OpenSCAD distro packages, but may become strengthened by other OSS projects adopting manifold. This can be a bit of a pivotal moment, as you'll be held to API versioning/compatibility standards (if not you, the people ending up owning your packages). Good API design and semantic versioning gets you a long way here, but having multiple variants of the same binary library is a bad thing in this domain (unless there is some sort of ultimate build containing _everything_ that makes it into distros). Could be worth keeping in the back of your heads.

**Comment by pca006132** [comment]
Splitting into different packages should be simple. In fact we have that internally. But probably need less generic naming, as well as more tests to make sure some packages can be optional and things can still work.

**Comment by fire** [comment]
In Godot Engine engine's build we use these dependencies.

- manifold
- quickhull
- libcudacxx
- thrust
- thirdparty/glm

The only reasonable dependency we can remove is [thrust, libcudacxx].

**Comment by elalish** [comment]
As we've said before, Manifold has absolutely no dependence on `libcudacxx` anymore - we're not using that backend of Thrust at all. Is there a reason you're including it?

**Comment by fire** [comment]
In thrust:

All mentions of `#include <cuda/std/type_traits>` need to be converted to `#include <type_traits>`

You're right!

**Comment by fire** [comment]
I switched to the newest cccl (thrust, libcudacxx). https://github.com/nvidia/cccl and it seems to still requires manifold/thirdparty/cccl/libcudacxx.

Note: that https://github.com/NVIDIA/thrust has been archived on Mar 21, 2024

https://github.com/nvidia/thrust is archived.

**Comment by elalish** [comment]
Interesting, it does seem like they pulled `libcudacxx` deeper into Thrust at some point, probably in preparation for this CCCL thing it's become. Looks like we're not the only ones [displeased](https://github.com/NVIDIA/cccl/discussions/520#discussioncomment-7191121).

Maybe it's time to finally get off of Thrust - deprecation is a pretty good reason. @pca006132 already did a lot of work to make it easier for us to slot in a different parallel library underneath. @pca006132 Do you have any thoughts on what we should switch to? It's still hard for me to tell if PSTL encompasses TBB or vice versa, or if there's a yet more universal API we should be using.

**Comment by elalish** [comment]
Is there a better way for manifold to package our Thrust (or CCCL) dependency than as a submodule? Curious if there's best practices here...

**Comment by fire** [comment]
I like https://github.com/ingydotnet/git-subrepo for my projects as git submodules are difficult to use. Especially when for example manifold does manifold -> thrust -> imgui

**Comment by elalish** [comment]
I have to admit, the problems you're running into @fire (copying dependencies instead of pulling the submodule) makes me think the submodule approach is better. I don't want that giant pile of unused files in my repo any more than you do (which is what I get with git-subrepo). Thrust and CCCL still don't link in the actual CUDA code in our case, so all that `cub` and `libcudacxx` business doesn't actually end up in any of our binaries anyway. 

I don't really see what all the submodule hate is about anyway - I find them pretty great for managing large 3rd-party dependencies that I don't ever want to touch, besides to update to the latest release occasionally. I feel like everyone who dislikes them is using them when they control both repos. Am I missing something?

**Comment by fire** [comment]
My previous monorepo had like 40 submodules in various states of nesting. Your use cases may vary.

**Comment by pca006132** [comment]
I think we probably want a todo list for this one. `cross_section` is now optional, we plan to make `quickhull` optional as well (the PR was stalled, not sure what was blocking it), and `thrust` will be gone after #856 is merged. What else do we need? Remove `nanobind` and use the system version instead?

**Comment by fire** [comment]
> nanobind and use the system version

I am not familiar with nanobind. What does it do?

**Comment by pca006132** [comment]
python binding

**Comment by elalish** [comment]
Using system dependencies is always best if we can, though I doubt `nanobind` concerns the C++ users since they won't bother compiling the Python bindings anyway.

**Comment by elalish** [comment]
It does seem like #810 is pretty much the last thing. It mostly got delayed to v3, since it's a breaking change. But there's also been a bunch of discussion about whether my technique makes sense or not (relying on an optional linked-in library - `hull` - to implement an API that's always defined in the `manifold.h` header). I'd appreciate some more feedback from our C++ users on whether they accept that pattern or not.

**Comment by elalish** [comment]
Actually, we're considering just forking quickhull and pulling it in so we have more opportunity to parallelize it. Then #810 won't be necessary at all and we'll still be down a dependency.

**Comment by starseeker** [comment]
@elalish is there a discussion somewhere about reworking quickhull for inclusion in Manifold?  Want to make sure I'm subscribed if there is ;-)

**Comment by elalish** [comment]
Okay, quickhull dependency has been removed in #881 by pulling in our own version instead. With everything else addressed, I'm going to go ahead and close this as completed.
