### ISSUE TITLE
Build without exceptions

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#804]
We did a fair bit of work to ensure Manifold worked with exceptions disabled, but I'm concerned that may have been broken in the time since. First step is to make sure at least one of our CI builds is without exceptions. If that doesn't work, let's see how we can fix it. WDYT @pca006132?

**Comment by elalish** [comment]
For reference: https://github.com/godotengine/godot/pull/91748

**Comment by fire** [comment]
I am testing this in https://github.com/godotengine/godot/pull/94321

**Comment by elalish** [comment]
Thank you! We should have marked this as fixed by #833. Please re-open this if you find a problem.
