### ISSUE TITLE
gcc14 build failure

### ISSUE THREAD

**Issue by kintel** [elalish/manifold#814]
Manifold fails to build on gcc14 due to pulling a too old version of Clipper2.
The gcc issue was fixed in Clipper2 here: https://github.com/AngusJohnson/Clipper2/issues/823

Perhaps pull a specific git hash instead of the latest release?

This causes OpenSCAD to build on Windows after msys2 upgraded to gcc14.

**Comment by elalish** [comment]
Sounds like we should update our CI for gcc14 as well. Would you like to take a look at our matrix of builds and see if anything's missing as compared to OpenSCAD?

**Comment by kintel** [comment]
The main difference in this context is that we build using msys2 on Windows (which uses gcc14) while you build on Visual Studio: https://github.com/openscad/openscad/blob/master/.github/workflows/windows.yml

**Comment by kintel** [comment]
Not sure if it's more convenient to set up a gcc14 build on Linux - we haven't done that ourselves; the latest Ubuntu (24.04) comes with gcc13..

**Comment by pca006132** [comment]
I can probably setup nix to do that

**Comment by kintel** [comment]
Works again after #817.

**Comment by elalish** [comment]
Great, since we also have GCC14 in our CI now, I'm going to go ahead and close this.
