### ISSUE TITLE
Triangulation issue: Zebra

### ISSUE THREAD

**Issue by kintel** [elalish/manifold#831]
The following OpenSCAD script yields a bad Manifold triangulation:
```
$fn=24;
text(text="R",font="naturePro",size=5);
```

Note: This single font glyph consists of ~120 separate outlines with >62K vertices.

![out](https://github.com/elalish/manifold/assets/186094/07d80f57-ebbb-4737-af22-b2ae6a356f09)

Saving as SVG and reading that back yields the same issue (SVG attached for convenience).
![zebra](https://github.com/elalish/manifold/assets/186094/55114db9-c033-4c2d-935e-399a19152e2c)

The output after enabling `MANIFOLD_DEBUG` and `PolygonParams().processOverlaps = false`:
[zebra.cc.zip](https://github.com/user-attachments/files/15572598/zebra.cc.zip)

**Comment by elalish** [comment]
Still digging into what's wrong with this one, but I can see why it's a tough customer:
<img width="620" alt="image" src="https://github.com/elalish/manifold/assets/1649964/78b75733-d6f4-4b74-a408-25d4eb1a8f3a">
Amazingly this is *not* self-intersecting. However, this is also a great example of why the even-odd fill rule is such a disaster. Strictly positive fill rule would have made a much more sensible polygon.

**Comment by elalish** [comment]
@pca006132 Unfortunately `minimize_testcase` fails for this polygon - it returns a single inverted triangle, but as far as I can tell there's nothing with incorrect winding in the whole thing. I'd guess it's getting confused by the touching vertices.

**Comment by pca006132** [comment]
Make sense, that code was assuming non-intersecting (touching) polygons. Should try to make it more general one day...

**Comment by elalish** [comment]
Can we get a new polygon dump, since something must have changed compared to our existing tests?

**Comment by pca006132** [comment]
Yeah, I think it is probably related to precision.

**Comment by pca006132** [comment]
Trying to reproduce, so far I cannot get the result that @kintel got.

**Comment by pca006132** [comment]
cannot reproduce downstream anyway
