### ISSUE TITLE
use size_t whenever possible

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#854]
still a long way to go...

1. Halfedges
2. collider
3. Track performance changes as well

**Comment by pca006132** [comment]
Changes to public interface should be complete.

**Comment by elalish** [comment]
SG - shall we close this for now?

**Comment by pca006132** [comment]
Idk, there are still internal changes that we should do, just not something for v3.0 release.

**Comment by elalish** [comment]
Since this one is a bit vague and we've had a few discussions around it already, let's close this and add new ones that are more specific as needed.
