### ISSUE TITLE
perfTest project crash on 3rd iteration - VS - Windows x64

### ISSUE THREAD

**Issue by yetigit** [elalish/manifold#87]
don't know why ??
![image](https://user-images.githubusercontent.com/7016200/158659412-0f4bb127-b351-464d-a9fb-cd888d096549.png)

**Comment by elalish** [comment]
Those `k = 1` and `No intersection` lines you can basically think of like asserts (it's hard to actually throw from a GPU kernel, but you can print). Basically something happened that shouldn't internally, so I'd guess we're not getting what we expect from the compiler.

**Comment by elalish** [comment]
Best guess is this has been fixed in the meanwhile. Please open a new issue with repro steps if you see this again.
