### ISSUE TITLE
OpenSCAD fails to build without CrossSection: no member named ‘ToPolygons’

### ISSUE THREAD

**Issue by cjmayo** [elalish/manifold#889]
When attempting to build OpenSCAD against a copy of manifold built with MANIFOLD_CROSS_SECTION=OFF from #888:

```
openscad-48f4430b12c29a95ab89ffdd8307205d7189421c/src/geometry/manifold/ManifoldGeometry.cc: In member function ‘Polygon2d ManifoldGeometry::slice() const’:
openscad-48f4430b12c29a95ab89ffdd8307205d7189421c/src/geometry/manifold/ManifoldGeometry.cc:308:59: error: ‘class std::vector<std::vector<glm::vec<2, float, glm::packed_highp> > >’ has no member named ‘ToPolygons’
  308 |   return ManifoldUtils::polygonsToPolygon2d(cross_section.ToPolygons());
      |                                                           ^~~~~~~~~~
openscad-48f4430b12c29a95ab89ffdd8307205d7189421c/src/geometry/manifold/ManifoldGeometry.cc: In member function ‘Polygon2d ManifoldGeometry::project() const’:
openscad-48f4430b12c29a95ab89ffdd8307205d7189421c/src/geometry/manifold/ManifoldGeometry.cc:313:59: error: ‘class std::vector<std::vector<glm::vec<2, float, glm::packed_highp> > >’ has no member named ‘ToPolygons’
  313 |   return ManifoldUtils::polygonsToPolygon2d(cross_section.ToPolygons());
      |      
```

cross_section there is from `manifold_->Slice()` and `manifold_->Project()` respectively.

https://github.com/openscad/openscad/blob/8119ad428948833245c2df25102767c1a98346da/src/geometry/manifold/ManifoldGeometry.cc#L306-L314

Is that expected?

**Comment by elalish** [comment]
Yes, but it's probably just because that was written when CrossSection was more tightly coupled to Manifold. I would guess it would be pretty easy now to make OpenSCAD only use our `Polygons` interface instead of `CrossSection`.

**Comment by pca006132** [comment]
I think slice and project requires cross section support?

**Comment by elalish** [comment]
Not since #850.

**Comment by elalish** [comment]
However, for Project(), you'll want to run it through a non-zero fill rule (CrossSection did that automatically).

**Comment by pca006132** [comment]
> However, for Project(), you'll want to run it through a non-zero fill rule (CrossSection did that automatically).

Maybe we should add that to the documentation?

**Comment by elalish** [comment]
I did: https://manifoldcad.org/docs/html/classmanifold_1_1_manifold.html#a328657b69e9bbaaee148572ca314677c

**Comment by elalish** [comment]
One or the other. I'd guess you'd rather use your own clipper than our wrapper.

**Comment by nicman23** [comment]
@cjmayo did you make a patch for it?
