### ISSUE TITLE
Flake needs option to enable MeshIO

### ISSUE THREAD

**Issue by reinux** [elalish/manifold#909]
I turned on the `-DMANIFOLD_EXPORT=ON` cmake flag [in my own fork](https://github.com/reinux/manifold/blob/1ff1081ea472e200325d41080c61a50550bafc4a/flake.nix#L50) so that I can use it in VSCode Notebooks from C#/F#.

Unfortunately, I'm still pretty green with nix flakes, and I'm not aware of the idiomatic approach to making this optional.

At the same time, it appears that the libassimp dependency is already non-optional in the flake anyway, so maybe it makes sense to just have this turned on.

**Comment by pca006132** [comment]
True, apparently there is no way to add optional args to flakes without some ugly hack... I think enabling MeshIO by default is fine, but users should be aware that it is not as well-tested as other parts of the library.

**Comment by elalish** [comment]
Yeah, our meshIO is not amazing, especially since it ignores almost all properties. I wrote a better one for GLB export for TS. My original inclination was to only link Assimp in for our tests, but several users really wanted IO, even if it's a bit paltry. I suppose it's fine to include it as long as no one's concerned about the binary bloat of the Assimp dependency.

**Comment by reinux** [comment]
I think culturally NixOS users tend not to be too worried about binary size, so it might be all right. Relatively high disk usage is the price we pay for immutable and isolated packages.

But maybe it would be better to put it off for now until it's in a state that you're happy with?

**Comment by pca006132** [comment]
I think it is fine to put `MeshIO` in. If users are frustrated in the lack of features or performance issue with it, they can just submit PRs to improve it.

**Comment by elalish** [comment]
SG - we're working up to a v3.0 release here, hopefully in the next month or so. I don't believe we currently publish anything for nix, it's just in our CI, right? I'm happy to merge a PR for this any time - I'm unlikely to remember to ask when we're actually ready to release.

**Comment by reinux** [comment]
Cool, I'll make a PR. And yeah, aside from visibility and build caches, nix doesn't care too much whether something comes out of the official nix packages or from a repo, so publishing it for nix probably isn't *that* much of a priority.

Thanks!
