### ISSUE TITLE
Fix Windows CI

### ISSUE THREAD

**Issue by elalish** [elalish/manifold#910]
For some reason #895 caused our Windows CI to start inexplicably failing on two tests: `Polygon.Zebra` and `Polygon.Zebra3` with `Process exited with code 127`. It's a pretty opaque error, but 100% repro on Windows, 0% on all other platforms. For now we have a workaround - details in this [thread](https://github.com/elalish/manifold/pull/895#issuecomment-2323857439), but we should fix the root cause before release.

**Comment by weianweigan** [comment]
@elalish  I am a Windows user. After updating the master branch and compiling and running the tests, the zebra3 test did not pass as follows:
```powershell
PS D:\weigan\repos\manifold-csharp\build\bin\Release> manifold_test.exe --gtest_filter=Polygon.Zebra*
Note: Google Test filter = Polygon.Zebra*
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from Polygon
[ RUN      ] Polygon.Zebra1
[       OK ] Polygon.Zebra1 (6 ms)
[ RUN      ] Polygon.Zebra
[       OK ] Polygon.Zebra (1599 ms)
[ RUN      ] Polygon.Zebra3
unknown file: error: SEH exception with code 0xc00000fd thrown in the test body.
[  FAILED  ] Polygon.Zebra3 (1 ms)
[----------] 3 tests from Polygon (1606 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (1607 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Polygon.Zebra3
```
