### ISSUE TITLE
[wasm] support for passing property tolerance for constructing manifold

### ISSUE THREAD

**Issue by dsafa** [elalish/manifold#925]
I was looking at the c++ docs and I saw that there was a overload for [passing property tolerance](https://manifoldcad.org/docs/html/classmanifold_1_1_manifold.html#a4bc17f3828311b81bf61c34805501599) which isn't in the js binding. I can try adding it, are you good with that?

**Comment by pca006132** [comment]
sounds good

**Comment by elalish** [comment]
You know, normally I'd say certainly, but I'm actually in the middle of a change that's removing that. The property tolerances will be an input to their own function that explicitly creates faces, instead of doing it all the time internally, since it's a fairly slow operation.

**Comment by dsafa** [comment]
haha, sounds good. I'll close this issue then
