### ISSUE TITLE
Simplify kissing faces

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#926]
See https://github.com/elalish/manifold/discussions/923

**Comment by starseeker** [comment]
@elalish Per the discussion, should folks interested in this issue be keeping an eye on https://github.com/elalish/manifold/issues/289 instead?  Also, would it be useful to prepare some inputs that produce these "kissing faces" as test cases?

**Comment by elalish** [comment]
Yeah, let's direct this to #289. I think those test cases will be easy enough to generate. #289 has already been open for a couple years - given its scale I wouldn't be surprised if its open for more. I am really interested in trying it, but it will be quite complicated and will require a lot of work to make robust, not to mention the possibility that the algorithm I've sketched out might have some fundamental flaw. If anyone is interested in pushing the envelope on computational geometry, let me know! Two heads are better than one, especially for motivation.
