### ISSUE TITLE
Error when `slice`-ing the bottom face of a manifold

### ISSUE THREAD

**Issue by neilpa** [elalish/manifold#929]
It appears the [`slice` function doesn't work as advertised](https://github.com/elalish/manifold/blob/4760ba3a33edded2b619557a789b70b86a97cfc2/bindings/wasm/manifold-encapsulated-types.d.ts#L830-L838) for extracting the bottom faces of a manifold. I'm hitting an undefined error that I can reproduce with a trivial example on [manifoldcad.org](https://manifoldcad.org)

```js
const box = Manifold.cube(1)
console.log(box.boundingBox().min);
console.log(box.slice(0));
```

Produces

```
[
    0,
    0,
    0
]
TypeError: A[0] is undefined
```

Related, is there a way to use `slice` to extract the top faces?

> using a height equal to the top of the bounding box will return empty.

Assuming this bug gets resolved, I can work around it by mirroring and slicing the bottom, but that feels like a kludge.

**Comment by neilpa** [comment]
It actually appears `slice` doesn't work at all. I suspect something is broken with the WASM bindings. I get the same error with `Manifold.cube(1).slice(0.5)`.

I debugged this a bit, the failure is  [here in `polygons2vec`](https://github.com/elalish/manifold/blob/4760ba3a33edded2b619557a789b70b86a97cfc2/bindings/wasm/bindings.js#L54).

![Screen Shot 2024-09-15 at 8 59 00 AM](https://github.com/user-attachments/assets/0a4b1f15-7e5e-496e-8ede-94b164f9778e)

I've got limited WASM experience, but it looks like a WASM-bridged C++ object is getting passed to the function rather than an expected JS array?

![Screen Shot 2024-09-15 at 9 01 10 AM](https://github.com/user-attachments/assets/832a2924-004b-49a4-947f-0d8952a51283)

If I'm reading correctly, it's coming [directly from `Manifold._Slice`](https://github.com/elalish/manifold/blob/4760ba3a33edded2b619557a789b70b86a97cfc2/bindings/wasm/bindings.js#L287).

**Comment by elalish** [comment]
Thanks! Looks like we must be missing a WASM test example that uses slice. @pca006132 wasn't there a recent refactor of this? Maybe something got missed?

**Comment by neilpa** [comment]
I noticed `project` as the same problem as well. Seems like this is the culprit change - 85d71f5cef43d9b026bc67f9ddf9d64e7872a8e8

**Comment by elalish** [comment]
There must be something I don't understand here. I just tried 

```
const box = Manifold.cube(1)
const result = Manifold.extrude(box.slice(0), 0.1);
```
in ManifoldCAD.org and it worked just fine - made a thin box as expected. What is the bug?

**Comment by neilpa** [comment]
Weird. This works for me now too on manifoldcad.org. However, I double checked on my local build and I can still repro the issue w/out my changes #930.

![Screen Shot 2024-09-17 at 6 15 56 PM](https://github.com/user-attachments/assets/4ecb8ce7-f9ad-48eb-8a07-d93558b3c136)

**Comment by dsafa** [comment]
I don't know if this is intended, but the reason manifold.org is working is cause it seems to have to fixed code from the pr? at least I'm able to see the new example on there

![image](https://github.com/user-attachments/assets/1e6a2b47-15bf-4f2d-92ab-91a8dd6884a3)

**Comment by neilpa** [comment]
> I don't know if this is intended, but the reason manifold.org is working is cause it seems to have to fixed code from the pr?

Nope and that would do it. I’m guessing one of the CI actions on PRs is inadvertently deploying/updating manifoldcad.org

**Comment by pca006132** [comment]
Ha! This is a security issue.

https://github.com/elalish/manifold/blob/ced53e210972adee15edade7c7308fcf2777f707/.github/workflows/manifold.yml#L154-L161

I think we should only upload the artifact when it is triggered from the master branch.

**Comment by elalish** [comment]
Ha! Wow, that's not how I thought THAT worked. Besides, I didn't think uploading an artifact did anything - I thought only our deploy action that downloads said artifact and packs it into our Github pages deployment would actually put it on a server. I'm so confused...

**Comment by pca006132** [comment]
Well, uploading an artifact probably does nothing, but when you have a race condition and the deployment job is running on the master branch...

**Comment by elalish** [comment]
Oh, that's interesting. I feel like there's supposed to be a way to ensure you only get an artifact from your same job - am I crazy or did we mess that up?

**Comment by pca006132** [comment]
https://github.com/orgs/community/discussions/106300

Seems a bit complicated.
