### ISSUE TITLE
js bindings: CrossSection.toPolygons() return value doesn't match typescript type

### ISSUE THREAD

**Issue by dsafa** [elalish/manifold#943]
The points are objects of type {x,y} instead of an array [x,y] like the types indicate.
example: run this on the web example `console.log(CrossSection.square().toPolygons());`
output:
```
[
    [
        {
            "x": 0,
            "y": 0
        },
        {
            "x": 1,
            "y": 0
        },
        {
            "x": 1,
            "y": 1
        },
        {
            "x": 0,
            "y": 1
        }
    ]
]
```

expected:
```
[
    [
        [0,0],
        [1,0],
        [1,1],
        [0,1]
    ]
]
```

I can look into fixing it later if no one wants to fix it.

**Comment by elalish** [comment]
Thanks, good find. @pca006132 this makes me wonder if we should do any additional API changes here. We switched from `Mesh` vector-of-vec3` to `MeshGL` flat vectors. Should we do something similar with `Polygon`?

**Comment by pca006132** [comment]
Idk, what I am sure is we should double check binding APIs before we release v3.0 :P

**Comment by neilpa** [comment]
As part of #930 I started to write a bindings-specific test suite that could at least run some sanity checks. However, given the scope of the API surface, I didn't get very far. If I have time, I can revisit that change.
