### ISSUE TITLE
errors when compiling for iOS

### ISSUE THREAD

**Issue by wtholliday** [elalish/manifold#944]
I'm trying to compile manifold as an xcframework for iOS.

Doing this:

```
cmake -B build_ios -G Xcode -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=OS64
cmake --build build_ios --config Release
```

(I'm using this toolchain file https://github.com/leetal/ios-cmake)

I get various errors like:

```
manifold/src/collider/include/manifold/collider.h:287:39: error: implicit conversion loses integer
      precision: 'size_t' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32]
```

Probably can silence those warnings (though I'm lousy with CMake and `-DCMAKE_COMPILE_WARNING_AS_ERROR=OFF` didn't do anything), but might be good to fix the underlying thing.

**Comment by elalish** [comment]
Yeah, some of that is actually in process now. But we have a fair number of those warnings silenced already as they can get pretty pedantic.

**Comment by pca006132** [comment]
Probably need `-DCMAKE_CXX_FLAGS="-Wno-shorten-64-to-32"`.

**Comment by pca006132** [comment]
I had a look at this, there are simply too many changes required, and we have to change the internal halfedges to 64-bit which can affect performance and require further evaluation. I think for now the only way is to silence the warning.

**Comment by wtholliday** [comment]
@pca006132 what about adding casts in the code? Also that particular warning above can be fixed by changing the `int` to a `size_t` it seems.

**Comment by pca006132** [comment]
This requires a lot of changes. For each one it is simple, but there are many of them...
