### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by pca006132** [elalish/manifold#969]
A list of cleanup to do before v3.0.

- [x] https://github.com/elalish/manifold/blob/master/RELEASE_CHECKLIST.md
- [x] Cleanup `.vscode/launch.json`.
- [x] Move the public header install logic to the main cmake file?
- [x] Remove the single mesh file in `extras/Thingi10K/raw_meshes`.
- [ ] Organize `extras`, e.g. move things related to hull testing to its own folder, add readme to explain the use of each file.
- [x] `format.sh` format cmake.
- [x] Remove `.gitmodules`.
- [x] Update readme about the `clang-format` version requirement.
- [x] Workaround #944 by adding ignore flags.
- [ ] Try to make fuzzing work again.
- [x] Check the documentation to make sure things are up-to-date.

**Comment by starseeker** [comment]
For the formatting of cmake, did you have a preferred solution in mind?

**Comment by pca006132** [comment]
No, maybe https://github.com/cheshirekow/cmake_format? I haven't yet tried it though.

**Comment by pca006132** [comment]
@elalish for fuzzing, I encountered https://github.com/google/fuzztest/issues/1022, not sure how to fix it.

**Comment by starseeker** [comment]
@pca006132 It's not cleanup, but were we going to decide what to do about glm in the public headers et. al. prior to 3.0?  Didn't know if that should be added to the 3.0 milestone...

**Comment by pca006132** [comment]
Yes, but not sure if I should convert the discussion into issue, the discussion is very long and has multiple threads.

**Comment by elalish** [comment]
Yeah, 1) sounds like the right approach for v3.0. I'm comfortable crossing the 2) bridge when we come to it. We did a similar thing we when we built `MeshGL` parallel to `Mesh` without a breaking change - we can do that again if necessary. Unless someone has a great idea for a simple thing we should do right now, I'm going to ignore it.

**Comment by pca006132** [comment]
Currently, about half of our files in extras do not work:

1. `minimize_testcase.cpp` does not parse the current polygon dump format.
2. `perf_test_cgal.cpp` does not compile (we should remove it anyway)
3. `test_hull_performance.cpp` does not compile.

I'm thinking if we should fix these before the release, or it is fine to just leave them as is for now. These are just for our internal use only anyway.

**Comment by elalish** [comment]
Yeah, I wouldn't call anything in extras a priority. Might be good to remove `perf_test_cgal` at least so there's one less optional dependency to confuse people.

**Comment by elalish** [comment]
I'm going to call this done - we can come back and clean up extras and fuzzing after v3.0.
