### ISSUE TITLE
boolean problem

### ISSUE THREAD

**Issue by rob-rb** [elalish/manifold#974]
boolan subtraction creates a lot of non-manifold example in this example
[mesh_boolan.zip](https://github.com/user-attachments/files/17212138/mesh_boolan.zip)

**Comment by sloriot** [comment]
bool_mesh_1 is self-intersecting and its oriented inside-out. You can try with that fixed version of the mesh. 
[bool_mesh_1_fixed.obj.gz](https://github.com/user-attachments/files/17212397/bool_mesh_1_fixed.obj.gz)

**Comment by rob-rb** [comment]
thanks yes flipping mesh1 solved the issue
