### ISSUE TITLE
Update bindings

### ISSUE THREAD

**Issue by NickUfer** [elalish/manifold#979]
Commit 6cec951aede0fb9156c13f015a2568230931f74e added the option to create partial revolves to [Manifold::Revolve](https://github.com/elalish/manifold/blob/658d3e037a0a198b605fd99e496e84b1dd674a32/src/constructors.cpp#L293-L294). The C api function [manifold_revolve()](https://github.com/elalish/manifold/blob/658d3e037a0a198b605fd99e496e84b1dd674a32/bindings/c/include/manifold/manifoldc.h#L168-L169) wasn't updated to expose this new feature, probably to prevent breaking the API.
It would be great if we could fix this for the next major release.

**Comment by pca006132** [comment]
Yeah, we do plan to update the bindings. I think our bindings are a bit outdated, e.g. don't have `MeshGL64` support. We should start looking into updating our bindings after those major API updates.

**Comment by pca006132** [comment]
List of missing C binding functions I found:

- triangulation related functions
- tolerance related functions
- warp batch
- partial evolve

it will be great if some other users can tell us what else we are missing, as we are not the direct consumer of the C API and it is hard to figure out every missing pieces.

For python:

- `TriangulateIdx`

**Comment by elalish** [comment]
I found `setTolerance` was missing from our WASM bindings, so I'm fixing that, along with the OP's `manifold_revolve` update. The rest doesn't look like breaking changes, nor super high priority, so I'm okay with those coming after v3.0.
