### ISSUE TITLE
add centroid method to Manifold and CrossSection

### ISSUE THREAD

**Issue by yxdragon** [elalish/manifold#983]
```python
def volume(verts, faces):
    v1, v2, v3 = [verts[faces[:,i]] for i in (0,1,2)]
    vt = np.cross(v2-v1, v3-v1)
    return (vt * v1).sum()
    
def centroid(verts, faces):
    v1, v2, v3 = [verts[faces[:,i]] for i in (0,1,2)]
    vt = np.cross(v2-v1, v3-v1)
    w = (vt * v1).sum(axis=1);
    o = (v1 + v2 + v3) / 4
    o *= w[:,None]
    return o.sum(axis=0) / w.sum()
```

this is a numpy implements of centroid.
But the centroid counting is fast, but to_mesh cost the main time when there are large number of manifolds.
So I think Manifold and CrossSection should give a C+ implements.

**Comment by yxdragon** [comment]
i tested that Manifold.volume() is fast. does volume() call to_mesh()?

**Comment by pca006132** [comment]
It also evaluates the underlying csg tree. I'm thinking if the slowness you see is caused by overhead in our python binding code...

Which version are you using? Maybe you can try to compile from source and see if it performs better?

**Comment by elalish** [comment]
I'm confused - what is slow? Or what API is missing?

**Comment by yxdragon** [comment]
```python
import manifold3d as mfd

def volume(verts, faces):
    v1, v2, v3 = [verts[faces[:,i]] for i in (0,1,2)]
    vt = np.cross(v2-v1, v3-v1)
    return (vt * v1).sum()
    
def centroid(verts, faces):
    v1, v2, v3 = [verts[faces[:,i]] for i in (0,1,2)]
    vt = np.cross(v2-v1, v3-v1)
    w = (vt * v1).sum(axis=1);
    o = (v1 + v2 + v3) / 4
    o *= w[:,None]
    return o.sum(axis=0) / w.sum()

box = mfd.Manifold.cube((1,1,1))
sphere = mfd.Manifold.sphere(1, circular_segments=16)

from time import time

# it is so fast, so i think it just keep a operator tree, and processed when needed?
start = time()
spheres = [box ^ sphere for i in range(3000)]
print('bool:', time()-start)

start = time()
for i in spheres: i.to_mesh()
print('to_mesh:', time()-start)

# volume became fast after to_mesh. but slow without to_mesh
start = time()
for i in spheres: i.volume()
print('volume:', time()-start)
```

after more test, I found to_mesh or volume became slow after bool operator.
So I think the cost is rebuild mesh from csg tree? Or the operater just keep a tree, and be processed when needed?

**Comment by elalish** [comment]
That's right, our operations are all lazy, so you have to be careful to include a call that forces evaluation when you do timing. num_vert() is an easy one.

**Comment by yxdragon** [comment]
So this issue could be closed, It is my timing mistake. But I think it is also useful to implement centroid method for Manifold and CrossSection.

**Comment by elalish** [comment]
Okay, thanks. Feel free to add a C++ centroid method and expose it through our bindings.
