### ISSUE TITLE
Odd failure creating and unioning multiple cylinders

### ISSUE THREAD

**Issue by starseeker** [elalish/manifold#996]
In the process of simplifying down my test code for the performance regression (https://github.com/starseeker/manifold/blob/perf_test/extras/offset_test.cpp), I've hit an odd failure that I'm having trouble reproducing in isolation.  I'm running fine, and then I suddenly hit this error (enabling MANIFOLD_DEBUG doesn't seem to change anything):

```
Edge 333: 13254 vertices, 27144 triangles
Edges - manifold boolean op failure: Vec out of range
```

I've tried to dump the glb meshes producing this output, but something is wrong:  I can generate them, but for the Manifold generated by Cylinder all I'm getting is a mesh that contains 1 vertex:

```
./extras/convertFile cyl.glb 
1 vertices, 28 triangles
0 objects:
```

However, if I interrogate the cyl Manifold itself in the C++ code with methods like NumVert() and NumTri(), both the Manifold itself and a GetMeshGL version, there appears to be more data there:

Short Edge Cylinder counts (Manifold, pre bool): 16 vertices, 28 triangles
Short Edge Cylinder counts (GetMeshGL, pre bool) Manifold: 16 vertices, 28 triangles
Vec out of range
Short Edge Cylinder counts (GetMeshGL, post bool): 16 vertices, 28 triangles

Compared to the other Cylinders being generated this one is short (a little over 0.025) but if I try to create an isolated test with just the Cylinder call and a glb read of the other input mesh the test passes.  If I skip that one short cylinder the rest of the test runs to completion.

Am I using Cylinder incorrectly, or somehow mismanaging memory in such a way that I could be causing corruption?  I'm at a bit of a loss, particularly since things seem to complete without that individual cylinder but trying to isolate it for a test case isn't going very well...

**Comment by starseeker** [comment]
Additional context - running on Linux, specific invocation of the test from the build directory after building my perf_test branch with MANIFOLD_EXPORT=ON is:

```
./extras/offsetTest ../test/models/Generic_Twin_91.1.t0.glb
```

@elalish I'll boil things down more for the boolean complex test form, but ideally I'd like to know what I'm doing wrong rather than just punting and skipping the problem case...

**Comment by pca006132** [comment]
Weird, maybe try to compile and run with address sanitizer? Is something corrupted?

**Comment by elalish** [comment]
Yeah, ideally boil down that failure case to its own `TEST` as well. I agree that's quite strange. I'm guessing your 1-vert mesh is just due to the exporter collapsing verts? I wouldn't trust MeshIO/Assimp very much. I take it you've checked that your volumes are positive (CCW winding)?

**Comment by starseeker** [comment]
New data point - ran with valgrind (quite slow) and that didn't report anything. (Grr.)

**Comment by starseeker** [comment]
Is there a way to specify one test to run with manifold_test?

**Comment by starseeker** [comment]
Hmm - may have spotted a bug in my code.

**Comment by starseeker** [comment]
Ah - no, just a raw calculation instead of calling a method.  Phooey.

**Comment by starseeker** [comment]
I tried the Cylinder method in BRL-CAD in lieu of the custom code I was using and I occasionally get the Vec out of range error there as well.  Once the other test is in I'll have another go at boiling down a reproduction.

**Comment by starseeker** [comment]
Drilling in with the debugger, I'm seeing the following:

```
(gdb) print evec
$9 = {x = -0, y = -0, z = 0.025390625}
(gdb) print manifold::RotateUp(evec)
$10 = {x = {x = -nan(0x8000000000000), y = -nan(0x8000000000000), z = -nan(0x8000000000000)}, y = {
    x = -nan(0x8000000000000), y = -nan(0x8000000000000), z = -nan(0x8000000000000)}, z = {x = -nan(0x8000000000000), 
    y = -nan(0x8000000000000), z = -nan(0x8000000000000)}, w = {x = 0, y = 0, z = 0}}
```

**Comment by starseeker** [comment]
Looks like the problem is {0, 0, N} vectors?

**Comment by elalish** [comment]
Oh wow, all this comes down to a bad `RotateUp` implementation? Ugh, that's embarrassing. Oh well, I was planning to remove that anyway - linalg has something more general. Guess I should make a PR.

**Comment by starseeker** [comment]
@elalish In the spirit of laziness, would it be an option to have a Cylinder constructor in the Manifold API that accepts two input points and a radius and makes the cylinder between them?

**Comment by elalish** [comment]
No, you can do your own transform math - it's like two lines and I already put it in your example in #1000.

**Comment by starseeker** [comment]
I wasn't thinking for my case so much - more as a general API convenience.  It's true though that anyone wanting it can just do the transform compactly themselves.
